from typing import Dict, NamedTuple, Optional, Set
from .Options import Ys8Options
from BaseClasses import Item, ItemClassification


class Ys8Item(Item):
    game: str = "Ys 8"


class Ys8ItemData(NamedTuple):
    category: str
    code: int
    type: str
    classification: ItemClassification = ItemClassification.filler
    weight: int = 1
    is_party_member: bool = False
    battle_logic: bool = False
    quantity: int = 1
    pool_quantity: int = 1
    landmark_default_location: Optional[str] = None

def get_items_by_category(category: str) -> Dict[str, Ys8ItemData]:
    return {name: data for name, data in item_table.items() if data.category == category}

def get_item_pool_quantity(item_name: str, data: Ys8ItemData, options: Ys8Options) -> int:
    if item_name == "Flame Stone":
        return data.pool_quantity + options.extra_flame_stones
    return data.pool_quantity

item_table: Dict[str, Ys8ItemData] = {
    "Mistilteinn": Ys8ItemData("Weapon", code = 900, classification = ItemClassification.useful, type = "Item", battle_logic = True, pool_quantity = 1),
    "Spirit Ring Celesdia": Ys8ItemData("Weapon", code = 1300, classification = ItemClassification.useful, type = "Item", battle_logic = True, pool_quantity = 1),
    "Bone Necklace": Ys8ItemData("Accessory", code = 15100, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Bone Necklace II": Ys8ItemData("Accessory", code = 15200, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Bone Necklace III": Ys8ItemData("Accessory", code = 15300, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Blade Ring": Ys8ItemData("Accessory", code = 15500, classification = ItemClassification.useful, type = "Item", battle_logic = True, pool_quantity = 1),
    "Blade Ring II": Ys8ItemData("Accessory", code = 15600, classification = ItemClassification.useful, type = "Item", battle_logic = True, pool_quantity = 1),
    "Blade Ring III": Ys8ItemData("Accessory", code = 15700, classification = ItemClassification.useful, type = "Item", battle_logic = True, pool_quantity = 1),
    "Shield Earring": Ys8ItemData("Accessory", code = 15900, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Shield earring II": Ys8ItemData("Accessory", code = 16000, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Shield Earrings III": Ys8ItemData("Accessory", code = 16100, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Snake Amulet": Ys8ItemData("Accessory", code = 16300, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Lightning Amulet": Ys8ItemData("Accessory", code = 16500, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Crow Amulet": Ys8ItemData("Accessory", code = 16700, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Fenrir Talisman": Ys8ItemData("Accessory", code = 16900, classification = ItemClassification.useful, type = "Item", battle_logic = True, pool_quantity = 1),
    "Pyrios Talisman": Ys8ItemData("Accessory", code = 17100, classification = ItemClassification.useful, type = "Item", battle_logic = True, pool_quantity = 1),
    "Pyrios Stone": Ys8ItemData("Accessory", code = 17200, classification = ItemClassification.useful, type = "Item", battle_logic = True, pool_quantity = 1),
    "Nature Talisman": Ys8ItemData("Accessory", code = 17500, classification = ItemClassification.useful, type = "Item", pool_quantity = 2),
    "Warrior's Mark": Ys8ItemData("Accessory", code = 17600, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Warrior's Seal II": Ys8ItemData("Accessory", code = 17700, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Warrior's Mark III": Ys8ItemData("Accessory", code = 17800, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Warrior's Mark IV": Ys8ItemData("Accessory", code = 17900, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Red Cape": Ys8ItemData("Accessory", code = 18000, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Blue Cape": Ys8ItemData("Accessory", code = 18200, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Blue Moon Talisman": Ys8ItemData("Accessory", code = 18300, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Sun Talisman": Ys8ItemData("Accessory", code = 18500, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Hunter Hat": Ys8ItemData("Accessory", code = 18600, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Blood Fang": Ys8ItemData("Accessory", code = 19000, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Athlete's Ring": Ys8ItemData("Accessory", code = 19200, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Athlete Belt": Ys8ItemData("Accessory", code = 19300, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Hero's Belt": Ys8ItemData("Accessory", code = 19500, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Legend's Belt": Ys8ItemData("Accessory", code = 19600, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Wanderer Cloak": Ys8ItemData("Accessory", code = 19700, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Tiger Claw": Ys8ItemData("Accessory", code = 19900, classification = ItemClassification.useful, type = "Item", pool_quantity = 2),
    "Eagle Feather": Ys8ItemData("Accessory", code = 20000, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Hawk Wing": Ys8ItemData("Accessory", code = 20100, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Feather Boots": Ys8ItemData("Accessory", code = 20200, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Jade Pendant": Ys8ItemData("Accessory", code = 20600, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Ocean Hogeki": Ys8ItemData("Accessory", code = 20900, classification = ItemClassification.useful, type = "Item", battle_logic = True, pool_quantity = 1),
    "Earth Orb": Ys8ItemData("Accessory", code = 21000, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Sky Crown": Ys8ItemData("Accessory", code = 21100, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Saint's Ring": Ys8ItemData("Accessory", code = 21200, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Spirit Necklace": Ys8ItemData("Accessory", code = 21300, classification = ItemClassification.useful, type = "Item", pool_quantity = 3),
    "Prominent Cloak": Ys8ItemData("Accessory", code = 21500, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Slash Medal": Ys8ItemData("Accessory", code = 21800, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Leather Armor x2": Ys8ItemData("Accessory", code = 24300, classification = ItemClassification.useful, type = "Item", quantity = 2, pool_quantity = 1),
    "Needle Wristband": Ys8ItemData("Accessory", code = 25200, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Iron Shield": Ys8ItemData("Accessory", code = 25300, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Stone Glove": Ys8ItemData("Accessory", code = 25400, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Gauntlet": Ys8ItemData("Accessory", code = 25500, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Red Glove": Ys8ItemData("Accessory", code = 25700, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Dark Glove": Ys8ItemData("Accessory", code = 25800, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Bandit Gloves": Ys8ItemData("Accessory", code = 25900, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Blue Glove": Ys8ItemData("Accessory", code = 26000, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Soft Leather Gloves": Ys8ItemData("Accessory", code = 26600, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Prickly Band": Ys8ItemData("Accessory", code = 26700, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Tektite Shield": Ys8ItemData("Accessory", code = 26800, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Bolt Bracelet": Ys8ItemData("Accessory", code = 26900, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Heavy Gauntlet": Ys8ItemData("Accessory", code = 27000, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Warrior Wrist": Ys8ItemData("Accessory", code = 27100, classification = ItemClassification.useful, type = "Item", battle_logic = True, pool_quantity = 1),
    "Crimson Bracelet": Ys8ItemData("Accessory", code = 27200, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Black Bracelet": Ys8ItemData("Accessory", code = 27300, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Blue Bracelet": Ys8ItemData("Accessory", code = 27500, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Barbaric Bracelet": Ys8ItemData("Accessory", code = 27600, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Abyssal Gauntlet": Ys8ItemData("Accessory", code = 28800, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Bandit Gauntlets": Ys8ItemData("Accessory", code = 28900, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Blizzard Gauntlets": Ys8ItemData("Accessory", code = 29000, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Eternal Gauntlets": Ys8ItemData("Accessory", code = 29300, classification = ItemClassification.useful, type = "Item", pool_quantity = 3),
    "Light Arm Guard": Ys8ItemData("Accessory", code = 29500, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Thunder Gauntlets": Ys8ItemData("Accessory", code = 29700, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Ancient Bone": Ys8ItemData("Consumable", code = 30300, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Beast Hide x2": Ys8ItemData("Consumable", code = 30700, classification = ItemClassification.filler, type = "Item", quantity = 2, pool_quantity = 1),
    "Ancient Hide": Ys8ItemData("Consumable", code = 30800, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Sterile Mucus x5": Ys8ItemData("Consumable", code = 31100, classification = ItemClassification.filler, type = "Item", quantity = 5, pool_quantity = 1),
    "Sparkling Mucus x2": Ys8ItemData("Consumable", code = 31200, classification = ItemClassification.filler, type = "Item", quantity = 2, pool_quantity = 1),
    "Sturdy Lumber x3": Ys8ItemData("Consumable", code = 31600, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Beautiful Flower x5": Ys8ItemData("Consumable", code = 32100, classification = ItemClassification.filler, type = "Item", quantity = 5, pool_quantity = 1),
    "Iron Ore x3": Ys8ItemData("Consumable", code = 32600, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Iron Ore x5": Ys8ItemData("Consumable", code = 32601, classification = ItemClassification.filler, type = "Item", quantity = 5, pool_quantity = 1),
    "Tektite Ore x2": Ys8ItemData("Consumable", code = 32700, classification = ItemClassification.filler, type = "Item", quantity = 2, pool_quantity = 1),
    "Tektite Ore x3": Ys8ItemData("Consumable", code = 32701, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Tektite Ore x5": Ys8ItemData("Consumable", code = 32702, classification = ItemClassification.filler, type = "Item", quantity = 5, pool_quantity = 1),
    "Essence Stone": Ys8ItemData("Consumable", code = 32800, classification = ItemClassification.filler, type = "Item", pool_quantity = 10),
    "Essence Stone x2": Ys8ItemData("Consumable", code = 32801, classification = ItemClassification.filler, type = "Item", quantity = 2, pool_quantity = 1),
    "Essence Stone x3": Ys8ItemData("Consumable", code = 32802, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Beast Claw x3": Ys8ItemData("Consumable", code = 40000, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Remex x5": Ys8ItemData("Consumable", code = 40100, classification = ItemClassification.filler, type = "Item", quantity = 5, pool_quantity = 1),
    "Gwaranga Pincer x2": Ys8ItemData("Consumable", code = 40400, classification = ItemClassification.filler, type = "Item", quantity = 2, pool_quantity = 1),
    "Bullfrodon Mucus": Ys8ItemData("Consumable", code = 40500, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Digitalis Leaf x3": Ys8ItemData("Consumable", code = 41900, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Digitalis Leaf x5": Ys8ItemData("Consumable", code = 41901, classification = ItemClassification.filler, type = "Item", quantity = 5, pool_quantity = 1),
    "Sword Tip Fang x3": Ys8ItemData("Consumable", code = 42000, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Razor Feather x3": Ys8ItemData("Consumable", code = 42100, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Accursed Shell x3": Ys8ItemData("Consumable", code = 42200, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Lustrous Scale x3": Ys8ItemData("Consumable", code = 42300, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Salamandine Hide x3": Ys8ItemData("Consumable", code = 42400, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Large Pearl": Ys8ItemData("Consumable", code = 43600, classification = ItemClassification.filler, type = "Item", battle_logic = True, pool_quantity = 5),
    "Large Pearl x3": Ys8ItemData("Consumable", code = 43601, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Glow Rock": Ys8ItemData("Consumable", code = 43700, classification = ItemClassification.filler, type = "Item", pool_quantity = 2),
    "Glow Rock x3": Ys8ItemData("Consumable", code = 43701, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Stalactite x3": Ys8ItemData("Consumable", code = 43800, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Thunder Claw x3": Ys8ItemData("Consumable", code = 44000, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Blue Sky Feather x3": Ys8ItemData("Consumable", code = 44100, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Diamond Shell x3": Ys8ItemData("Consumable", code = 44200, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Rigid Fiber": Ys8ItemData("Consumable", code = 44300, classification = ItemClassification.filler, type = "Item", pool_quantity = 4),
    "Rigid Fiber x2": Ys8ItemData("Consumable", code = 44301, classification = ItemClassification.filler, type = "Item", quantity = 2, pool_quantity = 1),
    "Rigid Fiber x3": Ys8ItemData("Consumable", code = 44302, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Vivine Bitters x2": Ys8ItemData("Consumable", code = 44400, classification = ItemClassification.filler, type = "Item", quantity = 2, pool_quantity = 1),
    "Saurian Scale": Ys8ItemData("Consumable", code = 44600, classification = ItemClassification.filler, type = "Item", pool_quantity = 3),
    "Saurian Scale x2": Ys8ItemData("Consumable", code = 44601, classification = ItemClassification.filler, type = "Item", quantity = 2, pool_quantity = 1),
    "Moonlight Grass x3": Ys8ItemData("Consumable", code = 45700, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Rim Flower": Ys8ItemData("Consumable", code = 45900, classification = ItemClassification.filler, type = "Item", pool_quantity = 2),
    "Rim Flower x2": Ys8ItemData("Consumable", code = 45901, classification = ItemClassification.filler, type = "Item", quantity = 2, pool_quantity = 1),
    "Sunlight Fang x2": Ys8ItemData("Consumable", code = 46000, classification = ItemClassification.filler, type = "Item", quantity = 2, pool_quantity = 1),
    "Lunar Wing x2": Ys8ItemData("Consumable", code = 46100, classification = ItemClassification.filler, type = "Item", quantity = 2, pool_quantity = 1),
    "Starry Shell x2": Ys8ItemData("Consumable", code = 46200, classification = ItemClassification.filler, type = "Item", quantity = 2, pool_quantity = 1),
    "Acidic Liquid": Ys8ItemData("Consumable", code = 46300, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Dandale Horn": Ys8ItemData("Consumable", code = 46500, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Prismatic Jewel": Ys8ItemData("Consumable", code = 47600, classification = ItemClassification.progression, type = "Item", pool_quantity = 17),
    "Prismatic Jewel x2": Ys8ItemData("Consumable", code = 47601, classification = ItemClassification.progression, type = "Item", quantity = 2, pool_quantity = 1),
    "Prismatic Jewel x3": Ys8ItemData("Consumable", code = 47602, classification = ItemClassification.progression, type = "Item", quantity = 3, pool_quantity = 1),
    "Prismatic Jewel x5": Ys8ItemData("Consumable", code = 47603, classification = ItemClassification.progression, type = "Item", quantity = 5, pool_quantity = 1),
    "Dragon Crest Stone": Ys8ItemData("Consumable", code = 47800, classification = ItemClassification.filler, type = "Item", pool_quantity = 3),
    "Dragon Crest Stone x2": Ys8ItemData("Consumable", code = 47801, classification = ItemClassification.filler, type = "Item", quantity = 2, pool_quantity = 1),
    "Great Tree Lumber": Ys8ItemData("Consumable", code = 47900, classification = ItemClassification.filler, type = "Item", pool_quantity = 3),
    "Great Tree Lumber x2": Ys8ItemData("Consumable", code = 47901, classification = ItemClassification.filler, type = "Item", quantity = 2, pool_quantity = 1),
    "Saurian Carapace": Ys8ItemData("Consumable", code = 48600, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Rivera's Immortal Flower x3": Ys8ItemData("Consumable", code = 49700, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Pure Orichalcum": Ys8ItemData("Consumable", code = 49800, classification = ItemClassification.useful, type = "Item", pool_quantity = 3),
    "Aura Grass": Ys8ItemData("Consumable", code = 49900, classification = ItemClassification.filler, type = "Item", pool_quantity = 8),
    "Aura Grass x2": Ys8ItemData("Consumable", code = 49901, classification = ItemClassification.filler, type = "Item", quantity = 2, pool_quantity = 1),
    "Aura Grass x3": Ys8ItemData("Consumable", code = 49902, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Heal Potion": Ys8ItemData("Consumable", code = 50000, classification = ItemClassification.filler, type = "Item", pool_quantity = 4),
    "Full Potion": Ys8ItemData("Consumable", code = 50100, classification = ItemClassification.filler, type = "Item", pool_quantity = 2),
    "Revive Medicine": Ys8ItemData("Consumable", code = 50300, classification = ItemClassification.filler, type = "Item", pool_quantity = 4),
    "Great Tree Drop": Ys8ItemData("Consumable", code = 50400, classification = ItemClassification.useful, type = "Item", pool_quantity = 2),
    "Dynastic Water": Ys8ItemData("Consumable", code = 50700, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Medicine": Ys8ItemData("Consumable", code = 50800, classification = ItemClassification.filler, type = "Item", pool_quantity = 4),
    "Full Medicine": Ys8ItemData("Consumable", code = 50900, classification = ItemClassification.filler, type = "Item", pool_quantity = 6),
    "Antidote x3": Ys8ItemData("Consumable", code = 51000, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Antidote x5": Ys8ItemData("Consumable", code = 51001, classification = ItemClassification.filler, type = "Item", quantity = 5, pool_quantity = 1),
    "Eye Drops x3": Ys8ItemData("Consumable", code = 51100, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Eye Drops x5": Ys8ItemData("Consumable", code = 51101, classification = ItemClassification.filler, type = "Item", quantity = 5, pool_quantity = 1),
    "Antiparalytic": Ys8ItemData("Consumable", code = 51200, classification = ItemClassification.filler, type = "Item", pool_quantity = 7),
    "Antiparalytic x3": Ys8ItemData("Consumable", code = 51201, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Antiparalytic x5": Ys8ItemData("Consumable", code = 51202, classification = ItemClassification.filler, type = "Item", quantity = 5, pool_quantity = 1),
    "Defrost Medicine x3": Ys8ItemData("Consumable", code = 51300, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Defrost Medicine x5": Ys8ItemData("Consumable", code = 51301, classification = ItemClassification.filler, type = "Item", quantity = 5, pool_quantity = 1),
    "Burn Medicine x3": Ys8ItemData("Consumable", code = 51400, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Burn Medicine x5": Ys8ItemData("Consumable", code = 51401, classification = ItemClassification.filler, type = "Item", quantity = 5, pool_quantity = 1),
    "Hemostatic": Ys8ItemData("Consumable", code = 51500, classification = ItemClassification.filler, type = "Item", pool_quantity = 6),
    "Hemostatic x3": Ys8ItemData("Consumable", code = 51501, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Hemostatic x5": Ys8ItemData("Consumable", code = 51502, classification = ItemClassification.filler, type = "Item", quantity = 5, pool_quantity = 1),
    "Remedy x3": Ys8ItemData("Consumable", code = 51600, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Antiparalytic x3": Ys8ItemData("Consumable", code = 51700, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Burn Medicine x3": Ys8ItemData("Consumable", code = 51800, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Remedy x3": Ys8ItemData("Consumable", code = 51900, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Sweet Remedy": Ys8ItemData("Consumable", code = 52000, classification = ItemClassification.filler, type = "Item", pool_quantity = 5),
    "Sweet Remedy x3": Ys8ItemData("Consumable", code = 52001, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Sweet Remedy x5": Ys8ItemData("Consumable", code = 52002, classification = ItemClassification.filler, type = "Item", quantity = 5, pool_quantity = 1),
    "Bitter Remedy": Ys8ItemData("Consumable", code = 52100, classification = ItemClassification.filler, type = "Item", pool_quantity = 4),
    "Bitter Remedy x2": Ys8ItemData("Consumable", code = 52101, classification = ItemClassification.filler, type = "Item", quantity = 2, pool_quantity = 1),
    "Bitter Remedy x3": Ys8ItemData("Consumable", code = 52102, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Hermit's Elixir": Ys8ItemData("Consumable", code = 52200, classification = ItemClassification.filler, type = "Item", pool_quantity = 10),
    "Hermit's Elixir x3": Ys8ItemData("Consumable", code = 52201, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Strength Elixir": Ys8ItemData("Consumable", code = 52300, classification = ItemClassification.filler, type = "Item", pool_quantity = 7),
    "Strength Elixir x3": Ys8ItemData("Consumable", code = 52301, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Defense Elixir": Ys8ItemData("Consumable", code = 52400, classification = ItemClassification.filler, type = "Item", pool_quantity = 10),
    "Defense Elixir x3": Ys8ItemData("Consumable", code = 52401, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Life Elixir": Ys8ItemData("Consumable", code = 52500, classification = ItemClassification.filler, type = "Item", pool_quantity = 7),
    "Life Elixir x3": Ys8ItemData("Consumable", code = 52501, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Spirit Elixir": Ys8ItemData("Consumable", code = 52600, classification = ItemClassification.useful, type = "Item", pool_quantity = 6),
    "Tempest Elixir": Ys8ItemData("Consumable", code = 52700, classification = ItemClassification.filler, type = "Item", pool_quantity = 3),
    "Beastiary Potion": Ys8ItemData("Consumable", code = 52800, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Coconut x2": Ys8ItemData("Consumable", code = 53100, classification = ItemClassification.filler, type = "Item", quantity = 2, pool_quantity = 1),
    "Mango x2": Ys8ItemData("Consumable", code = 53200, classification = ItemClassification.filler, type = "Item", quantity = 2, pool_quantity = 1),
    "Mango x5": Ys8ItemData("Consumable", code = 53201, classification = ItemClassification.filler, type = "Item", quantity = 5, pool_quantity = 1),
    "Dragon Tree Treasure": Ys8ItemData("Consumable", code = 53300, classification = ItemClassification.filler, type = "Item", pool_quantity = 12),
    "Ripe Crudberry": Ys8ItemData("Consumable", code = 53500, classification = ItemClassification.filler, type = "Item", pool_quantity = 4),
    "Ripe Crudberry x2": Ys8ItemData("Consumable", code = 53501, classification = ItemClassification.filler, type = "Item", quantity = 2, pool_quantity = 1),
    "Ripe Crudberry x3": Ys8ItemData("Consumable", code = 53502, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Ripe Coconut": Ys8ItemData("Consumable", code = 53600, classification = ItemClassification.filler, type = "Item", pool_quantity = 7),
    "Ripe Coconut x2": Ys8ItemData("Consumable", code = 53601, classification = ItemClassification.filler, type = "Item", quantity = 2, pool_quantity = 1),
    "Ripe Coconut x3": Ys8ItemData("Consumable", code = 53602, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Ripe Mango": Ys8ItemData("Consumable", code = 53700, classification = ItemClassification.filler, type = "Item", pool_quantity = 13),
    "Ripe Mango x2": Ys8ItemData("Consumable", code = 53701, classification = ItemClassification.filler, type = "Item", quantity = 2, pool_quantity = 1),
    "Ripe Mango x3": Ys8ItemData("Consumable", code = 53702, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Dragon Tree Treasure": Ys8ItemData("Consumable", code = 53800, classification = ItemClassification.filler, type = "Item", pool_quantity = 12),
    "Dragon Tree Treasure x3": Ys8ItemData("Consumable", code = 53801, classification = ItemClassification.filler, type = "Item", quantity = 3, pool_quantity = 1),
    "Hope Stone": Ys8ItemData("Accessory", code = 54200, classification = ItemClassification.useful, type = "Item", battle_logic = True, pool_quantity = 2),
    "Luminous Ring": Ys8ItemData("Accessory", code = 54300, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Devil Fang": Ys8ItemData("Accessory", code = 54400, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Wings of Heavenly Light": Ys8ItemData("Accessory", code = 54500, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Wheel of Eternity": Ys8ItemData("Accessory", code = 54600, classification = ItemClassification.useful, type = "Item", pool_quantity = 2),
    "Crown of Creation": Ys8ItemData("Accessory", code = 54700, classification = ItemClassification.useful, type = "Item", pool_quantity = 2),
    "Stone of Anitquity": Ys8ItemData("Accessory", code = 54800, classification = ItemClassification.useful, type = "Item", battle_logic = True, pool_quantity = 2),
    "Garment of Many Tongues": Ys8ItemData("Accessory", code = 54900, classification = ItemClassification.useful, type = "Item", pool_quantity = 3),
    "Recipe Book/Mushroom Omelet": Ys8ItemData("Recipe Book", code = 56900, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Recipe Book/Hearty Ratatouille": Ys8ItemData("Recipe Book", code = 57000, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Recipe Book/Colorful Meuniere": Ys8ItemData("Recipe Book", code = 57100, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Recipe Book/Seafood Quiche": Ys8ItemData("Recipe Book", code = 57200, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Recipe Book/Cabbage Rolls": Ys8ItemData("Recipe Book", code = 57300, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Recipe Book/Meat-Wrapped Mushrooms": Ys8ItemData("Recipe Book", code = 57400, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Recipe Book/Fish Fry": Ys8ItemData("Recipe Book", code = 57500, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Recipe Book/Pirate's Platter": Ys8ItemData("Recipe Book", code = 57600, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Recipe Book/Luxury Coleslaw": Ys8ItemData("Recipe Book", code = 57700, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Recipe Book/Heartfelt Bolognese": Ys8ItemData("Recipe Book", code = 57800, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Recipe Book/Great Pumpkin Pie": Ys8ItemData("Recipe Book", code = 57900, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Spiral Manual": Ys8ItemData("Consumable", code = 58300, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Fairy Manual": Ys8ItemData("Consumable", code = 58400, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Wild Manual": Ys8ItemData("Consumable", code = 58500, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Tremor Manual": Ys8ItemData("Consumable", code = 58600, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Thorn Manual": Ys8ItemData("Consumable", code = 58700, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Freeze Manual": Ys8ItemData("Consumable", code = 58800, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Forest Guide": Ys8ItemData("Consumable", code = 59000, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Ocean Guide": Ys8ItemData("Consumable", code = 59100, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Mountain Guide": Ys8ItemData("Consumable", code = 59200, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Wind Guide": Ys8ItemData("Consumable", code = 59300, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Seiren Wheat x5": Ys8ItemData("Consumable", code = 60200, classification = ItemClassification.filler, type = "Item", quantity = 5, pool_quantity = 1),
    "Pheasant Egg x5": Ys8ItemData("Consumable", code = 60300, classification = ItemClassification.filler, type = "Item", quantity = 5, pool_quantity = 1),
    "Sweet Pepper x5": Ys8ItemData("Consumable", code = 60900, classification = ItemClassification.filler, type = "Item", quantity = 5, pool_quantity = 1),
    "Eggplant Seed": Ys8ItemData("Consumable", code = 61000, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Shiny Corn x5": Ys8ItemData("Consumable", code = 61200, classification = ItemClassification.filler, type = "Item", quantity = 5, pool_quantity = 1),
    "King Pumpkin x2": Ys8ItemData("Consumable", code = 61400, classification = ItemClassification.filler, type = "Item", quantity = 2, pool_quantity = 1),
    "Strength Elixir": Ys8ItemData("Consumable", code = 61700, classification = ItemClassification.filler, type = "Item", pool_quantity = 7),
    "Defense Elixir": Ys8ItemData("Consumable", code = 61800, classification = ItemClassification.filler, type = "Item", pool_quantity = 10),
    "Life Elixir": Ys8ItemData("Consumable", code = 61900, classification = ItemClassification.filler, type = "Item", pool_quantity = 7),
    "Empty Bottle": Ys8ItemData("Consumable", code = 62000, classification = ItemClassification.filler, type = "Item", pool_quantity = 2),
    "Bait x5": Ys8ItemData("Consumable", code = 62800, classification = ItemClassification.filler, type = "Item", quantity = 5, pool_quantity = 1),
    "Bait x10": Ys8ItemData("Consumable", code = 62801, classification = ItemClassification.filler, type = "Item", quantity = 10, pool_quantity = 1),
    "Fishing Rod": Ys8ItemData("Consumable", code = 62900, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Energy Fragment x50": Ys8ItemData("Consumable", code = 67000, classification = ItemClassification.filler, type = "Item", quantity = 50, pool_quantity = 1),
    "Energy Fragment x100": Ys8ItemData("Consumable", code = 67001, classification = ItemClassification.filler, type = "Item", quantity = 100, pool_quantity = 1),
    "Energy Fragment x150": Ys8ItemData("Consumable", code = 67002, classification = ItemClassification.filler, type = "Item", quantity = 150, pool_quantity = 1),
    "Eyedrop Formula": Ys8ItemData("Consumable", code = 68700, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Blood Formula": Ys8ItemData("Consumable", code = 68900, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Delight Formula": Ys8ItemData("Consumable", code = 69000, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Bitter Formula": Ys8ItemData("Consumable", code = 69100, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Bless Formula": Ys8ItemData("Consumable", code = 69200, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Life Formula": Ys8ItemData("Consumable", code = 69300, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Hide Formula": Ys8ItemData("Consumable", code = 69400, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Strength Formula": Ys8ItemData("Consumable", code = 69500, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Defense Formula": Ys8ItemData("Consumable", code = 69600, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Maiden Journal": Ys8ItemData("Consumable", code = 69800, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Frozen Flower": Ys8ItemData("Consumable", code = 69900, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Blue Seal of Whirling Water": Ys8ItemData("Consumable", code = 70000, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Green Seal of Roaring Stone": Ys8ItemData("Consumable", code = 70100, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Golden Seal of Piercing Light": Ys8ItemData("Consumable", code = 70200, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Essence Key Stone": Ys8ItemData("Consumable", code = 70300, classification = ItemClassification.filler, type = "Item", pool_quantity = 9),
    "Battle Armlet": Ys8ItemData("Consumable", code = 72000, classification = ItemClassification.useful, type = "Item", battle_logic = True, pool_quantity = 2),
    "Dragon Bone Necklace": Ys8ItemData("Consumable", code = 72200, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Mushin's hairpin": Ys8ItemData("Consumable", code = 72500, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Fairy Cape": Ys8ItemData("Consumable", code = 72600, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Shrine Maiden Amulet": Ys8ItemData("Consumable", code = 72700, classification = ItemClassification.progression, type = "Item", battle_logic = True, pool_quantity = 1),
    "Stone Crown": Ys8ItemData("Consumable", code = 72900, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Blue Wind Staff": Ys8ItemData("Adventure Gear", code = 73000, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Nature Talisman": Ys8ItemData("Adventure Gear", code = 73100, classification = ItemClassification.useful, type = "Item", pool_quantity = 2),
    "Gale Feather": Ys8ItemData("Adventure Gear", code = 73500, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Windy Vestment": Ys8ItemData("Adventure Gear", code = 73600, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Grip Gloves": Ys8ItemData("Adventure Gear", code = 73700, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Hermit's Scale": Ys8ItemData("Adventure Gear", code = 73800, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Glow Stone": Ys8ItemData("Adventure Gear", code = 73900, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Float Shoes": Ys8ItemData("Adventure Gear", code = 74000, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Archeopteryx Wings": Ys8ItemData("Adventure Gear", code = 74100, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Purifying Bell": Ys8ItemData("Adventure Gear", code = 74200, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Ares Seal": Ys8ItemData("Adventure Gear", code = 74300, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Aeolus Urn": Ys8ItemData("Adventure Gear", code = 74400, classification = ItemClassification.useful, type = "Item", pool_quantity = 1),
    "Eagle Eye Orb": Ys8ItemData("Adventure Gear", code = 74500, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Pirate's Notes": Ys8ItemData("Consumable", code = 75000, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Pirate Memo A": Ys8ItemData("Consumable", code = 75100, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Pirate Memo B": Ys8ItemData("Consumable", code = 75200, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Pirate Memo C": Ys8ItemData("Consumable", code = 75300, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Pirate Memo D": Ys8ItemData("Consumable", code = 75400, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Pirate's Memo E": Ys8ItemData("Consumable", code = 75500, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "T's Memo": Ys8ItemData("Consumable", code = 76000, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "T's Memo A": Ys8ItemData("Consumable", code = 76100, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "T's Memo B": Ys8ItemData("Consumable", code = 76200, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "T's Memo C": Ys8ItemData("Consumable", code = 76300, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Logbook 1": Ys8ItemData("Consumable", code = 77000, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Logbook 2": Ys8ItemData("Consumable", code = 77100, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Logbook 3": Ys8ItemData("Consumable", code = 77200, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Logbook 4": Ys8ItemData("Consumable", code = 77300, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Logbook 5": Ys8ItemData("Consumable", code = 77400, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Monolith Fragment": Ys8ItemData("Consumable", code = 77700, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Flame Stone": Ys8ItemData("Consumable", code = 77800, classification = ItemClassification.progression, type = "Item", pool_quantity = 7),
    "Ship Blueprint": Ys8ItemData("Consumable", code = 77900, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Sweet Pepper Seeds": Ys8ItemData("Consumable", code = 78000, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Shiny Corn Seeds": Ys8ItemData("Consumable", code = 78300, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Queen Tomato Seeds": Ys8ItemData("Consumable", code = 78400, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "King Pumpkin seeds": Ys8ItemData("Consumable", code = 78500, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Seiren Nautical Chart": Ys8ItemData("Consumable", code = 79500, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Treasure Chest Key": Ys8ItemData("Consumable", code = 79600, classification = ItemClassification.progression, type = "Item", pool_quantity = 1),
    "Romun Badge": Ys8ItemData("Consumable", code = 80100, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Rainbow Pigment": Ys8ItemData("Consumable", code = 80300, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Ship Nameplate": Ys8ItemData("Consumable", code = 80400, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Violet Bookmark": Ys8ItemData("Consumable", code = 80800, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Engraved Pen": Ys8ItemData("Consumable", code = 81300, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Gold Essence Crystal": Ys8ItemData("Consumable", code = 81500, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Ancient Coin": Ys8ItemData("Consumable", code = 81600, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Iron Knuckle": Ys8ItemData("Consumable", code = 81800, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Snowflake Soap": Ys8ItemData("Consumable", code = 81900, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Big Seed": Ys8ItemData("Consumable", code = 82700, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Old Stethoscope": Ys8ItemData("Consumable", code = 82900, classification = ItemClassification.filler, type = "Item", pool_quantity = 1),
    "Laxia": Ys8ItemData("Crew", code = 90100, classification = ItemClassification.progression, type = "SetFlag", is_party_member = True, pool_quantity = 1),
    "Captain Barbaros": Ys8ItemData("Crew", code = 90200, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Little Paro": Ys8ItemData("Crew", code = 90300, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Sahad": Ys8ItemData("Crew", code = 90400, classification = ItemClassification.progression, type = "SetFlag", is_party_member = True, pool_quantity = 1),
    "Dogi": Ys8ItemData("Crew", code = 90500, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Alison": Ys8ItemData("Crew", code = 90600, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Sir Carlan": Ys8ItemData("Crew", code = 90700, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Kiergaard": Ys8ItemData("Crew", code = 90800, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Sister Nia": Ys8ItemData("Crew", code = 90900, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Hummel": Ys8ItemData("Crew", code = 91000, classification = ItemClassification.progression, type = "SetFlag", is_party_member = True, pool_quantity = 1),
    "Dina": Ys8ItemData("Crew", code = 91100, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Reja": Ys8ItemData("Crew", code = 91200, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Euron": Ys8ItemData("Crew", code = 91300, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Licht": Ys8ItemData("Crew", code = 91400, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Quina": Ys8ItemData("Crew", code = 91500, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Ricotta": Ys8ItemData("Crew", code = 91600, classification = ItemClassification.progression, type = "SetFlag", is_party_member = True, pool_quantity = 1),
    "Austin": Ys8ItemData("Crew", code = 91700, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Miralda": Ys8ItemData("Crew", code = 91800, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Thanatos": Ys8ItemData("Crew", code = 91900, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Silvia": Ys8ItemData("Crew", code = 92000, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Dana": Ys8ItemData("Crew", code = 92100, classification = ItemClassification.progression, type = "SetFlag", is_party_member = True, pool_quantity = 1),
    "Katthew": Ys8ItemData("Crew", code = 92200, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Ed": Ys8ItemData("Crew", code = 92300, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Franz": Ys8ItemData("Crew", code = 92400, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Shoebill": Ys8ItemData("Crew", code = 92500, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Griselda": Ys8ItemData("Crew", code = 92600, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Master Kong": Ys8ItemData("Crew", code = 92700, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Adol": Ys8ItemData("Crew", code = 92800, classification = ItemClassification.progression, type = "SetFlag", is_party_member = True, pool_quantity = 1),
    "SKILL_ADOL_SP_C1": Ys8ItemData("Skill", code = 92900, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_ADOL_SP_C2": Ys8ItemData("Skill", code = 93000, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_LAXIA_SP_C1": Ys8ItemData("Skill", code = 93100, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_LAXIA_SP_C2": Ys8ItemData("Skill", code = 93200, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_SAHAD_SP_C1": Ys8ItemData("Skill", code = 93300, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_SAHAD_SP_C2": Ys8ItemData("Skill", code = 93400, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_HUMMEL_SP_C1": Ys8ItemData("Skill", code = 93500, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_HUMMEL_SP_C2": Ys8ItemData("Skill", code = 93600, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_RICOTTA_SP_C1": Ys8ItemData("Skill", code = 93700, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_RICOTTA_SP_C2": Ys8ItemData("Skill", code = 93800, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_DANA_SP_C1": Ys8ItemData("Skill", code = 93900, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_DANA_SP_C2": Ys8ItemData("Skill", code = 94000, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_DANA_SP_C4": Ys8ItemData("Skill", code = 94100, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_ADOL_SP_B1": Ys8ItemData("Skill", code = 94200, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_DANA_SP_A2": Ys8ItemData("Skill", code = 94300, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_DANA_SP_A3": Ys8ItemData("Skill", code = 94400, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_HUMMEL_SP_A3": Ys8ItemData("Skill", code = 94500, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_HUMMEL_SP_A2": Ys8ItemData("Skill", code = 94600, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_SAHAD_SP_A3": Ys8ItemData("Skill", code = 94700, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_SAHAD_SP_A2": Ys8ItemData("Skill", code = 94800, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_RICOTTA_SP_A3": Ys8ItemData("Skill", code = 94900, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_RICOTTA_SP_A1": Ys8ItemData("Skill", code = 95000, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_LAXIA_SP_A2": Ys8ItemData("Skill", code = 95100, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_LAXIA_SP_A3": Ys8ItemData("Skill", code = 95200, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_DANA_SP_B5": Ys8ItemData("Skill", code = 95300, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_ADOL_SP_A2": Ys8ItemData("Skill", code = 95400, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_RICOTTA_SP_B5": Ys8ItemData("Skill", code = 95500, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_SAHAD_SP_A1": Ys8ItemData("Skill", code = 95600, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_HUMMEL_SP_A1": Ys8ItemData("Skill", code = 95700, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_RICOTTA_SP_B4": Ys8ItemData("Skill", code = 95800, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_DANA_SP_B3": Ys8ItemData("Skill", code = 95900, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_SAHAD_SP_B5": Ys8ItemData("Skill", code = 96000, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_SAHAD_SP_B3": Ys8ItemData("Skill", code = 96100, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_SAHAD_SP_B4": Ys8ItemData("Skill", code = 96200, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_HUMMEL_SP_B3": Ys8ItemData("Skill", code = 96300, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_HUMMEL_SP_B4": Ys8ItemData("Skill", code = 96400, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_RICOTTA_SP_B1": Ys8ItemData("Skill", code = 96500, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_RICOTTA_SP_B2": Ys8ItemData("Skill", code = 96600, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_ADOL_SP_A1": Ys8ItemData("Skill", code = 96700, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_ADOL_SP_B5": Ys8ItemData("Skill", code = 96800, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_LAXIA_SP_B5": Ys8ItemData("Skill", code = 96900, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_LAXIA_SP_B4": Ys8ItemData("Skill", code = 97000, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_RICOTTA_SP_C4": Ys8ItemData("Skill", code = 97100, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_RICOTTA_SP_C3": Ys8ItemData("Skill", code = 97200, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_LAXIA_SP_B1": Ys8ItemData("Skill", code = 97300, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_LAXIA_SP_B2": Ys8ItemData("Skill", code = 97400, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_DANA_SP_B1": Ys8ItemData("Skill", code = 97500, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_DANA_SP_B2": Ys8ItemData("Skill", code = 97600, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_HUMMEL_SP_B2": Ys8ItemData("Skill", code = 97700, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_HUMMEL_SP_B1": Ys8ItemData("Skill", code = 97800, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_HUMMEL_SP_C3": Ys8ItemData("Skill", code = 97900, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_DANA_SP_C3": Ys8ItemData("Skill", code = 98000, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_ADOL_SP_B2": Ys8ItemData("Skill", code = 98100, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_ADOL_SP_B3": Ys8ItemData("Skill", code = 98200, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_SAHAD_SP_B1": Ys8ItemData("Skill", code = 98300, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_SAHAD_SP_B2": Ys8ItemData("Skill", code = 98400, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_LAXIA_SP_C3": Ys8ItemData("Skill", code = 98500, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_LAXIA_SP_C4": Ys8ItemData("Skill", code = 98600, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_ADOL_SP_C3": Ys8ItemData("Skill", code = 98700, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_ADOL_SP_C4": Ys8ItemData("Skill", code = 98800, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_RICOTTA_SP_A2": Ys8ItemData("Skill", code = 98900, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_SAHAD_SP_C4": Ys8ItemData("Skill", code = 99000, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_DANA_SP_B4": Ys8ItemData("Skill", code = 99100, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_LAXIA_SP_A1": Ys8ItemData("Skill", code = 99200, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_HUMMEL_SP_B5": Ys8ItemData("Skill", code = 99300, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
    "SKILL_ADOL_SP_A3": Ys8ItemData("Skill", code = 99400, classification = ItemClassification.useful, type = "SetFlag", pool_quantity = 1),
}

landmark_item_table: Dict[str, Ys8ItemData] = {
    "Birdsong Rock": Ys8ItemData("Landmark", code = 99500, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Cobalt Crag": Ys8ItemData("Landmark", code = 99600, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Rainbow Falls": Ys8ItemData("Landmark", code = 99700, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Metavolicalis": Ys8ItemData("Landmark", code = 99800, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Parasequoia": Ys8ItemData("Landmark", code = 99900, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Chimney Rock": Ys8ItemData("Landmark", code = 100000, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Indigo Mineral Vein": Ys8ItemData("Landmark", code = 100100, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Beached Remains": Ys8ItemData("Landmark", code = 100200, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Field of Medicinal Herbs": Ys8ItemData("Landmark", code = 100300, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Airs Cairn": Ys8ItemData("Landmark", code = 100400, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Zephyr Hill": Ys8ItemData("Landmark", code = 100500, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Lapis Mineral Vein": Ys8ItemData("Landmark", code = 100600, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Beehive": Ys8ItemData("Landmark", code = 100700, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Ship Graveyard": Ys8ItemData("Landmark", code = 100800, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Hidden Pirate Storehouse": Ys8ItemData("Landmark", code = 100900, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Magna Carpa": Ys8ItemData("Landmark", code = 101000, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Prismatic Mineral Vein": Ys8ItemData("Landmark", code = 101100, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Unicalamites": Ys8ItemData("Landmark", code = 101200, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Breath Fountain": Ys8ItemData("Landmark", code = 101300, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Ancient Tree": Ys8ItemData("Landmark", code = 101400, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Sky Garden": Ys8ItemData("Landmark", code = 101500, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Soundless Hall": Ys8ItemData("Landmark", code = 101600, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Graves of Ancient Heroes": Ys8ItemData("Landmark", code = 101700, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Milky White Vein": Ys8ItemData("Landmark", code = 101800, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
}

event_item_table: Dict[str, Ys8ItemData] = {
    "Avalodragil 2 Defeated": Ys8ItemData("Mont Gendarme Mid-Boss Arena Avalodragil 2", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Avalodragil Defeated": Ys8ItemData("Nameless Coast First Avalodragil Arena Avalodragil", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Basileus Defeated": Ys8ItemData("Valley of Kings Boss Arena Basileus", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Brachion Defeated": Ys8ItemData("Temple of the Great Tree Temple Boss Arena Brachion", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Byfteriza Defeated": Ys8ItemData("Waterdrop Cave Boss Arena Byfteriza", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Carveros Defeated": Ys8ItemData("Baja Tower Boss Arena Carveros", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Clareon Defeated": Ys8ItemData("Towering Coral Forest Boss Arena Clareon", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Coelacantos Defeated": Ys8ItemData("Archeozoic Chasm Mid-Boss Arena Coelacantos", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Doxa Griel Defeated": Ys8ItemData("Valley of Kings Mid-Boss Arena Doxa Griel", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "End the Lacrimosa": Ys8ItemData("Octus Overlook Selection Sphere Goal", code = None, classification = ItemClassification.progression, type = "Goal", pool_quantity = 1),
    "Exmetal Defeated": Ys8ItemData("Baja Tower Mid-Boss Arena Exmetal", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Gargantula Defeated": Ys8ItemData("Eroded Valley Boss Arena Gargantula", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Giasburn Defeated": Ys8ItemData("Mont Gendarme Boss Arena Giasburn", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Kiergaard Weissman Defeated": Ys8ItemData("Odd Rock Coast Odd Rock Coast Kiergaard Weissman", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Laspisus Defeated": Ys8ItemData("Schlamm Jungle Boss Arena Laspisus", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Lonbrigius Defeated": Ys8ItemData("Eroded Valley Mid-Boss Arena Lonbrigius", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Magamandra Defeated": Ys8ItemData("Schlamm Jungle Mid-Boss Arena Magamandra", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Master Kong Adol Defeated": Ys8ItemData("Vista Ridge Vista Ridge Lower Master Kong Adol", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Master Kong Dana Defeated": Ys8ItemData("Odd Rock Coast Odd Rock Coast Master Kong Dana", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Master Kong Hummel Defeated": Ys8ItemData("Pangaia Plains Ancient Tree Master Kong Hummel", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Master Kong Laxia Defeated": Ys8ItemData("Mont Gendarme Boss Arena Master Kong Laxia", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Master Kong Ricotta Defeated": Ys8ItemData("Roaring Seashore Parasequoia Master Kong Ricotta", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Master Kong Sahad Defeated": Ys8ItemData("Sunrise Beach Sunrise Beach Master Kong Sahad", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Melaiduma Defeated": Ys8ItemData("Former Sanctuary Crypt - Final Floor Boss Arena Melaiduma", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Mephorash Defeated": Ys8ItemData("Silent Tower Second Basement Mephorash", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Oceanus Defeated": Ys8ItemData("Archeozoic Chasm Boss Arena Oceanus", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Pirate Revenant Defeated": Ys8ItemData("Pirate Ship Eleftheria Deck Pirate Revenant", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Psyche-Hydra Defeated": Ys8ItemData("Octus Overlook Path of the Ocean Era Psyche-Hydra", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Psyche-Minos Defeated": Ys8ItemData("Octus Overlook Path of the Frozen Era Psyche-Minos", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Psyche-Nestor Defeated": Ys8ItemData("Octus Overlook Path of the Insectoid Era Psyche-Nestor", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Psyche-Ura Defeated": Ys8ItemData("Octus Overlook Path of the Sky Era Psyche-Ura", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Serpentus Defeated": Ys8ItemData("Towering Coral Forest Mid-Boss Arena Serpentus", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Silvia Defeated": Ys8ItemData("Calm Inlet Calm Inlet (Castaway Village Area) Silvia", code = None, classification = ItemClassification.progression, type = "Boss", pool_quantity = 1),
    "Force Garmr Defeated": Ys8ItemData("Lodinia Marshlands Back Force Garmr Encounter", code = None, classification = ItemClassification.progression, type = "Encounter", pool_quantity = 1),
    "Gilkyra Encounter Defeated": Ys8ItemData("East Coast Cave East Coast Cave Gilkyra Encounter", code = None, classification = ItemClassification.progression, type = "Encounter", pool_quantity = 1),
    # Grind area access events
    "Grind: Archeozoic Chasm": Ys8ItemData("Archeozoic Chasm Front Grind Access", code = None, classification = ItemClassification.progression, type = "Grind", pool_quantity = 1),
    "Grind: Baja Tower": Ys8ItemData("Baja Tower Lower Floors Grind Access", code = None, classification = ItemClassification.progression, type = "Grind", pool_quantity = 1),
    "Grind: Bolado Monastery": Ys8ItemData("Bolado Monastery Grind Access", code = None, classification = ItemClassification.progression, type = "Grind", pool_quantity = 1),
    "Grind: Eroded Valley": Ys8ItemData("Eroded Valley Front Grind Access", code = None, classification = ItemClassification.progression, type = "Grind", pool_quantity = 1),
    "Grind: Lodinia Marshlands": Ys8ItemData("Lodinia Marshlands Front Grind Access", code = None, classification = ItemClassification.progression, type = "Grind", pool_quantity = 1),
    "Grind: Mont Gendarme": Ys8ItemData("Mont Gendarme Front Grind Access", code = None, classification = ItemClassification.progression, type = "Grind", pool_quantity = 1),
    "Grind: Nostalgia Cape": Ys8ItemData("Nostalgia Cape Area Grind Access", code = None, classification = ItemClassification.progression, type = "Grind", pool_quantity = 1),
    "Grind: Octus Overlook": Ys8ItemData("Octus Overlook Grind Access", code = None, classification = ItemClassification.progression, type = "Grind", pool_quantity = 1),
    "Grind: Schlamm Jungle": Ys8ItemData("Schlamm Jungle Front Grind Access", code = None, classification = ItemClassification.progression, type = "Grind", pool_quantity = 1),
    "Grind: Seiren North Access": Ys8ItemData("Seiren North Access Grind Access", code = None, classification = ItemClassification.progression, type = "Grind", pool_quantity = 1),
    "Grind: Silent Tower": Ys8ItemData("Silent Tower Grind Access", code = None, classification = ItemClassification.progression, type = "Grind", pool_quantity = 1),
    "Grind: Temple of the Great Tree": Ys8ItemData("Temple of the Great Tree Grind Access", code = None, classification = ItemClassification.progression, type = "Grind", pool_quantity = 1),
    "Grind: Towal Highway": Ys8ItemData("Towal Highway Grind Access", code = None, classification = ItemClassification.progression, type = "Grind", pool_quantity = 1),
    "Grind: Towering Coral Forest": Ys8ItemData("Towering Coral Forest Front Grind Access", code = None, classification = ItemClassification.progression, type = "Grind", pool_quantity = 1),
    "Grind: Towering Coral Forest Rear": Ys8ItemData("Towering Coral Forest Before Boss Grind Access", code = None, classification = ItemClassification.progression, type = "Grind", pool_quantity = 1),
    "Grind: Valley of Kings": Ys8ItemData("Lodinia Marshlands Back Grind Access", code = None, classification = ItemClassification.progression, type = "Grind", pool_quantity = 1),
    "Grind: Western Foot of Gendarme": Ys8ItemData("Western Foot of Gendarme Grind Access", code = None, classification = ItemClassification.progression, type = "Grind", pool_quantity = 1),
    "Grind: Eroded Valley Rear": Ys8ItemData("Eroded Valley Before Boss Grind Access", code = None, classification = ItemClassification.progression, type = "Grind", pool_quantity = 1),
    "Grind: Schlamm Jungle Rear": Ys8ItemData("Schlamm Jungle Before Boss Grind Access", code = None, classification = ItemClassification.progression, type = "Grind", pool_quantity = 1),
    "Grind: Mont Gendarme Rear": Ys8ItemData("Mont Gendarme Upper Grind Access", code = None, classification = ItemClassification.progression, type = "Grind", pool_quantity = 1),
    "Grind: Lodinia Marshlands Rear": Ys8ItemData("Lodinia Marshlands Near Sky Garden Grind Access", code = None, classification = ItemClassification.progression, type = "Grind", pool_quantity = 1),
    "Grind: Mont Gendarme Night": Ys8ItemData("Mont Gendarme (Night) Grind Access", code = None, classification = ItemClassification.progression, type = "Grind", pool_quantity = 1),
    "Grind: Pangaia Plains Night": Ys8ItemData("Pangaia Plains (Night) Grind Access", code = None, classification = ItemClassification.progression, type = "Grind", pool_quantity = 1),
    "Grind: Towering Coral Forest Night": Ys8ItemData("Towering Coral Forest (Night) Grind Access", code = None, classification = ItemClassification.progression, type = "Grind", pool_quantity = 1),
    # Material farming access events
    "Material: Accursed Shell (Western Foot of Gendarme)": Ys8ItemData("Accursed Shell Farming - Western Foot of Gendarme", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Ancient Bone (Archeozoic Chasm)": Ys8ItemData("Ancient Bone Farming - Archeozoic Chasm", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Ancient Bone (Temple of the Great Tree)": Ys8ItemData("Ancient Bone Farming - Temple of the Great Tree", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Ancient Hide (Nostalgia Cape)": Ys8ItemData("Ancient Hide Farming - Nostalgia Cape", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Ancient Hide (Waterdrop Cave)": Ys8ItemData("Ancient Hide Farming - Waterdrop Cave", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Ancient Lumber (Octus Overlook)": Ys8ItemData("Ancient Lumber Farming - Octus Overlook", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Ancient Lumber (Temple of the Great Tree)": Ys8ItemData("Ancient Lumber Farming - Temple of the Great Tree", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Beast Bone (East Coast Cave)": Ys8ItemData("Beast Bone Farming - East Coast Cave", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Beast Bone (Vista Ridge)": Ys8ItemData("Beast Bone Farming - Vista Ridge", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Beast Claw (Western Foot of Gendarme)": Ys8ItemData("Beast Claw Farming - Western Foot of Gendarme", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Beast Hide (Schlamm Jungle)": Ys8ItemData("Beast Hide Farming - Schlamm Jungle", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Beast Hide (Western Foot of Gendarme)": Ys8ItemData("Beast Hide Farming - Western Foot of Gendarme", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Beautiful Flower (Nameless Coast)": Ys8ItemData("Beautiful Flower Farming - Nameless Coast", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Dandale Horn (Lodinia Marshlands)": Ys8ItemData("Dandale Horn Farming - Lodinia Marshlands", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Dragon Crest Stone (Silent Tower)": Ys8ItemData("Dragon Crest Stone Farming - Silent Tower", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Dragon Crest Stone (Valley of Kings)": Ys8ItemData("Dragon Crest Stone Farming - Valley of Kings", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Essence Stone (Baja Tower)": Ys8ItemData("Essence Stone Farming - Baja Tower", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Essence Stone (Valley of Kings)": Ys8ItemData("Essence Stone Farming - Valley of Kings", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Flexible Branch (Towering Coral Forest Night)": Ys8ItemData("Flexible Branch Farming - TCF Night", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Flexible Branch (Waterfall Grotto)": Ys8ItemData("Flexible Branch Farming - Waterfall Grotto", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Glow Rock (Towering Coral Forest Night)": Ys8ItemData("Glow Rock Farming - TCF Night", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Iron Ore (Eroded Valley)": Ys8ItemData("Iron Ore Farming - Eroded Valley", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Iron Ore (Towering Coral Forest)": Ys8ItemData("Iron Ore Farming - Towering Coral Forest", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Lustrous Scale (East Coast Cave)": Ys8ItemData("Lustrous Scale Farming - East Coast Cave", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Lustrous Scale (Nostalgia Cape)": Ys8ItemData("Lustrous Scale Farming - Nostalgia Cape", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Razor Feather (Schlamm Jungle)": Ys8ItemData("Razor Feather Farming - Schlamm Jungle", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Saurian Scale (Great River Valley)": Ys8ItemData("Saurian Scale Farming - Great River Valley", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Saurian Scale (Towal Highway)": Ys8ItemData("Saurian Scale Farming - Towal Highway", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Stalactite (Nameless Coast)": Ys8ItemData("Stalactite Farming - Nameless Coast", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Sword Tip Fang (Western Foot of Gendarme)": Ys8ItemData("Sword Tip Fang Farming - Western Foot of Gendarme", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Tektite Ore (Mont Gendarme)": Ys8ItemData("Tektite Ore Farming - Mont Gendarme", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Tektite Ore (Towal Highway)": Ys8ItemData("Tektite Ore Farming - Towal Highway", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Tektite Ore (Western Foot of Gendarme)": Ys8ItemData("Tektite Ore Farming - Western Foot of Gendarme", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Thick Hide (Schlamm Jungle)": Ys8ItemData("Thick Hide Farming - Schlamm Jungle", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Thick Hide (Western Foot of Gendarme)": Ys8ItemData("Thick Hide Farming - Western Foot of Gendarme", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Thunder Claw (Great River Valley)": Ys8ItemData("Thunder Claw Farming - Great River Valley", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Thunder Claw (Valley of Kings)": Ys8ItemData("Thunder Claw Farming - Valley of Kings", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Underworld Bone (Octus Overlook)": Ys8ItemData("Underworld Bone Farming - Octus Overlook", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
    "Material: Underworld Hide (Octus Overlook)": Ys8ItemData("Underworld Hide Farming - Octus Overlook", code = None, classification = ItemClassification.progression, type = "Material", pool_quantity = 1),
}

psyche_item_table: Dict[str, Ys8ItemData] = {
    "Psyches of the Sky Era": Ys8ItemData("Psyches", code = None, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Psyches of the Insectoid Era": Ys8ItemData("Psyches", code = None, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Psyches of the Ocean Era": Ys8ItemData("Psyches", code = None, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Psyches of the Frozen Era": Ys8ItemData("Psyches", code = None, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1)
}

psyche_access_item_table: Dict[str, Ys8ItemData] = {
    "Psyches of the Sky Era Access": Ys8ItemData("Psyches Access", code = None, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Psyches of the Insectoid Era Access": Ys8ItemData("Psyches Access", code = None, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Psyches of the Ocean Era Access": Ys8ItemData("Psyches Access", code = None, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1),
    "Psyches of the Frozen Era Access": Ys8ItemData("Psyches Access", code = None, classification = ItemClassification.progression, type = "SetFlag", pool_quantity = 1)
}

#Make item categories
item_name_groups: Dict[str, Set[str]] = {}
for item in item_table.keys():
    category = item_table[item].category
    if category not in item_name_groups.keys():
        item_name_groups[category] = set()
    item_name_groups[category].add(item)

def extend_item_tables_with_landmarks():
    """Merge landmark items into the main item table."""
    item_table.update(landmark_item_table)