from typing import Dict, NamedTuple, Optional, Set
from .Options import Ys8Options
from BaseClasses import Item, ItemClassification


class Ys8Item(Item):
    game: str = "Ys 8"


class Ys8ItemData(NamedTuple):
    category: str
    code: int
    type: str
    classification: ItemClassification = ItemClassification.filler
    weight: int = 1
    is_party_member: bool = False
    quantity: int = 1
    pool_quantity: int = 1
    default_loc: Optional[str] = None

def get_items_by_category(category: str) -> Dict[str, Ys8ItemData]:
    return {name: data for name, data in item_table.items() if data.category == category}

def get_item_pool_quantity(item_name: str, data: Ys8ItemData, options: Ys8Options) -> int:
    if item_name == "Flame Stone":
        return data.pool_quantity + options.extra_flame_stones
    return data.pool_quantity

item_table: Dict[str, Ys8ItemData] = {
    "Bone Necklace": Ys8ItemData("Accessory", 15100, "Item", ItemClassification.useful),
    "Bone Necklace II": Ys8ItemData("Accessory", 15200, "Item", ItemClassification.useful),
    "Bone Necklace III": Ys8ItemData("Accessory", 15300, "Item", ItemClassification.useful),
    "Blade Ring": Ys8ItemData("Accessory", 15500, "Item", ItemClassification.progression),
    "Blade Ring II": Ys8ItemData("Accessory", 15600, "Item", ItemClassification.progression),
    "Blade Ring III": Ys8ItemData("Accessory", 15700, "Item", ItemClassification.progression),
    "Shield Earring": Ys8ItemData("Accessory", 15900, "Item", ItemClassification.useful),
    "Shield earring II": Ys8ItemData("Accessory", 16000, "Item", ItemClassification.useful),
    "Shield Earrings III": Ys8ItemData("Accessory", 16100, "Item", ItemClassification.useful),
    "Snake Amulet": Ys8ItemData("Accessory", 16300, "Item", ItemClassification.useful),
    "Lightning Amulet": Ys8ItemData("Accessory", 16500, "Item", ItemClassification.useful),
    "Crow Amulet": Ys8ItemData("Accessory", 16700, "Item", ItemClassification.useful),
    "Fenrir Talisman": Ys8ItemData("Accessory", 16900, "Item", ItemClassification.progression),
    "Pyrios Talisman": Ys8ItemData("Accessory", 17100, "Item", ItemClassification.progression),
    "Pyrios Stone": Ys8ItemData("Accessory", 17200, "Item", ItemClassification.progression),
    "Nature Talisman": Ys8ItemData("Accessory", 17500, "Item", ItemClassification.useful, pool_quantity = 2),
    "Warrior's Mark": Ys8ItemData("Accessory", 17600, "Item", ItemClassification.useful),
    "Warrior's Seal II": Ys8ItemData("Accessory", 17700, "Item", ItemClassification.useful),
    "Warrior's Mark III": Ys8ItemData("Accessory", 17800, "Item", ItemClassification.useful),
    "Warrior's Mark IV": Ys8ItemData("Accessory", 17900, "Item", ItemClassification.useful),
    "Red Cape": Ys8ItemData("Accessory", 18000, "Item", ItemClassification.useful),
    "Blue Cape": Ys8ItemData("Accessory", 18200, "Item", ItemClassification.useful),
    "Blue Moon Talisman": Ys8ItemData("Accessory", 18300, "Item", ItemClassification.useful),
    "Sun Talisman": Ys8ItemData("Accessory", 18500, "Item", ItemClassification.useful),
    "Hunter Hat": Ys8ItemData("Accessory", 18600, "Item", ItemClassification.useful),
    "Blood Fang": Ys8ItemData("Accessory", 19000, "Item", ItemClassification.useful),
    "Athlete's Ring": Ys8ItemData("Accessory", 19200, "Item", ItemClassification.useful),
    "Athlete Belt": Ys8ItemData("Accessory", 19300, "Item", ItemClassification.useful),
    "Hero's Belt": Ys8ItemData("Accessory", 19500, "Item", ItemClassification.useful),
    "Legend's Belt": Ys8ItemData("Accessory", 19600, "Item", ItemClassification.useful),
    "Wanderer Cloak": Ys8ItemData("Accessory", 19700, "Item", ItemClassification.useful),
    "Tiger Claw": Ys8ItemData("Accessory", 19900, "Item", ItemClassification.useful, pool_quantity = 2),
    "Eagle Feather": Ys8ItemData("Accessory", 20000, "Item", ItemClassification.useful),
    "Hawk Wing": Ys8ItemData("Accessory", 20100, "Item", ItemClassification.useful),
    "Feather Boots": Ys8ItemData("Accessory", 20200, "Item", ItemClassification.useful),
    "Jade Pendant": Ys8ItemData("Accessory", 20600, "Item", ItemClassification.progression),
    "Ocean Hogeki": Ys8ItemData("Accessory", 20900, "Item", ItemClassification.progression),
    "Earth Orb": Ys8ItemData("Accessory", 21000, "Item", ItemClassification.useful),
    "Sky Crown": Ys8ItemData("Accessory", 21100, "Item", ItemClassification.useful),
    "Saint's Ring": Ys8ItemData("Accessory", 21200, "Item", ItemClassification.useful),
    "Spirit Necklace": Ys8ItemData("Accessory", 21300, "Item", ItemClassification.useful, pool_quantity = 3),
    "Prominent Cloak": Ys8ItemData("Accessory", 21500, "Item", ItemClassification.useful),
    "Slash Medal": Ys8ItemData("Accessory", 21800, "Item", ItemClassification.useful),
    "Leather Armor x2": Ys8ItemData("Accessory", 24300, "Item", ItemClassification.useful, quantity = 2),
    "Needle Wristband": Ys8ItemData("Accessory", 25200, "Item", ItemClassification.useful),
    "Iron Shield": Ys8ItemData("Accessory", 25300, "Item", ItemClassification.useful),
    "Stone Glove": Ys8ItemData("Accessory", 25400, "Item", ItemClassification.useful),
    "Gauntlet": Ys8ItemData("Accessory", 25500, "Item", ItemClassification.useful),
    "Red Glove": Ys8ItemData("Accessory", 25700, "Item", ItemClassification.useful),
    "Dark Glove": Ys8ItemData("Accessory", 25800, "Item", ItemClassification.useful),
    "Bandit Gloves": Ys8ItemData("Accessory", 25900, "Item", ItemClassification.useful),
    "Blue Glove": Ys8ItemData("Accessory", 26000, "Item", ItemClassification.useful),
    "Soft Leather Gloves": Ys8ItemData("Accessory", 26600, "Item", ItemClassification.useful),
    "Prickly Band": Ys8ItemData("Accessory", 26700, "Item", ItemClassification.useful),
    "Tektite Shield": Ys8ItemData("Accessory", 26800, "Item", ItemClassification.useful),
    "Bolt Bracelet": Ys8ItemData("Accessory", 26900, "Item", ItemClassification.useful),
    "Heavy Gauntlet": Ys8ItemData("Accessory", 27000, "Item", ItemClassification.useful),
    "Warrior Wrist": Ys8ItemData("Accessory", 27100, "Item", ItemClassification.progression),
    "Crimson Bracelet": Ys8ItemData("Accessory", 27200, "Item", ItemClassification.useful),
    "Black Bracelet": Ys8ItemData("Accessory", 27300, "Item", ItemClassification.useful),
    "Blue Bracelet": Ys8ItemData("Accessory", 27500, "Item", ItemClassification.useful),
    "Barbaric Bracelet": Ys8ItemData("Accessory", 27600, "Item", ItemClassification.useful),
    "Abyssal Gauntlet": Ys8ItemData("Accessory", 28800, "Item", ItemClassification.useful),
    "Bandit Gauntlets": Ys8ItemData("Accessory", 28900, "Item", ItemClassification.useful),
    "Blizzard Gauntlets": Ys8ItemData("Accessory", 29000, "Item", ItemClassification.useful),
    "Eternal Gauntlets": Ys8ItemData("Accessory", 29300, "Item", ItemClassification.useful, pool_quantity = 3),
    "Light Arm Guard": Ys8ItemData("Accessory", 29500, "Item", ItemClassification.useful),
    "Thunder Gauntlets": Ys8ItemData("Accessory", 29700, "Item", ItemClassification.useful),
    "Ancient Bone": Ys8ItemData("Consumable", 30300, "Item"),
    "Beast Hide x2": Ys8ItemData("Consumable", 30700, "Item", quantity = 2),
    "Ancient Hide": Ys8ItemData("Consumable", 30800, "Item"),
    "Sterile Mucus x5": Ys8ItemData("Consumable", 31100, "Item", quantity = 5),
    "Sparkling Mucus x2": Ys8ItemData("Consumable", 31200, "Item", quantity = 2),
    "Sturdy Lumber x3": Ys8ItemData("Consumable", 31600, "Item", quantity = 3),
    "Beautiful Flower x5": Ys8ItemData("Consumable", 32100, "Item", quantity = 5),
    "Iron Ore x3": Ys8ItemData("Consumable", 32600, "Item", quantity = 3),
    "Iron Ore x5": Ys8ItemData("Consumable", 32601, "Item", quantity = 5),
    "Tektite Ore x2": Ys8ItemData("Consumable", 32700, "Item", quantity = 2),
    "Tektite Ore x3": Ys8ItemData("Consumable", 32701, "Item", quantity = 3),
    "Tektite Ore x5": Ys8ItemData("Consumable", 32702, "Item", quantity = 5),
    "Essence Stone": Ys8ItemData("Consumable", 32800, "Item", pool_quantity = 10),
    "Essence Stone x2": Ys8ItemData("Consumable", 32801, "Item", quantity = 2),
    "Essence Stone x3": Ys8ItemData("Consumable", 32802, "Item", quantity = 3),
    "Beast Claw x3": Ys8ItemData("Consumable", 40000, "Item", quantity = 3),
    "Remex x5": Ys8ItemData("Consumable", 40100, "Item", quantity = 5),
    "Gwaranga Pincer x2": Ys8ItemData("Consumable", 40400, "Item", quantity = 2),
    "Bullfrodon Mucus": Ys8ItemData("Consumable", 40500, "Item"),
    "Digitalis Leaf x3": Ys8ItemData("Consumable", 41900, "Item", quantity = 3),
    "Digitalis Leaf x5": Ys8ItemData("Consumable", 41901, "Item", quantity = 5),
    "Sword Tip Fang x3": Ys8ItemData("Consumable", 42000, "Item", quantity = 3),
    "Razor Feather x3": Ys8ItemData("Consumable", 42100, "Item", quantity = 3),
    "Accursed Shell x3": Ys8ItemData("Consumable", 42200, "Item", quantity = 3),
    "Lustrous Scale x3": Ys8ItemData("Consumable", 42300, "Item", quantity = 3),
    "Salamandine Hide x3": Ys8ItemData("Consumable", 42400, "Item", quantity = 3),
    "Large Pearl": Ys8ItemData("Consumable", 43600, "Item", ItemClassification.progression, pool_quantity = 5),
    "Large Pearl x3": Ys8ItemData("Consumable", 43601, "Item", quantity = 3),
    "Glow Rock": Ys8ItemData("Consumable", 43700, "Item", pool_quantity = 2),
    "Glow Rock x3": Ys8ItemData("Consumable", 43701, "Item", quantity = 3),
    "Stalactite x3": Ys8ItemData("Consumable", 43800, "Item", quantity = 3),
    "Thunder Claw x3": Ys8ItemData("Consumable", 44000, "Item", quantity = 3),
    "Blue Sky Feather x3": Ys8ItemData("Consumable", 44100, "Item", quantity = 3),
    "Diamond Shell x3": Ys8ItemData("Consumable", 44200, "Item", quantity = 3),
    "Rigid Fiber": Ys8ItemData("Consumable", 44300, "Item", pool_quantity = 4),
    "Rigid Fiber x2": Ys8ItemData("Consumable", 44301, "Item", quantity = 2),
    "Rigid Fiber x3": Ys8ItemData("Consumable", 44302, "Item", quantity = 3),
    "Vivine Bitters x2": Ys8ItemData("Consumable", 44400, "Item", quantity = 2),
    "Saurian Scale": Ys8ItemData("Consumable", 44600, "Item", pool_quantity = 3),
    "Saurian Scale x2": Ys8ItemData("Consumable", 44601, "Item", quantity = 2),
    "Moonlight Grass x3": Ys8ItemData("Consumable", 45700, "Item", quantity = 3),
    "Rim Flower": Ys8ItemData("Consumable", 45900, "Item", pool_quantity = 2),
    "Rim Flower x2": Ys8ItemData("Consumable", 45901, "Item", quantity = 2),
    "Sunlight Fang x2": Ys8ItemData("Consumable", 46000, "Item", quantity = 2),
    "Lunar Wing x2": Ys8ItemData("Consumable", 46100, "Item", quantity = 2),
    "Starry Shell x2": Ys8ItemData("Consumable", 46200, "Item", quantity = 2),
    "Acidic Liquid": Ys8ItemData("Consumable", 46300, "Item"),
    "Dandale Horn": Ys8ItemData("Consumable", 46500, "Item"),
    "Prismatic Jewel": Ys8ItemData("Consumable", 47600, "Item", ItemClassification.progression, pool_quantity = 17),
    "Prismatic Jewel x2": Ys8ItemData("Consumable", 47601, "Item", ItemClassification.progression, quantity = 2),
    "Prismatic Jewel x3": Ys8ItemData("Consumable", 47602, "Item", ItemClassification.progression, quantity = 3),
    "Prismatic Jewel x5": Ys8ItemData("Consumable", 47603, "Item", ItemClassification.progression, quantity = 5),
    "Dragon Crest Stone": Ys8ItemData("Consumable", 47800, "Item", pool_quantity = 3),
    "Dragon Crest Stone x2": Ys8ItemData("Consumable", 47801, "Item", quantity = 2),
    "Great Tree Lumber": Ys8ItemData("Consumable", 47900, "Item", pool_quantity = 3),
    "Great Tree Lumber x2": Ys8ItemData("Consumable", 47901, "Item", quantity = 2),
    "Saurian Carapace": Ys8ItemData("Consumable", 48600, "Item"),
    "Rivera's Immortal Flower x3": Ys8ItemData("Consumable", 49700, "Item", quantity = 3),
    "Pure Orichalcum": Ys8ItemData("Consumable", 49800, "Item", ItemClassification.useful, pool_quantity = 3),
    "Aura Grass": Ys8ItemData("Consumable", 49900, "Item", pool_quantity = 8),
    "Aura Grass x2": Ys8ItemData("Consumable", 49901, "Item", quantity = 2),
    "Aura Grass x3": Ys8ItemData("Consumable", 49902, "Item", quantity = 3),
    "Heal Potion": Ys8ItemData("Consumable", 50000, "Item", pool_quantity = 4),
    "Full Potion": Ys8ItemData("Consumable", 50100, "Item", pool_quantity = 2),
    "Revive Medicine": Ys8ItemData("Consumable", 50300, "Item", pool_quantity = 4),
    "Great Tree Drop": Ys8ItemData("Consumable", 50400, "Item", ItemClassification.useful, pool_quantity = 2),
    "Dynastic Water": Ys8ItemData("Consumable", 50700, "Item", ItemClassification.useful),
    "Medicine": Ys8ItemData("Consumable", 50800, "Item", pool_quantity = 4),
    "Full Medicine": Ys8ItemData("Consumable", 50900, "Item", pool_quantity = 6),
    "Antidote x3": Ys8ItemData("Consumable", 51000, "Item", quantity = 3),
    "Antidote x5": Ys8ItemData("Consumable", 51001, "Item", quantity = 5),
    "Eye Drops x3": Ys8ItemData("Consumable", 51100, "Item", quantity = 3),
    "Eye Drops x5": Ys8ItemData("Consumable", 51101, "Item", quantity = 5),
    "Antiparalytic": Ys8ItemData("Consumable", 51200, "Item", pool_quantity = 7),
    "Antiparalytic x3": Ys8ItemData("Consumable", 51201, "Item", quantity = 3),
    "Antiparalytic x5": Ys8ItemData("Consumable", 51202, "Item", quantity = 5),
    "Defrost Medicine x3": Ys8ItemData("Consumable", 51300, "Item", quantity = 3),
    "Defrost Medicine x5": Ys8ItemData("Consumable", 51301, "Item", quantity = 5),
    "Burn Medicine x3": Ys8ItemData("Consumable", 51400, "Item", quantity = 3),
    "Burn Medicine x5": Ys8ItemData("Consumable", 51401, "Item", quantity = 5),
    "Hemostatic": Ys8ItemData("Consumable", 51500, "Item", pool_quantity = 6),
    "Hemostatic x3": Ys8ItemData("Consumable", 51501, "Item", quantity = 3),
    "Hemostatic x5": Ys8ItemData("Consumable", 51502, "Item", quantity = 5),
    "Remedy x3": Ys8ItemData("Consumable", 51600, "Item", quantity = 3),
    "Antiparalytic x3": Ys8ItemData("Consumable", 51700, "Item"),
    "Burn Medicine x3": Ys8ItemData("Consumable", 51800, "Item"),
    "Remedy x3": Ys8ItemData("Consumable", 51900, "Item"),
    "Sweet Remedy": Ys8ItemData("Consumable", 52000, "Item", pool_quantity = 5),
    "Sweet Remedy x3": Ys8ItemData("Consumable", 52001, "Item", quantity = 3),
    "Sweet Remedy x5": Ys8ItemData("Consumable", 52002, "Item", quantity = 5),
    "Bitter Remedy": Ys8ItemData("Consumable", 52100, "Item", pool_quantity = 4),
    "Bitter Remedy x2": Ys8ItemData("Consumable", 52101, "Item", quantity = 2),
    "Bitter Remedy x3": Ys8ItemData("Consumable", 52102, "Item", quantity = 3),
    "Hermit's Elixir": Ys8ItemData("Consumable", 52200, "Item", pool_quantity = 10),
    "Hermit's Elixir x3": Ys8ItemData("Consumable", 52201, "Item", quantity = 3),
    "Strength Elixir": Ys8ItemData("Consumable", 52300, "Item", pool_quantity = 7),
    "Strength Elixir x3": Ys8ItemData("Consumable", 52301, "Item", quantity = 3),
    "Defense Elixir": Ys8ItemData("Consumable", 52400, "Item", pool_quantity = 10),
    "Defense Elixir x3": Ys8ItemData("Consumable", 52401, "Item", quantity = 3),
    "Life Elixir": Ys8ItemData("Consumable", 52500, "Item", pool_quantity = 7),
    "Life Elixir x3": Ys8ItemData("Consumable", 52501, "Item", quantity = 3),
    "Spirit Elixir": Ys8ItemData("Consumable", 52600, "Item", ItemClassification.useful, pool_quantity = 6),
    "Tempest Elixir": Ys8ItemData("Consumable", 52700, "Item", pool_quantity = 3),
    "Beastiary Potion": Ys8ItemData("Consumable", 52800, "Item"),
    "Coconut x2": Ys8ItemData("Consumable", 53100, "Item", quantity = 2),
    "Mango x2": Ys8ItemData("Consumable", 53200, "Item", quantity = 2),
    "Mango x5": Ys8ItemData("Consumable", 53201, "Item", quantity = 5),
    "Dragon Tree Treasure": Ys8ItemData("Consumable", 53300, "Item", pool_quantity = 12),
    "Ripe Crudberry": Ys8ItemData("Consumable", 53500, "Item", pool_quantity = 4),
    "Ripe Crudberry x2": Ys8ItemData("Consumable", 53501, "Item", quantity = 2),
    "Ripe Crudberry x3": Ys8ItemData("Consumable", 53502, "Item", quantity = 3),
    "Ripe Coconut": Ys8ItemData("Consumable", 53600, "Item", pool_quantity = 7),
    "Ripe Coconut x2": Ys8ItemData("Consumable", 53601, "Item", quantity = 2),
    "Ripe Coconut x3": Ys8ItemData("Consumable", 53602, "Item", quantity = 3),
    "Ripe Mango": Ys8ItemData("Consumable", 53700, "Item", pool_quantity = 13),
    "Ripe Mango x2": Ys8ItemData("Consumable", 53701, "Item", quantity = 2),
    "Ripe Mango x3": Ys8ItemData("Consumable", 53702, "Item", quantity = 3),
    "Dragon Tree Treasure": Ys8ItemData("Consumable", 53800, "Item", pool_quantity = 12),
    "Dragon Tree Treasure x3": Ys8ItemData("Consumable", 53801, "Item", quantity = 3),
    "Hope Stone": Ys8ItemData("Accessory", 54200, "Item", ItemClassification.progression, pool_quantity = 2),
    "Luminous Ring": Ys8ItemData("Accessory", 54300, "Item", ItemClassification.useful),
    "Devil Fang": Ys8ItemData("Accessory", 54400, "Item", ItemClassification.useful),
    "Wings of Heavenly Light": Ys8ItemData("Accessory", 54500, "Item", ItemClassification.useful),
    "Wheel of Eternity": Ys8ItemData("Accessory", 54600, "Item", ItemClassification.useful, pool_quantity = 2),
    "Crown of Creation": Ys8ItemData("Accessory", 54700, "Item", ItemClassification.useful, pool_quantity = 2),
    "Stone of Anitquity": Ys8ItemData("Accessory", 54800, "Item", ItemClassification.progression, pool_quantity = 2),
    "Garment of Many Tongues": Ys8ItemData("Accessory", 54900, "Item", ItemClassification.useful, pool_quantity = 3),
    "Recipe Book/Mushroom Omelet": Ys8ItemData("Recipe Book", 56900, "Item", ItemClassification.progression),
    "Recipe Book/Hearty Ratatouille": Ys8ItemData("Recipe Book", 57000, "Item", ItemClassification.progression),
    "Recipe Book/Colorful Meuniere": Ys8ItemData("Recipe Book", 57100, "Item", ItemClassification.progression),
    "Recipe Book/Seafood Quiche": Ys8ItemData("Recipe Book", 57200, "Item", ItemClassification.progression),
    "Recipe Book/Cabbage Rolls": Ys8ItemData("Recipe Book", 57300, "Item", ItemClassification.progression),
    "Recipe Book/Meat-Wrapped Mushrooms": Ys8ItemData("Recipe Book", 57400, "Item", ItemClassification.progression),
    "Recipe Book/Fish Fry": Ys8ItemData("Recipe Book", 57500, "Item", ItemClassification.progression),
    "Recipe Book/Pirate's Platter": Ys8ItemData("Recipe Book", 57600, "Item", ItemClassification.progression),
    "Recipe Book/Luxury Coleslaw": Ys8ItemData("Recipe Book", 57700, "Item", ItemClassification.progression),
    "Recipe Book/Heartfelt Bolognese": Ys8ItemData("Recipe Book", 57800, "Item", ItemClassification.progression),
    "Recipe Book/Great Pumpkin Pie": Ys8ItemData("Recipe Book", 57900, "Item", ItemClassification.progression),
    "Spiral Manual": Ys8ItemData("Consumable", 58300, "Item", ItemClassification.useful),
    "Fairy Manual": Ys8ItemData("Consumable", 58400, "Item", ItemClassification.useful),
    "Wild Manual": Ys8ItemData("Consumable", 58500, "Item", ItemClassification.useful),
    "Tremor Manual": Ys8ItemData("Consumable", 58600, "Item", ItemClassification.useful),
    "Thorn Manual": Ys8ItemData("Consumable", 58700, "Item", ItemClassification.useful),
    "Freeze Manual": Ys8ItemData("Consumable", 58800, "Item", ItemClassification.useful),
    "Forest Guide": Ys8ItemData("Consumable", 59000, "Item", ItemClassification.useful),
    "Ocean Guide": Ys8ItemData("Consumable", 59100, "Item", ItemClassification.useful),
    "Mountain Guide": Ys8ItemData("Consumable", 59200, "Item", ItemClassification.useful),
    "Wind Guide": Ys8ItemData("Consumable", 59300, "Item", ItemClassification.useful),
    "Seiren Wheat x5": Ys8ItemData("Consumable", 60200, "Item", quantity = 5),
    "Pheasant Egg x5": Ys8ItemData("Consumable", 60300, "Item", quantity = 5),
    "Sweet Pepper x5": Ys8ItemData("Consumable", 60900, "Item", quantity = 5),
    "Eggplant Seed": Ys8ItemData("Consumable", 61000, "Item"),
    "Shiny Corn x5": Ys8ItemData("Consumable", 61200, "Item", quantity = 5),
    "King Pumpkin x2": Ys8ItemData("Consumable", 61400, "Item", quantity = 2),
    "Strength Elixir": Ys8ItemData("Consumable", 61700, "Item", pool_quantity = 7),
    "Defense Elixir": Ys8ItemData("Consumable", 61800, "Item", pool_quantity = 10),
    "Life Elixir": Ys8ItemData("Consumable", 61900, "Item", pool_quantity = 7),
    "Empty Bottle": Ys8ItemData("Consumable", 62000, "Item", pool_quantity = 2),
    "Bait x5": Ys8ItemData("Consumable", 62800, "Item", quantity = 5),
    "Bait x10": Ys8ItemData("Consumable", 62801, "Item", quantity = 10),
    "Fishing Rod": Ys8ItemData("Consumable", 62900, "Item", ItemClassification.progression),
    "Energy Fragment x50": Ys8ItemData("Consumable", 67000, "Item", quantity = 50),
    "Energy Fragment x100": Ys8ItemData("Consumable", 67001, "Item", quantity = 100),
    "Energy Fragment x150": Ys8ItemData("Consumable", 67002, "Item", quantity = 150),
    "Eyedrop Formula": Ys8ItemData("Consumable", 68700, "Item"),
    "Blood Formula": Ys8ItemData("Consumable", 68900, "Item"),
    "Delight Formula": Ys8ItemData("Consumable", 69000, "Item"),
    "Bitter Formula": Ys8ItemData("Consumable", 69100, "Item", ItemClassification.useful),
    "Bless Formula": Ys8ItemData("Consumable", 69200, "Item"),
    "Life Formula": Ys8ItemData("Consumable", 69300, "Item"),
    "Hide Formula": Ys8ItemData("Consumable", 69400, "Item"),
    "Strength Formula": Ys8ItemData("Consumable", 69500, "Item", ItemClassification.useful),
    "Defense Formula": Ys8ItemData("Consumable", 69600, "Item"),
    "Maiden Journal": Ys8ItemData("Consumable", 69800, "Item", ItemClassification.progression),
    "Frozen Flower": Ys8ItemData("Consumable", 69900, "Item", ItemClassification.progression),
    "Blue Seal of Whirling Water": Ys8ItemData("Consumable", 70000, "Item", ItemClassification.progression),
    "Green Seal of Roaring Stone": Ys8ItemData("Consumable", 70100, "Item", ItemClassification.progression),
    "Golden Seal of Piercing Light": Ys8ItemData("Consumable", 70200, "Item", ItemClassification.progression),
    "Essence Key Stone": Ys8ItemData("Consumable", 70300, "Item", ItemClassification.progression, pool_quantity = 9),
    "Battle Armlet": Ys8ItemData("Consumable", 72000, "Item", ItemClassification.progression, pool_quantity = 2),
    "Dragon Bone Necklace": Ys8ItemData("Consumable", 72200, "Item"),
    "Mushin's hairpin": Ys8ItemData("Consumable", 72500, "Item"),
    "Fairy Cape": Ys8ItemData("Consumable", 72600, "Item"),
    "Shrine Maiden Amulet": Ys8ItemData("Consumable", 72700, "Item", ItemClassification.progression),
    "Stone Crown": Ys8ItemData("Consumable", 72900, "Item"),
    "Blue Wind Staff": Ys8ItemData("Adventure Gear", 73000, "Item", ItemClassification.useful),
    "Nature Talisman": Ys8ItemData("Adventure Gear", 73100, "Item", ItemClassification.useful, pool_quantity = 2),
    "Gale Feather": Ys8ItemData("Adventure Gear", 73500, "Item", ItemClassification.useful),
    "Windy Vestment": Ys8ItemData("Adventure Gear", 73600, "Item", ItemClassification.useful),
    "Grip Gloves": Ys8ItemData("Adventure Gear", 73700, "Item", ItemClassification.progression),
    "Hermit's Scale": Ys8ItemData("Adventure Gear", 73800, "Item", ItemClassification.progression),
    "Glow Stone": Ys8ItemData("Adventure Gear", 73900, "Item", ItemClassification.progression),
    "Float Shoes": Ys8ItemData("Adventure Gear", 74000, "Item", ItemClassification.progression),
    "Archeopteryx Wings": Ys8ItemData("Adventure Gear", 74100, "Item", ItemClassification.progression),
    "Purifying Bell": Ys8ItemData("Adventure Gear", 74200, "Item", ItemClassification.progression),
    "Ares Seal": Ys8ItemData("Adventure Gear", 74300, "Item", ItemClassification.useful),
    "Aeolus Urn": Ys8ItemData("Adventure Gear", 74400, "Item", ItemClassification.useful),
    "Eagle Eye Orb": Ys8ItemData("Adventure Gear", 74500, "Item", ItemClassification.progression),
    "Pirate's Notes": Ys8ItemData("Consumable", 75000, "Item"),
    "Pirate Memo A": Ys8ItemData("Consumable", 75100, "Item"),
    "Pirate Memo B": Ys8ItemData("Consumable", 75200, "Item"),
    "Pirate Memo C": Ys8ItemData("Consumable", 75300, "Item"),
    "Pirate Memo D": Ys8ItemData("Consumable", 75400, "Item"),
    "Pirate's Memo E": Ys8ItemData("Consumable", 75500, "Item"),
    "T's Memo": Ys8ItemData("Consumable", 76000, "Item", ItemClassification.progression),
    "T's Memo A": Ys8ItemData("Consumable", 76100, "Item", ItemClassification.progression),
    "T's Memo B": Ys8ItemData("Consumable", 76200, "Item", ItemClassification.progression),
    "T's Memo C": Ys8ItemData("Consumable", 76300, "Item", ItemClassification.progression),
    "Logbook 1": Ys8ItemData("Consumable", 77000, "Item", ItemClassification.progression),
    "Logbook 2": Ys8ItemData("Consumable", 77100, "Item"),
    "Logbook 3": Ys8ItemData("Consumable", 77200, "Item"),
    "Logbook 4": Ys8ItemData("Consumable", 77300, "Item"),
    "Logbook 5": Ys8ItemData("Consumable", 77400, "Item"),
    "Monolith Fragment": Ys8ItemData("Consumable", 77700, "Item"),
    "Flame Stone": Ys8ItemData("Consumable", 77800, "Item", ItemClassification.progression, pool_quantity = 7),
    "Ship Blueprint": Ys8ItemData("Consumable", 77900, "Item", ItemClassification.progression),
    "Sweet Pepper Seeds": Ys8ItemData("Consumable", 78000, "Item"),
    "Shiny Corn Seeds": Ys8ItemData("Consumable", 78300, "Item"),
    "Queen Tomato Seeds": Ys8ItemData("Consumable", 78400, "Item"),
    "King Pumpkin seeds": Ys8ItemData("Consumable", 78500, "Item"),
    "Seiren Nautical Chart": Ys8ItemData("Consumable", 79500, "Item"),
    "Treasure Chest Key": Ys8ItemData("Consumable", 79600, "Item", ItemClassification.progression),
    "Romun Badge": Ys8ItemData("Consumable", 80100, "Item"),
    "Rainbow Pigment": Ys8ItemData("Consumable", 80300, "Item"),
    "Ship Nameplate": Ys8ItemData("Consumable", 80400, "Item"),
    "Violet Bookmark": Ys8ItemData("Consumable", 80800, "Item"),
    "Engraved Pen": Ys8ItemData("Consumable", 81300, "Item"),
    "Gold Essence Crystal": Ys8ItemData("Consumable", 81500, "Item"),
    "Ancient Coin": Ys8ItemData("Consumable", 81600, "Item"),
    "Iron Knuckle": Ys8ItemData("Consumable", 81800, "Item"),
    "Snowflake Soap": Ys8ItemData("Consumable", 81900, "Item"),
    "Big Seed": Ys8ItemData("Consumable", 82700, "Item"),
    "Old Stethoscope": Ys8ItemData("Consumable", 82900, "Item"),
    "Laxia": Ys8ItemData("Crew", 90100, "SetFlag", ItemClassification.progression, is_party_member = True),
    "Captain Barbaros": Ys8ItemData("Crew", 90200, "SetFlag", ItemClassification.progression),
    "Little Paro": Ys8ItemData("Crew", 90300, "SetFlag", ItemClassification.progression),
    "Sahad": Ys8ItemData("Crew", 90400, "SetFlag", ItemClassification.progression, is_party_member = True),
    "Dogi": Ys8ItemData("Crew", 90500, "SetFlag", ItemClassification.progression),
    "Alison": Ys8ItemData("Crew", 90600, "SetFlag", ItemClassification.progression),
    "Sir Carlan": Ys8ItemData("Crew", 90700, "SetFlag", ItemClassification.progression),
    "Kiergaard": Ys8ItemData("Crew", 90800, "SetFlag", ItemClassification.progression),
    "Sister Nia": Ys8ItemData("Crew", 90900, "SetFlag", ItemClassification.progression),
    "Hummel": Ys8ItemData("Crew", 91000, "SetFlag", ItemClassification.progression, is_party_member = True),
    "Dina": Ys8ItemData("Crew", 91100, "SetFlag", ItemClassification.progression),
    "Reja": Ys8ItemData("Crew", 91200, "SetFlag", ItemClassification.progression),
    "Euron": Ys8ItemData("Crew", 91300, "SetFlag", ItemClassification.progression),
    "Licht": Ys8ItemData("Crew", 91400, "SetFlag", ItemClassification.progression),
    "Quina": Ys8ItemData("Crew", 91500, "SetFlag", ItemClassification.progression),
    "Ricotta": Ys8ItemData("Crew", 91600, "SetFlag", ItemClassification.progression, is_party_member = True),
    "Austin": Ys8ItemData("Crew", 91700, "SetFlag", ItemClassification.progression),
    "Miralda": Ys8ItemData("Crew", 91800, "SetFlag", ItemClassification.progression),
    "Thanatos": Ys8ItemData("Crew", 91900, "SetFlag", ItemClassification.progression),
    "Silvia": Ys8ItemData("Crew", 92000, "SetFlag", ItemClassification.progression),
    "Dana": Ys8ItemData("Crew", 92100, "SetFlag", ItemClassification.progression, is_party_member = True),
    "Katthew": Ys8ItemData("Crew", 92200, "SetFlag", ItemClassification.progression),
    "Ed": Ys8ItemData("Crew", 92300, "SetFlag", ItemClassification.progression),
    "Franz": Ys8ItemData("Crew", 92400, "SetFlag", ItemClassification.progression),
    "Shoebill": Ys8ItemData("Crew", 92500, "SetFlag", ItemClassification.progression),
    "Griselda": Ys8ItemData("Crew", 92600, "SetFlag", ItemClassification.progression),
    "Master Kong": Ys8ItemData("Crew", 92700, "SetFlag", ItemClassification.progression),
    "Adol": Ys8ItemData("Crew", 92800, "SetFlag", ItemClassification.progression, is_party_member = True),
    "Sonic Slide": Ys8ItemData("Adol Skill", 92900, "SetFlag", ItemClassification.useful),
    "Arc Shot": Ys8ItemData("Adol Skill", 93000, "SetFlag", ItemClassification.useful),
    "Dagger Fling": Ys8ItemData("Laxia Skill", 93100, "SetFlag", ItemClassification.useful),
    "Wake Up!": Ys8ItemData("Laxia Skill", 93200, "SetFlag", ItemClassification.useful),
    "High Wave": Ys8ItemData("Sahad Skill", 93300, "SetFlag", ItemClassification.useful),
    "Grand Anchor": Ys8ItemData("Sahad Skill", 93400, "SetFlag", ItemClassification.useful),
    "Burst Shot": Ys8ItemData("Hummel Skill", 93500, "SetFlag", ItemClassification.useful),
    "Venomous Bullet": Ys8ItemData("Hummel Skill", 93600, "SetFlag", ItemClassification.useful),
    "Wild Spin": Ys8ItemData("Ricotta Skill", 93700, "SetFlag", ItemClassification.useful),
    "Handmade Trap": Ys8ItemData("Ricotta Skill", 93800, "SetFlag", ItemClassification.useful),
    "Twin Edge": Ys8ItemData("Dana Skill", 93900, "SetFlag", ItemClassification.useful),
    "Sonic Rise": Ys8ItemData("Dana Skill", 94000, "SetFlag", ItemClassification.useful),
    "Dragon Spirit": Ys8ItemData("Dana Skill", 94100, "SetFlag", ItemClassification.useful),
    "Force Edge": Ys8ItemData("Adol Skill", 94200, "SetFlag", ItemClassification.useful),
    "Spiel Round Dance": Ys8ItemData("Dana Skill", 94300, "SetFlag", ItemClassification.useful),
    "Water Burst": Ys8ItemData("Dana Skill", 94400, "SetFlag", ItemClassification.useful),
    "Firecracker": Ys8ItemData("Hummel Skill", 94500, "SetFlag", ItemClassification.useful),
    "Prominence Shot": Ys8ItemData("Hummel Skill", 94600, "SetFlag", ItemClassification.useful),
    "Spiral Anchor": Ys8ItemData("Sahad Skill", 94700, "SetFlag", ItemClassification.useful),
    "Raging Deluge": Ys8ItemData("Sahad Skill", 94800, "SetFlag", ItemClassification.useful),
    "Dino Throw": Ys8ItemData("Ricotta Skill", 94900, "SetFlag", ItemClassification.useful),
    "Triple Bang": Ys8ItemData("Ricotta Skill", 95000, "SetFlag", ItemClassification.useful),
    "Precious Impact": Ys8ItemData("Laxia Skill", 95100, "SetFlag", ItemClassification.useful),
    "Lethal Raid": Ys8ItemData("Laxia Skill", 95200, "SetFlag", ItemClassification.useful),
    "Mistral Edge": Ys8ItemData("Dana Skill", 95300, "SetFlag", ItemClassification.useful),
    "Thrust Storm": Ys8ItemData("Adol Skill", 95400, "SetFlag", ItemClassification.useful),
    "Green Whip": Ys8ItemData("Ricotta Skill", 95500, "SetFlag", ItemClassification.useful),
    "Magna Wave": Ys8ItemData("Sahad Skill", 95600, "SetFlag", ItemClassification.useful),
    "Hasty Valor": Ys8ItemData("Hummel Skill", 95700, "SetFlag", ItemClassification.useful),
    "Beast Attack": Ys8ItemData("Ricotta Skill", 95800, "SetFlag", ItemClassification.useful),
    "Boomerang Edge": Ys8ItemData("Dana Skill", 95900, "SetFlag", ItemClassification.useful),
    "Upper Break": Ys8ItemData("Sahad Skill", 96000, "SetFlag", ItemClassification.useful),
    "Power Strike": Ys8ItemData("Sahad Skill", 96100, "SetFlag", ItemClassification.useful),
    "Seine Toss": Ys8ItemData("Sahad Skill", 96200, "SetFlag", ItemClassification.useful),
    "Judgment": Ys8ItemData("Hummel Skill", 96300, "SetFlag", ItemClassification.useful),
    "Counter Trick": Ys8ItemData("Hummel Skill", 96400, "SetFlag", ItemClassification.useful),
    "Flame Swing": Ys8ItemData("Ricotta Skill", 96500, "SetFlag", ItemClassification.useful),
    "Mighty Orbit": Ys8ItemData("Ricotta Skill", 96600, "SetFlag", ItemClassification.useful),
    "Blade Rush": Ys8ItemData("Adol Skill", 96700, "SetFlag", ItemClassification.useful),
    "Aura Blade": Ys8ItemData("Adol Skill", 96800, "SetFlag", ItemClassification.useful),
    "Eagle Lancer": Ys8ItemData("Laxia Skill", 96900, "SetFlag", ItemClassification.useful),
    "Spark Chaser": Ys8ItemData("Laxia Skill", 97000, "SetFlag", ItemClassification.useful),
    "Bandit Tackle": Ys8ItemData("Ricotta Skill", 97100, "SetFlag", ItemClassification.useful),
    "Screw Fang": Ys8ItemData("Ricotta Skill", 97200, "SetFlag", ItemClassification.useful),
    "Stun Thrust": Ys8ItemData("Laxia Skill", 97300, "SetFlag", ItemClassification.useful),
    "Blitz Charge": Ys8ItemData("Laxia Skill", 97400, "SetFlag", ItemClassification.useful),
    "Earth Dragon": Ys8ItemData("Dana Skill", 97500, "SetFlag", ItemClassification.useful),
    "Twin Moon Blade": Ys8ItemData("Dana Skill", 97600, "SetFlag", ItemClassification.useful),
    "Triple Bomber": Ys8ItemData("Hummel Skill", 97700, "SetFlag", ItemClassification.useful),
    "Guilty Raid": Ys8ItemData("Hummel Skill", 97800, "SetFlag", ItemClassification.useful),
    "Somersault": Ys8ItemData("Hummel Skill", 97900, "SetFlag", ItemClassification.useful),
    "Elemental Shot": Ys8ItemData("Dana Skill", 98000, "SetFlag", ItemClassification.useful),
    "Aerial Spin": Ys8ItemData("Adol Skill", 98100, "SetFlag", ItemClassification.useful),
    "Sky Drive": Ys8ItemData("Adol Skill", 98200, "SetFlag", ItemClassification.useful),
    "Vortex": Ys8ItemData("Sahad Skill", 98300, "SetFlag", ItemClassification.useful),
    "Great Ram": Ys8ItemData("Sahad Skill", 98400, "SetFlag", ItemClassification.useful),
    "Rapid Thrust": Ys8ItemData("Laxia Skill", 98500, "SetFlag", ItemClassification.useful),
    "Needle Break": Ys8ItemData("Laxia Skill", 98600, "SetFlag", ItemClassification.useful),
    "Rising Slash": Ys8ItemData("Adol Skill", 98700, "SetFlag", ItemClassification.useful),
    "Sword Impact": Ys8ItemData("Adol Skill", 98800, "SetFlag", ItemClassification.useful),
    "Spiral Drive": Ys8ItemData("Ricotta Skill", 98900, "SetFlag", ItemClassification.useful),
    "Gale Blow": Ys8ItemData("Sahad Skill", 99000, "SetFlag", ItemClassification.useful),
    "Dragon Wave": Ys8ItemData("Dana Skill", 99100, "SetFlag", ItemClassification.useful),
    "Piercing Tempest": Ys8ItemData("Laxia Skill", 99200, "SetFlag", ItemClassification.useful),
    "Assault Rain": Ys8ItemData("Hummel Skill", 99300, "SetFlag", ItemClassification.useful),
    "Brave Charge": Ys8ItemData("Adol Skill", 99400, "SetFlag", ItemClassification.useful),
    "Mistilteinn": Ys8ItemData("Super Weapon", 900, "Item", ItemClassification.progression),
    "Spirit Ring Celesdia": Ys8ItemData("Super Weapon", 1300, "Item", ItemClassification.progression),
    "Broken Mistilteinn": Ys8ItemData("Progressive Super Weapon", 901, "Item", ItemClassification.progression),
    "Broken Spirit Ring": Ys8ItemData("Progressive Super Weapon", 902, "Item", ItemClassification.progression),
    "Birdsong Rock": Ys8ItemData("Landmark", 99500, "SetFlag", ItemClassification.progression, default_loc = "Nameless Coast Shoreline North of Boulder Landmark"),
    "Cobalt Crag": Ys8ItemData("Landmark", 99600, "SetFlag", ItemClassification.progression, default_loc = "White Sand Cape Cobalt Crag Landmark"),
    "Rainbow Falls": Ys8ItemData("Landmark", 99700, "SetFlag", ItemClassification.progression, default_loc = "Towering Coral Forest Rainbow Falls Landmark"),
    "Metavolicalis": Ys8ItemData("Landmark", 99800, "SetFlag", ItemClassification.progression, default_loc = "Roaring Seashore Metavolicalis Landmark"),
    "Parasequoia": Ys8ItemData("Landmark", 99900, "SetFlag", ItemClassification.progression, default_loc = "Roaring Seashore Parasequoia Landmark"),
    "Chimney Rock": Ys8ItemData("Landmark", 100000, "SetFlag", ItemClassification.progression, default_loc = "Great River Valley Chimney Rock Landmark"),
    "Indigo Mineral Vein": Ys8ItemData("Landmark", 100100, "SetFlag", ItemClassification.progression, default_loc = "Eroded Valley Dark Passage Landmark"),
    "Beached Remains": Ys8ItemData("Landmark", 100200, "SetFlag", ItemClassification.progression, default_loc = "Sunrise Beach Sunrise Beach Landmark"),
    "Field of Medicinal Herbs": Ys8ItemData("Landmark", 100300, "SetFlag", ItemClassification.progression, default_loc = "Schlamm Jungle Muddy Passage Landmark"),
    "Airs Cairn": Ys8ItemData("Landmark", 100400, "SetFlag", ItemClassification.progression, default_loc = "Western Foot of Gendarme Near Cavern of the Ancient King Landmark"),
    "Zephyr Hill": Ys8ItemData("Landmark", 100500, "SetFlag", ItemClassification.progression, default_loc = "Weathervane Hills Zephyr Hill Landmark"),
    "Lapis Mineral Vein": Ys8ItemData("Landmark", 100600, "SetFlag", ItemClassification.progression, default_loc = "Underground Water Vein Lapis Mineral Vein Landmark"),
    "Beehive": Ys8ItemData("Landmark", 100700, "SetFlag", ItemClassification.progression, default_loc = "Longhorn Coast Reja Shore Landmark"),
    "Ship Graveyard": Ys8ItemData("Landmark", 100800, "SetFlag", ItemClassification.progression, default_loc = "Nostalgia Cape Nostalgia Cape Landmark"),
    "Hidden Pirate Storehouse": Ys8ItemData("Landmark", 100900, "SetFlag", ItemClassification.progression, default_loc = "East Coast Cave East Coast Cave Landmark"),
    "Magna Carpa": Ys8ItemData("Landmark", 101000, "SetFlag", ItemClassification.progression, default_loc = "Solitude Island Magna Carpa Landmark"),
    "Prismatic Mineral Vein": Ys8ItemData("Landmark", 101100, "SetFlag", ItemClassification.progression, default_loc = "Mountain Pinnacle Trail Second Cave Landmark"),
    "Unicalamites": Ys8ItemData("Landmark", 101200, "SetFlag", ItemClassification.progression, default_loc = "Titis Primeval Forest Near Primordial Den Landmark"),
    "Breath Fountain": Ys8ItemData("Landmark", 101300, "SetFlag", ItemClassification.progression, default_loc = "Pangaia Plains Northern Plains Landmark"),
    "Ancient Tree": Ys8ItemData("Landmark", 101400, "SetFlag", ItemClassification.progression, default_loc = "Pangaia Plains Ancient Tree Landmark"),
    "Sky Garden": Ys8ItemData("Landmark", 101500, "SetFlag", ItemClassification.progression, default_loc = "Lodinia Marshlands Exit to Valley of Kings Landmark"),
    "Soundless Hall": Ys8ItemData("Landmark", 101600, "SetFlag", ItemClassification.progression, default_loc = "The Submerged Cemetery The Submerged Cemetery Landmark"),
    "Graves of Ancient Heroes": Ys8ItemData("Landmark", 101700, "SetFlag", ItemClassification.progression, default_loc = "Eternal Hill Eternal Hill Landmark"),
    "Milky White Vein": Ys8ItemData("Landmark", 101800, "SetFlag", ItemClassification.progression, default_loc = "Waterfall Grotto Waterfall Grotto Landmark"),
}

event_item_table: Dict[str, Ys8ItemData] = {
    "Avalodragil 2 Defeated": Ys8ItemData("Mont Gendarme Mid-Boss Arena Avalodragil 2", None, "Boss", ItemClassification.progression),
    "Avalodragil Defeated": Ys8ItemData("Nameless Coast First Avalodragil Arena Avalodragil", None, "Boss", ItemClassification.progression),
    "Basileus Defeated": Ys8ItemData("Valley of Kings Boss Arena Basileus", None, "Boss", ItemClassification.progression),
    "Brachion Defeated": Ys8ItemData("Temple of the Great Tree Temple Boss Arena Brachion", None, "Boss", ItemClassification.progression),
    "Byfteriza Defeated": Ys8ItemData("Waterdrop Cave Boss Arena Byfteriza", None, "Boss", ItemClassification.progression),
    "Carveros Defeated": Ys8ItemData("Baja Tower Boss Arena Carveros", None, "Boss", ItemClassification.progression),
    "Clareon Defeated": Ys8ItemData("Towering Coral Forest Boss Arena Clareon", None, "Boss", ItemClassification.progression),
    "Coelacantos Defeated": Ys8ItemData("Archeozoic Chasm Mid-Boss Arena Coelacantos", None, "Boss", ItemClassification.progression),
    "Doxa Griel Defeated": Ys8ItemData("Valley of Kings Mid-Boss Arena Doxa Griel", None, "Boss", ItemClassification.progression),
    "End the Lacrimosa": Ys8ItemData("Octus Overlook Selection Sphere Goal", None, "Goal", ItemClassification.progression),
    "Exmetal Defeated": Ys8ItemData("Baja Tower Mid-Boss Arena Exmetal", None, "Boss", ItemClassification.progression),
    "Gargantula Defeated": Ys8ItemData("Eroded Valley Boss Arena Gargantula", None, "Boss", ItemClassification.progression),
    "Giasburn Defeated": Ys8ItemData("Mont Gendarme Boss Arena Giasburn", None, "Boss", ItemClassification.progression),
    "Kiergaard Weissman Defeated": Ys8ItemData("Odd Rock Coast Odd Rock Coast Kiergaard Weissman", None, "Boss", ItemClassification.progression),
    "Laspisus Defeated": Ys8ItemData("Schlamm Jungle Boss Arena Laspisus", None, "Boss", ItemClassification.progression),
    "Lonbrigius Defeated": Ys8ItemData("Eroded Valley Mid-Boss Arena Lonbrigius", None, "Boss", ItemClassification.progression),
    "Magamandra Defeated": Ys8ItemData("Schlamm Jungle Mid-Boss Arena Magamandra", None, "Boss", ItemClassification.progression),
    "Master Kong Adol Defeated": Ys8ItemData("Vista Ridge Vista Ridge Lower Master Kong Adol", None, "Boss", ItemClassification.progression),
    "Master Kong Dana Defeated": Ys8ItemData("Odd Rock Coast Odd Rock Coast Master Kong Dana", None, "Boss", ItemClassification.progression),
    "Master Kong Hummel Defeated": Ys8ItemData("Pangaia Plains Ancient Tree Master Kong Hummel", None, "Boss", ItemClassification.progression),
    "Master Kong Laxia Defeated": Ys8ItemData("Mont Gendarme Boss Arena Master Kong Laxia", None, "Boss", ItemClassification.progression),
    "Master Kong Ricotta Defeated": Ys8ItemData("Roaring Seashore Parasequoia Master Kong Ricotta", None, "Boss", ItemClassification.progression),
    "Master Kong Sahad Defeated": Ys8ItemData("Sunrise Beach Sunrise Beach Master Kong Sahad", None, "Boss", ItemClassification.progression),
    "Mephorash Defeated": Ys8ItemData("Silent Tower Second Basement Mephorash", None, "Boss", ItemClassification.progression),
    "Oceanus Defeated": Ys8ItemData("Archeozoic Chasm Boss Arena Oceanus", None, "Boss", ItemClassification.progression),
    "Pirate Revenant Defeated": Ys8ItemData("Pirate Ship Eleftheria Deck Pirate Revenant", None, "Boss", ItemClassification.progression),
    "Psyche-Hydra Defeated": Ys8ItemData("Octus Overlook Path of the Ocean Era Psyche-Hydra", None, "Boss", ItemClassification.progression),
    "Psyche-Minos Defeated": Ys8ItemData("Octus Overlook Path of the Frozen Era Psyche-Minos", None, "Boss", ItemClassification.progression),
    "Psyche-Nestor Defeated": Ys8ItemData("Octus Overlook Path of the Insectoid Era Psyche-Nestor", None, "Boss", ItemClassification.progression),
    "Psyche-Ura Defeated": Ys8ItemData("Octus Overlook Path of the Sky Era Psyche-Ura", None, "Boss", ItemClassification.progression),
    "Serpentus Defeated": Ys8ItemData("Towering Coral Forest Mid-Boss Arena Serpentus", None, "Boss", ItemClassification.progression),
    "Silvia Defeated": Ys8ItemData("Calm Inlet Calm Inlet (Castaway Village Area) Silvia", None, "Boss", ItemClassification.progression),
    "Force Garmr Defeated": Ys8ItemData("Valley of Kings Before Door Force Garmr Encounter", None, "Encounter", ItemClassification.progression),
    "Gilkyra Encounter Defeated": Ys8ItemData("East Coast Cave East Coast Cave Gilkyra Encounter", None, "Encounter", ItemClassification.progression),
    # Grind area access events
    "Grind: Archeozoic Chasm": Ys8ItemData("Archeozoic Chasm Front Grind Access", None, "Grind", ItemClassification.progression),
    "Grind: Baja Tower": Ys8ItemData("Baja Tower Lower Floors Grind Access", None, "Grind", ItemClassification.progression),
    "Grind: Bolado Monastery": Ys8ItemData("Bolado Monastery Grind Access", None, "Grind", ItemClassification.progression),
    "Grind: Eroded Valley": Ys8ItemData("Eroded Valley Front Grind Access", None, "Grind", ItemClassification.progression),
    "Grind: Lodinia Marshlands": Ys8ItemData("Lodinia Marshlands Front Grind Access", None, "Grind", ItemClassification.progression),
    "Grind: Mont Gendarme": Ys8ItemData("Mont Gendarme Front Grind Access", None, "Grind", ItemClassification.progression),
    "Grind: Nostalgia Cape": Ys8ItemData("Nostalgia Cape Area Grind Access", None, "Grind", ItemClassification.progression),
    "Grind: Octus Overlook": Ys8ItemData("Octus Overlook Grind Access", None, "Grind", ItemClassification.progression),
    "Grind: Schlamm Jungle": Ys8ItemData("Schlamm Jungle Front Grind Access", None, "Grind", ItemClassification.progression),
    "Grind: Seiren North Access": Ys8ItemData("Seiren North Access Grind Access", None, "Grind", ItemClassification.progression),
    "Grind: Silent Tower": Ys8ItemData("Silent Tower Grind Access", None, "Grind", ItemClassification.progression),
    "Grind: Temple of the Great Tree": Ys8ItemData("Temple of the Great Tree Grind Access", None, "Grind", ItemClassification.progression),
    "Grind: Towal Highway": Ys8ItemData("Towal Highway Grind Access", None, "Grind", ItemClassification.progression),
    "Grind: Towering Coral Forest": Ys8ItemData("Towering Coral Forest Front Grind Access", None, "Grind", ItemClassification.progression),
    "Grind: Towering Coral Forest Rear": Ys8ItemData("Towering Coral Forest Before Boss Grind Access", None, "Grind", ItemClassification.progression),
    "Grind: Valley of Kings": Ys8ItemData("Lodinia Marshlands Back Grind Access", None, "Grind", ItemClassification.progression),
    "Grind: Western Foot of Gendarme": Ys8ItemData("Western Foot of Gendarme Grind Access", None, "Grind", ItemClassification.progression),
    "Grind: Eroded Valley Rear": Ys8ItemData("Eroded Valley Before Boss Grind Access", None, "Grind", ItemClassification.progression),
    "Grind: Schlamm Jungle Rear": Ys8ItemData("Schlamm Jungle Before Boss Grind Access", None, "Grind", ItemClassification.progression),
    "Grind: Mont Gendarme Rear": Ys8ItemData("Mont Gendarme Upper Grind Access", None, "Grind", ItemClassification.progression),
    "Grind: Lodinia Marshlands Rear": Ys8ItemData("Lodinia Marshlands Near Sky Garden Grind Access", None, "Grind", ItemClassification.progression),
    "Grind: Mont Gendarme Night": Ys8ItemData("Mont Gendarme (Night) Grind Access", None, "Grind", ItemClassification.progression),
    "Grind: Pangaia Plains Night": Ys8ItemData("Pangaia Plains (Night) Grind Access", None, "Grind", ItemClassification.progression),
    "Grind: Towering Coral Forest Night": Ys8ItemData("Towering Coral Forest (Night) Grind Access", None, "Grind", ItemClassification.progression),
    # Material farming access events
    "Material: Accursed Shell (Western Foot of Gendarme)": Ys8ItemData("Accursed Shell Farming - Western Foot of Gendarme", None, "Material", ItemClassification.progression),
    "Material: Ancient Bone (Archeozoic Chasm)": Ys8ItemData("Ancient Bone Farming - Archeozoic Chasm", None, "Material", ItemClassification.progression),
    "Material: Ancient Bone (Temple of the Great Tree)": Ys8ItemData("Ancient Bone Farming - Temple of the Great Tree", None, "Material", ItemClassification.progression),
    "Material: Ancient Hide (Nostalgia Cape)": Ys8ItemData("Ancient Hide Farming - Nostalgia Cape", None, "Material", ItemClassification.progression),
    "Material: Ancient Hide (Waterdrop Cave)": Ys8ItemData("Ancient Hide Farming - Waterdrop Cave", None, "Material", ItemClassification.progression),
    "Material: Ancient Lumber (Octus Overlook)": Ys8ItemData("Ancient Lumber Farming - Octus Overlook", None, "Material", ItemClassification.progression),
    "Material: Ancient Lumber (Temple of the Great Tree)": Ys8ItemData("Ancient Lumber Farming - Temple of the Great Tree", None, "Material", ItemClassification.progression),
    "Material: Beast Bone (East Coast Cave)": Ys8ItemData("Beast Bone Farming - East Coast Cave", None, "Material", ItemClassification.progression),
    "Material: Beast Bone (Vista Ridge)": Ys8ItemData("Beast Bone Farming - Vista Ridge", None, "Material", ItemClassification.progression),
    "Material: Beast Claw (Western Foot of Gendarme)": Ys8ItemData("Beast Claw Farming - Western Foot of Gendarme", None, "Material", ItemClassification.progression),
    "Material: Beast Hide (Schlamm Jungle)": Ys8ItemData("Beast Hide Farming - Schlamm Jungle", None, "Material", ItemClassification.progression),
    "Material: Beast Hide (Western Foot of Gendarme)": Ys8ItemData("Beast Hide Farming - Western Foot of Gendarme", None, "Material", ItemClassification.progression),
    "Material: Beautiful Flower (Nameless Coast)": Ys8ItemData("Beautiful Flower Farming - Nameless Coast", None, "Material", ItemClassification.progression),
    "Material: Dandale Horn (Lodinia Marshlands)": Ys8ItemData("Dandale Horn Farming - Lodinia Marshlands", None, "Material", ItemClassification.progression),
    "Material: Dragon Crest Stone (Silent Tower)": Ys8ItemData("Dragon Crest Stone Farming - Silent Tower", None, "Material", ItemClassification.progression),
    "Material: Dragon Crest Stone (Valley of Kings)": Ys8ItemData("Dragon Crest Stone Farming - Valley of Kings", None, "Material", ItemClassification.progression),
    "Material: Essence Stone (Baja Tower)": Ys8ItemData("Essence Stone Farming - Baja Tower", None, "Material", ItemClassification.progression),
    "Material: Essence Stone (Valley of Kings)": Ys8ItemData("Essence Stone Farming - Valley of Kings", None, "Material", ItemClassification.progression),
    "Material: Flexible Branch (Towering Coral Forest Night)": Ys8ItemData("Flexible Branch Farming - TCF Night", None, "Material", ItemClassification.progression),
    "Material: Flexible Branch (Waterfall Grotto)": Ys8ItemData("Flexible Branch Farming - Waterfall Grotto", None, "Material", ItemClassification.progression),
    "Material: Glow Rock (Towering Coral Forest Night)": Ys8ItemData("Glow Rock Farming - TCF Night", None, "Material", ItemClassification.progression),
    "Material: Iron Ore (Eroded Valley)": Ys8ItemData("Iron Ore Farming - Eroded Valley", None, "Material", ItemClassification.progression),
    "Material: Iron Ore (Towering Coral Forest)": Ys8ItemData("Iron Ore Farming - Towering Coral Forest", None, "Material", ItemClassification.progression),
    "Material: Lustrous Scale (East Coast Cave)": Ys8ItemData("Lustrous Scale Farming - East Coast Cave", None, "Material", ItemClassification.progression),
    "Material: Lustrous Scale (Nostalgia Cape)": Ys8ItemData("Lustrous Scale Farming - Nostalgia Cape", None, "Material", ItemClassification.progression),
    "Material: Razor Feather (Schlamm Jungle)": Ys8ItemData("Razor Feather Farming - Schlamm Jungle", None, "Material", ItemClassification.progression),
    "Material: Saurian Scale (Great River Valley)": Ys8ItemData("Saurian Scale Farming - Great River Valley", None, "Material", ItemClassification.progression),
    "Material: Saurian Scale (Towal Highway)": Ys8ItemData("Saurian Scale Farming - Towal Highway", None, "Material", ItemClassification.progression),
    "Material: Stalactite (Nameless Coast)": Ys8ItemData("Stalactite Farming - Nameless Coast", None, "Material", ItemClassification.progression),
    "Material: Sword Tip Fang (Western Foot of Gendarme)": Ys8ItemData("Sword Tip Fang Farming - Western Foot of Gendarme", None, "Material", ItemClassification.progression),
    "Material: Tektite Ore (Mont Gendarme)": Ys8ItemData("Tektite Ore Farming - Mont Gendarme", None, "Material", ItemClassification.progression),
    "Material: Tektite Ore (Towal Highway)": Ys8ItemData("Tektite Ore Farming - Towal Highway", None, "Material", ItemClassification.progression),
    "Material: Tektite Ore (Western Foot of Gendarme)": Ys8ItemData("Tektite Ore Farming - Western Foot of Gendarme", None, "Material", ItemClassification.progression),
    "Material: Thick Hide (Schlamm Jungle)": Ys8ItemData("Thick Hide Farming - Schlamm Jungle", None, "Material", ItemClassification.progression),
    "Material: Thick Hide (Western Foot of Gendarme)": Ys8ItemData("Thick Hide Farming - Western Foot of Gendarme", None, "Material", ItemClassification.progression),
    "Material: Thunder Claw (Great River Valley)": Ys8ItemData("Thunder Claw Farming - Great River Valley", None, "Material", ItemClassification.progression),
    "Material: Thunder Claw (Valley of Kings)": Ys8ItemData("Thunder Claw Farming - Valley of Kings", None, "Material", ItemClassification.progression),
    "Material: Underworld Bone (Octus Overlook)": Ys8ItemData("Underworld Bone Farming - Octus Overlook", None, "Material", ItemClassification.progression),
    "Material: Underworld Hide (Octus Overlook)": Ys8ItemData("Underworld Hide Farming - Octus Overlook", None, "Material", ItemClassification.progression),
    "Melaiduma Defeated": Ys8ItemData("Former Sanctuary Crypt - Final Floor Boss Arena Melaiduma", None, "Boss", ItemClassification.progression),
    "Psyches of the Sky Era": Ys8ItemData("Psyches", None, "SetFlag", ItemClassification.progression),
    "Psyches of the Insectoid Era": Ys8ItemData("Psyches", None, "SetFlag", ItemClassification.progression),
    "Psyches of the Ocean Era": Ys8ItemData("Psyches", None, "SetFlag", ItemClassification.progression),
    "Psyches of the Frozen Era": Ys8ItemData("Psyches", None, "SetFlag", ItemClassification.progression),
    "Psyches of the Sky Era Access": Ys8ItemData("Psyches Access", None, "SetFlag", ItemClassification.progression),
    "Psyches of the Insectoid Era Access": Ys8ItemData("Psyches Access", None, "SetFlag", ItemClassification.progression),
    "Psyches of the Ocean Era Access": Ys8ItemData("Psyches Access", None, "SetFlag", ItemClassification.progression),
    "Psyches of the Frozen Era Access": Ys8ItemData("Psyches Access", None, "SetFlag", ItemClassification.progression)
}

#Make item categories
item_name_groups: Dict[str, Set[str]] = {}
for item in item_table.keys():
    category = item_table[item].category
    if category not in item_name_groups.keys():
        item_name_groups[category] = set()
    item_name_groups[category].add(item)

