from typing import Dict, NamedTuple, Optional, Set

from BaseClasses import Item, ItemClassification


class Ys8Item(Item):
    game: str = "Kingdom Hearts"


class Ys8ItemData(NamedTuple):
    category: str
    code: int
    type: str
    classification: ItemClassification = ItemClassification.filler
    weight: int = 1
    flags: Optional[list[bytes]] = None


def get_items_by_category(category: str) -> Dict[str, Ys8ItemData]:
    return {name: data for name, data in item_table.items() if data.category == category}

item_table: Dict[str, Ys8ItemData] = {
    "End the Lacrimosa": Ys8ItemData("Goal", code = 1, classification = ItemClassification.progression, type = "Event"),
    "Mistilteinn": Ys8ItemData("Weapon", code = 900, classification = ItemClassification.useful, type = "Item"),
    "Spirit Ring Celesdia": Ys8ItemData("Weapon", code = 1300, classification = ItemClassification.useful, type = "Item"),
    "Bone Necklace": Ys8ItemData("Accessory", code = 15100, classification = ItemClassification.filler, type = "Item"),
    "Bone Necklace II": Ys8ItemData("Accessory", code = 15200, classification = ItemClassification.filler, type = "Item"),
    "Bone Necklace III": Ys8ItemData("Accessory", code = 15300, classification = ItemClassification.filler, type = "Item"),
    "Blade Ring": Ys8ItemData("Accessory", code = 15500, classification = ItemClassification.filler, type = "Item"),
    "Blade Ring II": Ys8ItemData("Accessory", code = 15600, classification = ItemClassification.useful, type = "Item"),
    "Blade Ring III": Ys8ItemData("Accessory", code = 15700, classification = ItemClassification.useful, type = "Item"),
    "Shield Earring": Ys8ItemData("Accessory", code = 15900, classification = ItemClassification.filler, type = "Item"),
    "Shield earring II": Ys8ItemData("Accessory", code = 16000, classification = ItemClassification.filler, type = "Item"),
    "Shield Earrings III": Ys8ItemData("Accessory", code = 16100, classification = ItemClassification.filler, type = "Item"),
    "Snake Amulet": Ys8ItemData("Accessory", code = 16300, classification = ItemClassification.filler, type = "Item"),
    "Lightning Amulet": Ys8ItemData("Accessory", code = 16500, classification = ItemClassification.filler, type = "Item"),
    "Crow Amulet": Ys8ItemData("Accessory", code = 16700, classification = ItemClassification.filler, type = "Item"),
    "Fenrir Talisman": Ys8ItemData("Accessory", code = 16900, classification = ItemClassification.filler, type = "Item"),
    "Pyrios Talisman": Ys8ItemData("Accessory", code = 17100, classification = ItemClassification.filler, type = "Item"),
    "Pyrios Stone": Ys8ItemData("Accessory", code = 17200, classification = ItemClassification.filler, type = "Item"),
    "Nature Talisman": Ys8ItemData("Accessory", code = 17500, classification = ItemClassification.filler, type = "Item"),
    "Warrior's Mark": Ys8ItemData("Accessory", code = 17600, classification = ItemClassification.filler, type = "Item"),
    "Warrior's Seal II": Ys8ItemData("Accessory", code = 17700, classification = ItemClassification.filler, type = "Item"),
    "Warrior's Mark III": Ys8ItemData("Accessory", code = 17800, classification = ItemClassification.filler, type = "Item"),
    "Warrior's Mark IV": Ys8ItemData("Accessory", code = 17900, classification = ItemClassification.filler, type = "Item"),
    "Red Cape": Ys8ItemData("Accessory", code = 18000, classification = ItemClassification.filler, type = "Item"),
    "Blue Cape": Ys8ItemData("Accessory", code = 18200, classification = ItemClassification.filler, type = "Item"),
    "Blue Moon Talisman": Ys8ItemData("Accessory", code = 18300, classification = ItemClassification.filler, type = "Item"),
    "Sun Talisman": Ys8ItemData("Accessory", code = 18500, classification = ItemClassification.filler, type = "Item"),
    "Hunter Hat": Ys8ItemData("Accessory", code = 18600, classification = ItemClassification.filler, type = "Item"),
    "Blood Fang": Ys8ItemData("Accessory", code = 19000, classification = ItemClassification.filler, type = "Item"),
    "Athlete's Ring": Ys8ItemData("Accessory", code = 19200, classification = ItemClassification.useful, type = "Item"),
    "Athlete Belt": Ys8ItemData("Accessory", code = 19300, classification = ItemClassification.filler, type = "Item"),
    "Hero's Belt": Ys8ItemData("Accessory", code = 19500, classification = ItemClassification.filler, type = "Item"),
    "Legend's Belt": Ys8ItemData("Accessory", code = 19600, classification = ItemClassification.filler, type = "Item"),
    "Wanderer Cloak": Ys8ItemData("Accessory", code = 19700, classification = ItemClassification.filler, type = "Item"),
    "Tiger Claw": Ys8ItemData("Accessory", code = 19900, classification = ItemClassification.useful, type = "Item"),
    "Eagle Feather": Ys8ItemData("Accessory", code = 20000, classification = ItemClassification.useful, type = "Item"),
    "Hawk Wing": Ys8ItemData("Accessory", code = 20100, classification = ItemClassification.filler, type = "Item"),
    "Feather Boots": Ys8ItemData("Accessory", code = 20200, classification = ItemClassification.useful, type = "Item"),
    "Jade Pendant": Ys8ItemData("Accessory", code = 20600, classification = ItemClassification.filler, type = "Item"),
    "Ocean Hogeki": Ys8ItemData("Accessory", code = 20900, classification = ItemClassification.useful, type = "Item"),
    "Earth Orb": Ys8ItemData("Accessory", code = 21000, classification = ItemClassification.useful, type = "Item"),
    "Sky Crown": Ys8ItemData("Accessory", code = 21100, classification = ItemClassification.filler, type = "Item"),
    "Saint's Ring": Ys8ItemData("Accessory", code = 21200, classification = ItemClassification.useful, type = "Item"),
    "Spirit Necklace": Ys8ItemData("Accessory", code = 21300, classification = ItemClassification.useful, type = "Item"),
    "Prominent Cloak": Ys8ItemData("Accessory", code = 21500, classification = ItemClassification.filler, type = "Item"),
    "Slash Medal": Ys8ItemData("Accessory", code = 21800, classification = ItemClassification.filler, type = "Item"),
    "Leather Armor x2": Ys8ItemData("Accessory", code = 24300, classification = ItemClassification.filler, type = "Item"),
    "Needle Wristband": Ys8ItemData("Accessory", code = 25200, classification = ItemClassification.filler, type = "Item"),
    "Iron Shield": Ys8ItemData("Accessory", code = 25300, classification = ItemClassification.filler, type = "Item"),
    "Stone Glove": Ys8ItemData("Accessory", code = 25400, classification = ItemClassification.filler, type = "Item"),
    "Gauntlet": Ys8ItemData("Accessory", code = 25500, classification = ItemClassification.filler, type = "Item"),
    "Red Glove": Ys8ItemData("Accessory", code = 25700, classification = ItemClassification.filler, type = "Item"),
    "Dark Glove": Ys8ItemData("Accessory", code = 25800, classification = ItemClassification.filler, type = "Item"),
    "Bandit Gloves": Ys8ItemData("Accessory", code = 25900, classification = ItemClassification.filler, type = "Item"),
    "Blue Glove": Ys8ItemData("Accessory", code = 26000, classification = ItemClassification.filler, type = "Item"),
    "Soft Leather Gloves": Ys8ItemData("Accessory", code = 26600, classification = ItemClassification.filler, type = "Item"),
    "Prickly Band": Ys8ItemData("Accessory", code = 26700, classification = ItemClassification.filler, type = "Item"),
    "Tektite Shield": Ys8ItemData("Accessory", code = 26800, classification = ItemClassification.filler, type = "Item"),
    "Bolt Bracelet": Ys8ItemData("Accessory", code = 26900, classification = ItemClassification.filler, type = "Item"),
    "Heavy Gauntlet": Ys8ItemData("Accessory", code = 27000, classification = ItemClassification.filler, type = "Item"),
    "Warrior Wrist": Ys8ItemData("Accessory", code = 27100, classification = ItemClassification.useful, type = "Item"),
    "Crimson Bracelet": Ys8ItemData("Accessory", code = 27200, classification = ItemClassification.filler, type = "Item"),
    "Black Bracelet": Ys8ItemData("Accessory", code = 27300, classification = ItemClassification.filler, type = "Item"),
    "Blue Bracelet": Ys8ItemData("Accessory", code = 27500, classification = ItemClassification.filler, type = "Item"),
    "Barbaric Bracelet": Ys8ItemData("Accessory", code = 27600, classification = ItemClassification.filler, type = "Item"),
    "Abyssal Gauntlet": Ys8ItemData("Accessory", code = 28800, classification = ItemClassification.filler, type = "Item"),
    "Bandit Gauntlets": Ys8ItemData("Accessory", code = 28900, classification = ItemClassification.filler, type = "Item"),
    "Blizzard Gauntlets": Ys8ItemData("Accessory", code = 29000, classification = ItemClassification.filler, type = "Item"),
    "Eternal Gauntlets": Ys8ItemData("Accessory", code = 29300, classification = ItemClassification.useful, type = "Item"),
    "Light Arm Guard": Ys8ItemData("Accessory", code = 29500, classification = ItemClassification.filler, type = "Item"),
    "Thunder Gauntlets": Ys8ItemData("Accessory", code = 29700, classification = ItemClassification.filler, type = "Item"),
    "Ancient Bone": Ys8ItemData("Consumable", code = 30300, classification = ItemClassification.filler, type = "Item"),
    "Beast Hide x2": Ys8ItemData("Consumable", code = 30700, classification = ItemClassification.filler, type = "Item"),
    "Ancient Hide": Ys8ItemData("Consumable", code = 30800, classification = ItemClassification.filler, type = "Item"),
    "Sterile Mucus x5": Ys8ItemData("Consumable", code = 31100, classification = ItemClassification.filler, type = "Item"),
    "Sparkling Mucus x2": Ys8ItemData("Consumable", code = 31200, classification = ItemClassification.filler, type = "Item"),
    "Sturdy Lumber x3": Ys8ItemData("Consumable", code = 31600, classification = ItemClassification.filler, type = "Item"),
    "Beautiful Flower x5": Ys8ItemData("Consumable", code = 32100, classification = ItemClassification.filler, type = "Item"),
    "Iron Ore x3": Ys8ItemData("Consumable", code = 32600, classification = ItemClassification.filler, type = "Item"),
    "Iron Ore x5": Ys8ItemData("Consumable", code = 32601, classification = ItemClassification.filler, type = "Item"),
    "Tektite Ore x2": Ys8ItemData("Consumable", code = 32700, classification = ItemClassification.filler, type = "Item"),
    "Tektite Ore x3": Ys8ItemData("Consumable", code = 32701, classification = ItemClassification.filler, type = "Item"),
    "Tektite Ore x5": Ys8ItemData("Consumable", code = 32702, classification = ItemClassification.filler, type = "Item"),
    "Essence Stone": Ys8ItemData("Consumable", code = 32800, classification = ItemClassification.filler, type = "Item"),
    "Essence Stone x2": Ys8ItemData("Consumable", code = 32801, classification = ItemClassification.filler, type = "Item"),
    "Essence Stone x3": Ys8ItemData("Consumable", code = 32802, classification = ItemClassification.filler, type = "Item"),
    "Beast Claw x3": Ys8ItemData("Consumable", code = 40000, classification = ItemClassification.filler, type = "Item"),
    "Remex x5": Ys8ItemData("Consumable", code = 40100, classification = ItemClassification.filler, type = "Item"),
    "Gwaranga Pincer x2": Ys8ItemData("Consumable", code = 40400, classification = ItemClassification.filler, type = "Item"),
    "Bullfrodon Mucus": Ys8ItemData("Consumable", code = 40500, classification = ItemClassification.filler, type = "Item"),
    "Digitalis Leaf x3": Ys8ItemData("Consumable", code = 41900, classification = ItemClassification.filler, type = "Item"),
    "Digitalis Leaf x5": Ys8ItemData("Consumable", code = 41901, classification = ItemClassification.filler, type = "Item"),
    "Sword Tip Fang x3": Ys8ItemData("Consumable", code = 42000, classification = ItemClassification.filler, type = "Item"),
    "Razor Feather x3": Ys8ItemData("Consumable", code = 42100, classification = ItemClassification.filler, type = "Item"),
    "Accursed Shell x3": Ys8ItemData("Consumable", code = 42200, classification = ItemClassification.filler, type = "Item"),
    "Lustrous Scale x3": Ys8ItemData("Consumable", code = 42300, classification = ItemClassification.filler, type = "Item"),
    "Salamandine Hide x3": Ys8ItemData("Consumable", code = 42400, classification = ItemClassification.filler, type = "Item"),
    "Large Pearl": Ys8ItemData("Consumable", code = 43600, classification = ItemClassification.filler, type = "Item"),
    "Large Pearl x3": Ys8ItemData("Consumable", code = 43601, classification = ItemClassification.filler, type = "Item"),
    "Glow Rock": Ys8ItemData("Consumable", code = 43700, classification = ItemClassification.filler, type = "Item"),
    "Glow Rock x3": Ys8ItemData("Consumable", code = 43701, classification = ItemClassification.filler, type = "Item"),
    "Stalactite x3": Ys8ItemData("Consumable", code = 43800, classification = ItemClassification.filler, type = "Item"),
    "Thunder Claw x3": Ys8ItemData("Consumable", code = 44000, classification = ItemClassification.filler, type = "Item"),
    "Blue Sky Feather x3": Ys8ItemData("Consumable", code = 44100, classification = ItemClassification.filler, type = "Item"),
    "Diamond Shell x3": Ys8ItemData("Consumable", code = 44200, classification = ItemClassification.filler, type = "Item"),
    "Rigid Fiber": Ys8ItemData("Consumable", code = 44300, classification = ItemClassification.filler, type = "Item"),
    "Rigid Fiber x2": Ys8ItemData("Consumable", code = 44301, classification = ItemClassification.filler, type = "Item"),
    "Rigid Fiber x3": Ys8ItemData("Consumable", code = 44302, classification = ItemClassification.filler, type = "Item"),
    "Vivine Bitters x2": Ys8ItemData("Consumable", code = 44400, classification = ItemClassification.filler, type = "Item"),
    "Saurian Scale": Ys8ItemData("Consumable", code = 44600, classification = ItemClassification.filler, type = "Item"),
    "Saurian Scale x2": Ys8ItemData("Consumable", code = 44601, classification = ItemClassification.filler, type = "Item"),
    "Moonlight Grass x3": Ys8ItemData("Consumable", code = 45700, classification = ItemClassification.filler, type = "Item"),
    "Rim Flower": Ys8ItemData("Consumable", code = 45900, classification = ItemClassification.filler, type = "Item"),
    "Rim Flower x2": Ys8ItemData("Consumable", code = 45901, classification = ItemClassification.filler, type = "Item"),
    "Sunlight Fang x2": Ys8ItemData("Consumable", code = 46000, classification = ItemClassification.filler, type = "Item"),
    "Lunar Wing x2": Ys8ItemData("Consumable", code = 46100, classification = ItemClassification.filler, type = "Item"),
    "Lunar Wings x2": Ys8ItemData("Consumable", code = 46100, classification = ItemClassification.filler, type = "Item"),
    "Starry Shell x2": Ys8ItemData("Consumable", code = 46200, classification = ItemClassification.filler, type = "Item"),
    "Acidic Liquid": Ys8ItemData("Consumable", code = 46300, classification = ItemClassification.filler, type = "Item"),
    "Dandale Horn": Ys8ItemData("Consumable", code = 46500, classification = ItemClassification.filler, type = "Item"),
    "Prismatic Jewel": Ys8ItemData("Consumable", code = 47600, classification = ItemClassification.progression, type = "Item"),
    "Prismatic Jewel x2": Ys8ItemData("Consumable", code = 47601, classification = ItemClassification.progression, type = "Item"),
    "Prismatic Jewel x3": Ys8ItemData("Consumable", code = 47602, classification = ItemClassification.progression, type = "Item"),
    "Prismatic Jewel x5": Ys8ItemData("Consumable", code = 47603, classification = ItemClassification.progression, type = "Item"),
    "Dragon Crest Stone": Ys8ItemData("Consumable", code = 47800, classification = ItemClassification.filler, type = "Item"),
    "Dragon Crest Stone x2": Ys8ItemData("Consumable", code = 47801, classification = ItemClassification.filler, type = "Item"),
    "Great Tree Lumber": Ys8ItemData("Consumable", code = 47900, classification = ItemClassification.filler, type = "Item"),
    "Great Tree Lumber x2": Ys8ItemData("Consumable", code = 47901, classification = ItemClassification.filler, type = "Item"),
    "Saurian Carapace": Ys8ItemData("Consumable", code = 48600, classification = ItemClassification.filler, type = "Item"),
    "Rivera's Immortal Flower x3": Ys8ItemData("Consumable", code = 49700, classification = ItemClassification.filler, type = "Item"),
    "Pure Orichalcum": Ys8ItemData("Consumable", code = 49800, classification = ItemClassification.useful, type = "Item"),
    "Aura Grass": Ys8ItemData("Consumable", code = 49900, classification = ItemClassification.filler, type = "Item"),
    "Aura Grass x2": Ys8ItemData("Consumable", code = 49901, classification = ItemClassification.filler, type = "Item"),
    "Aura Grass x3": Ys8ItemData("Consumable", code = 49902, classification = ItemClassification.filler, type = "Item"),
    "Heal Potion": Ys8ItemData("Consumable", code = 50000, classification = ItemClassification.filler, type = "Item"),
    "Full Potion": Ys8ItemData("Consumable", code = 50100, classification = ItemClassification.filler, type = "Item"),
    "Revive Medicine": Ys8ItemData("Consumable", code = 50300, classification = ItemClassification.filler, type = "Item"),
    "Great Tree Drop": Ys8ItemData("Consumable", code = 50400, classification = ItemClassification.useful, type = "Item"),
    "Dynastic Water": Ys8ItemData("Consumable", code = 50700, classification = ItemClassification.useful, type = "Item"),
    "Medicine": Ys8ItemData("Consumable", code = 50800, classification = ItemClassification.filler, type = "Item"),
    "Full Medicine": Ys8ItemData("Consumable", code = 50900, classification = ItemClassification.filler, type = "Item"),
    "Antidote x3": Ys8ItemData("Consumable", code = 51000, classification = ItemClassification.filler, type = "Item"),
    "Antidote x5": Ys8ItemData("Consumable", code = 51001, classification = ItemClassification.filler, type = "Item"),
    "Eye Drops x3": Ys8ItemData("Consumable", code = 51100, classification = ItemClassification.filler, type = "Item"),
    "Eye Drops x5": Ys8ItemData("Consumable", code = 51101, classification = ItemClassification.filler, type = "Item"),
    "Antiparalytic": Ys8ItemData("Consumable", code = 51200, classification = ItemClassification.filler, type = "Item"),
    "Antiparalytic x3": Ys8ItemData("Consumable", code = 51201, classification = ItemClassification.filler, type = "Item"),
    "Antiparalytic x5": Ys8ItemData("Consumable", code = 51202, classification = ItemClassification.filler, type = "Item"),
    "Defrost Medicine x3": Ys8ItemData("Consumable", code = 51300, classification = ItemClassification.filler, type = "Item"),
    "Defrost Medicine x5": Ys8ItemData("Consumable", code = 51301, classification = ItemClassification.filler, type = "Item"),
    "Burn Medicine x3": Ys8ItemData("Consumable", code = 51400, classification = ItemClassification.filler, type = "Item"),
    "Burn Medicine x5": Ys8ItemData("Consumable", code = 51401, classification = ItemClassification.filler, type = "Item"),
    "Hemostatic": Ys8ItemData("Consumable", code = 51500, classification = ItemClassification.filler, type = "Item"),
    "Hemostatic x3": Ys8ItemData("Consumable", code = 51501, classification = ItemClassification.filler, type = "Item"),
    "Hemostatic x5": Ys8ItemData("Consumable", code = 51502, classification = ItemClassification.filler, type = "Item"),
    "Remedy x3": Ys8ItemData("Consumable", code = 51600, classification = ItemClassification.filler, type = "Item"),
    "Antiparalytic x3": Ys8ItemData("Consumable", code = 51700, classification = ItemClassification.filler, type = "Item"),
    "Burn Medicine x3": Ys8ItemData("Consumable", code = 51800, classification = ItemClassification.filler, type = "Item"),
    "Remedy x3": Ys8ItemData("Consumable", code = 51900, classification = ItemClassification.filler, type = "Item"),
    "Sweet Remedy": Ys8ItemData("Consumable", code = 52000, classification = ItemClassification.filler, type = "Item"),
    "Sweet Remedy x3": Ys8ItemData("Consumable", code = 52001, classification = ItemClassification.filler, type = "Item"),
    "Sweet Remedy x5": Ys8ItemData("Consumable", code = 52002, classification = ItemClassification.filler, type = "Item"),
    "Bitter Remedy": Ys8ItemData("Consumable", code = 52100, classification = ItemClassification.filler, type = "Item"),
    "Bitter Remedy x2": Ys8ItemData("Consumable", code = 52101, classification = ItemClassification.filler, type = "Item"),
    "Bitter Remedy x3": Ys8ItemData("Consumable", code = 52102, classification = ItemClassification.filler, type = "Item"),
    "Hermit's Elixir": Ys8ItemData("Consumable", code = 52200, classification = ItemClassification.filler, type = "Item"),
    "Hermit's Elixir x3": Ys8ItemData("Consumable", code = 52201, classification = ItemClassification.filler, type = "Item"),
    "Strength Elixir": Ys8ItemData("Consumable", code = 52300, classification = ItemClassification.filler, type = "Item"),
    "Strength Elixir x3": Ys8ItemData("Consumable", code = 52301, classification = ItemClassification.filler, type = "Item"),
    "Defense Elixir": Ys8ItemData("Consumable", code = 52400, classification = ItemClassification.filler, type = "Item"),
    "Defense Elixir x3": Ys8ItemData("Consumable", code = 52401, classification = ItemClassification.filler, type = "Item"),
    "Life Elixir": Ys8ItemData("Consumable", code = 52500, classification = ItemClassification.filler, type = "Item"),
    "Life Elixir x3": Ys8ItemData("Consumable", code = 52501, classification = ItemClassification.filler, type = "Item"),
    "Spirit Elixir": Ys8ItemData("Consumable", code = 52600, classification = ItemClassification.useful, type = "Item"),
    "Tempest Elixir": Ys8ItemData("Consumable", code = 52700, classification = ItemClassification.filler, type = "Item"),
    "Beastiary Potion": Ys8ItemData("Consumable", code = 52800, classification = ItemClassification.filler, type = "Item"),
    "Coconut x2": Ys8ItemData("Consumable", code = 53100, classification = ItemClassification.filler, type = "Item"),
    "Mango x2": Ys8ItemData("Consumable", code = 53200, classification = ItemClassification.filler, type = "Item"),
    "Mango x5": Ys8ItemData("Consumable", code = 53201, classification = ItemClassification.filler, type = "Item"),
    "Dragon Tree Treasure": Ys8ItemData("Consumable", code = 53300, classification = ItemClassification.filler, type = "Item"),
    "Ripe Crudberry": Ys8ItemData("Consumable", code = 53500, classification = ItemClassification.filler, type = "Item"),
    "Ripe Crudberry x2": Ys8ItemData("Consumable", code = 53501, classification = ItemClassification.filler, type = "Item"),
    "Ripe Crudberry x3": Ys8ItemData("Consumable", code = 53502, classification = ItemClassification.filler, type = "Item"),
    "Ripe Coconut": Ys8ItemData("Consumable", code = 53600, classification = ItemClassification.filler, type = "Item"),
    "Ripe Coconut x2": Ys8ItemData("Consumable", code = 53601, classification = ItemClassification.filler, type = "Item"),
    "Ripe Coconut x3": Ys8ItemData("Consumable", code = 53602, classification = ItemClassification.filler, type = "Item"),
    "Ripe Mango": Ys8ItemData("Consumable", code = 53700, classification = ItemClassification.filler, type = "Item"),
    "Ripe Mango x2": Ys8ItemData("Consumable", code = 53701, classification = ItemClassification.filler, type = "Item"),
    "Ripe Mango x3": Ys8ItemData("Consumable", code = 53702, classification = ItemClassification.filler, type = "Item"),
    "Dragon Tree Treasure": Ys8ItemData("Consumable", code = 53800, classification = ItemClassification.filler, type = "Item"),
    "Dragon Tree Treasure x3": Ys8ItemData("Consumable", code = 53801, classification = ItemClassification.filler, type = "Item"),
    "Hope Stone": Ys8ItemData("Consumable", code = 54200, classification = ItemClassification.filler, type = "Item"),
    "Luminous Ring": Ys8ItemData("Consumable", code = 54300, classification = ItemClassification.filler, type = "Item"),
    "Devil Fang": Ys8ItemData("Consumable", code = 54400, classification = ItemClassification.filler, type = "Item"),
    "Wings of Heavenly Light": Ys8ItemData("Consumable", code = 54500, classification = ItemClassification.filler, type = "Item"),
    "Wheel of Eternity": Ys8ItemData("Consumable", code = 54600, classification = ItemClassification.filler, type = "Item"),
    "Crown of Creation": Ys8ItemData("Consumable", code = 54700, classification = ItemClassification.useful, type = "Item"),
    "Stone of Anitquity": Ys8ItemData("Consumable", code = 54800, classification = ItemClassification.useful, type = "Item"),
    "Garment of Many Tongues": Ys8ItemData("Consumable", code = 54900, classification = ItemClassification.useful, type = "Item"),
    "Recipe Book/Mushroom Omelet": Ys8ItemData("Consumable", code = 56900, classification = ItemClassification.progression, type = "Item"),
    "Recipe Book/Hearty Ratatouille": Ys8ItemData("Consumable", code = 57000, classification = ItemClassification.progression, type = "Item"),
    "Recipe Book/Colorful Meuniere": Ys8ItemData("Consumable", code = 57100, classification = ItemClassification.progression, type = "Item"),
    "Recipe Book/Seafood Quiche": Ys8ItemData("Consumable", code = 57200, classification = ItemClassification.progression, type = "Item"),
    "Recipe Book/Cabbage Rolls": Ys8ItemData("Consumable", code = 57300, classification = ItemClassification.progression, type = "Item"),
    "Recipe Book/Meat-Wrapped Mushrooms": Ys8ItemData("Consumable", code = 57400, classification = ItemClassification.progression, type = "Item"),
    "Recipe Book/Fish Fry": Ys8ItemData("Consumable", code = 57500, classification = ItemClassification.progression, type = "Item"),
    "Recipe Book/Pirate's Platter": Ys8ItemData("Consumable", code = 57600, classification = ItemClassification.progression, type = "Item"),
    "Recipe Book/Luxury Coleslaw": Ys8ItemData("Consumable", code = 57700, classification = ItemClassification.progression, type = "Item"),
    "Recipe Book/Heartfelt Bolognese": Ys8ItemData("Consumable", code = 57800, classification = ItemClassification.progression, type = "Item"),
    "Recipe Book/Great Pumpkin Pie": Ys8ItemData("Consumable", code = 57900, classification = ItemClassification.progression, type = "Item"),
    "Spiral Manual": Ys8ItemData("Consumable", code = 58300, classification = ItemClassification.useful, type = "Item"),
    "Fairy Manual": Ys8ItemData("Consumable", code = 58400, classification = ItemClassification.useful, type = "Item"),
    "Wild Manual": Ys8ItemData("Consumable", code = 58500, classification = ItemClassification.useful, type = "Item"),
    "Tremor Manual": Ys8ItemData("Consumable", code = 58600, classification = ItemClassification.useful, type = "Item"),
    "Thorn Manual": Ys8ItemData("Consumable", code = 58700, classification = ItemClassification.useful, type = "Item"),
    "Freeze Manual": Ys8ItemData("Consumable", code = 58800, classification = ItemClassification.useful, type = "Item"),
    "Forest Guide": Ys8ItemData("Consumable", code = 59000, classification = ItemClassification.useful, type = "Item"),
    "Ocean Guide": Ys8ItemData("Consumable", code = 59100, classification = ItemClassification.useful, type = "Item"),
    "Mountain Guide": Ys8ItemData("Consumable", code = 59200, classification = ItemClassification.useful, type = "Item"),
    "Wind Guide": Ys8ItemData("Consumable", code = 59300, classification = ItemClassification.useful, type = "Item"),
    "Seiren Wheat x5": Ys8ItemData("Consumable", code = 60200, classification = ItemClassification.filler, type = "Item"),
    "Pheasant Egg x5": Ys8ItemData("Consumable", code = 60300, classification = ItemClassification.filler, type = "Item"),
    "Sweet Pepper x5": Ys8ItemData("Consumable", code = 60900, classification = ItemClassification.filler, type = "Item"),
    "Eggplant Seed": Ys8ItemData("Consumable", code = 61000, classification = ItemClassification.filler, type = "Item"),
    "Shiny Corn x5": Ys8ItemData("Consumable", code = 61200, classification = ItemClassification.filler, type = "Item"),
    "King Pumpkin x2": Ys8ItemData("Consumable", code = 61400, classification = ItemClassification.filler, type = "Item"),
    "Strength Elixir": Ys8ItemData("Consumable", code = 61700, classification = ItemClassification.filler, type = "Item"),
    "Defense Elixir": Ys8ItemData("Consumable", code = 61800, classification = ItemClassification.filler, type = "Item"),
    "Life Elixir": Ys8ItemData("Consumable", code = 61900, classification = ItemClassification.filler, type = "Item"),
    "Empty Bottle": Ys8ItemData("Consumable", code = 62000, classification = ItemClassification.filler, type = "Item"),
    "Empty bottle": Ys8ItemData("Consumable", code = 62000, classification = ItemClassification.filler, type = "Item"),
    "Bait x5": Ys8ItemData("Consumable", code = 62800, classification = ItemClassification.filler, type = "Item"),
    "Bait x10": Ys8ItemData("Consumable", code = 62801, classification = ItemClassification.filler, type = "Item"),
    "Fishing Rod": Ys8ItemData("Consumable", code = 62900, classification = ItemClassification.progression, type = "Item"),
    "Energy Fragment x50": Ys8ItemData("Consumable", code = 67000, classification = ItemClassification.filler, type = "Item"),
    "Energy Fragment x100": Ys8ItemData("Consumable", code = 67001, classification = ItemClassification.filler, type = "Item"),
    "Energy Fragment x150": Ys8ItemData("Consumable", code = 67002, classification = ItemClassification.filler, type = "Item"),
    "Eyedrop Formula": Ys8ItemData("Consumable", code = 68700, classification = ItemClassification.filler, type = "Item"),
    "Blood Formula": Ys8ItemData("Consumable", code = 68900, classification = ItemClassification.filler, type = "Item"),
    "Delight Formula": Ys8ItemData("Consumable", code = 69000, classification = ItemClassification.filler, type = "Item"),
    "Bitter Formula": Ys8ItemData("Consumable", code = 69100, classification = ItemClassification.useful, type = "Item"),
    "Bless Formula": Ys8ItemData("Consumable", code = 69200, classification = ItemClassification.filler, type = "Item"),
    "Life Formula": Ys8ItemData("Consumable", code = 69300, classification = ItemClassification.filler, type = "Item"),
    "Hide Formula": Ys8ItemData("Consumable", code = 69400, classification = ItemClassification.filler, type = "Item"),
    "Strength Formula": Ys8ItemData("Consumable", code = 69500, classification = ItemClassification.useful, type = "Item"),
    "Defense Formula": Ys8ItemData("Consumable", code = 69600, classification = ItemClassification.filler, type = "Item"),
    "Maiden Journal": Ys8ItemData("Consumable", code = 69800, classification = ItemClassification.progression, type = "Item"),
    "Frozen Flower": Ys8ItemData("Consumable", code = 69900, classification = ItemClassification.progression, type = "Item"),
    "Blue Seal of Whirling Water": Ys8ItemData("Consumable", code = 70000, classification = ItemClassification.progression, type = "Item"),
    "Green Seal of Roaring Stone": Ys8ItemData("Consumable", code = 70100, classification = ItemClassification.progression, type = "Item"),
    "Golden Seal of Piercing Light": Ys8ItemData("Consumable", code = 70200, classification = ItemClassification.progression, type = "Item"),
    "Essence Key Stone": Ys8ItemData("Consumable", code = 70300, classification = ItemClassification.filler, type = "Item"),
    "Battle Armlet": Ys8ItemData("Consumable", code = 72000, classification = ItemClassification.useful, type = "Item"),
    "Dragon Bone Necklace": Ys8ItemData("Consumable", code = 72200, classification = ItemClassification.filler, type = "Item"),
    "Mushin's hairpin": Ys8ItemData("Consumable", code = 72500, classification = ItemClassification.filler, type = "Item"),
    "Fairy Cape": Ys8ItemData("Consumable", code = 72600, classification = ItemClassification.filler, type = "Item"),
    "Shrine Maiden Amulet": Ys8ItemData("Consumable", code = 72700, classification = ItemClassification.progression, type = "Item"),
    "Stone Crown": Ys8ItemData("Consumable", code = 72900, classification = ItemClassification.filler, type = "Item"),
    "Blue Wind Staff": Ys8ItemData("Adventure Gear", code = 73000, classification = ItemClassification.filler, type = "Item"),
    "Nature Talisman": Ys8ItemData("Adventure Gear", code = 73100, classification = ItemClassification.filler, type = "Item"),
    "Gale Feather": Ys8ItemData("Adventure Gear", code = 73500, classification = ItemClassification.useful, type = "Item"),
    "Windy Vestment": Ys8ItemData("Adventure Gear", code = 73600, classification = ItemClassification.useful, type = "Item"),
    "Grip Gloves": Ys8ItemData("Adventure Gear", code = 73700, classification = ItemClassification.progression, type = "Item"),
    "Hermit's Scale": Ys8ItemData("Adventure Gear", code = 73800, classification = ItemClassification.progression, type = "Item"),
    "Glow Stone": Ys8ItemData("Adventure Gear", code = 73900, classification = ItemClassification.progression, type = "Item"),
    "Float Shoes": Ys8ItemData("Adventure Gear", code = 74000, classification = ItemClassification.progression, type = "Item"),
    "Archeopteryx Wings": Ys8ItemData("Adventure Gear", code = 74100, classification = ItemClassification.progression, type = "Item"),
    "Purifying bell": Ys8ItemData("Adventure Gear", code = 74200, classification = ItemClassification.progression, type = "Item"),
    "Ares Seal": Ys8ItemData("Adventure Gear", code = 74300, classification = ItemClassification.useful, type = "Item"),
    "Aeolus Urn": Ys8ItemData("Adventure Gear", code = 74400, classification = ItemClassification.useful, type = "Item"),
    "Eagle Eye Orb": Ys8ItemData("Adventure Gear", code = 74500, classification = ItemClassification.progression, type = "Item"),
    "Pirate's Notes": Ys8ItemData("Consumable", code = 75000, classification = ItemClassification.filler, type = "Item"),
    "Pirate Memo A": Ys8ItemData("Consumable", code = 75100, classification = ItemClassification.filler, type = "Item"),
    "Pirate Memo B": Ys8ItemData("Consumable", code = 75200, classification = ItemClassification.filler, type = "Item"),
    "Pirate Memo C": Ys8ItemData("Consumable", code = 75300, classification = ItemClassification.filler, type = "Item"),
    "Pirate Memo D": Ys8ItemData("Consumable", code = 75400, classification = ItemClassification.filler, type = "Item"),
    "Pirate's Memo E": Ys8ItemData("Consumable", code = 75500, classification = ItemClassification.filler, type = "Item"),
    "T's Memo": Ys8ItemData("Consumable", code = 76000, classification = ItemClassification.progression, type = "Item"),
    "T's Memo A": Ys8ItemData("Consumable", code = 76100, classification = ItemClassification.progression, type = "Item"),
    "T's Memo B": Ys8ItemData("Consumable", code = 76200, classification = ItemClassification.progression, type = "Item"),
    "T's Memo C": Ys8ItemData("Consumable", code = 76300, classification = ItemClassification.progression, type = "Item"),
    "Logbook 1": Ys8ItemData("Consumable", code = 77000, classification = ItemClassification.progression, type = "Item"),
    "Logbook 2": Ys8ItemData("Consumable", code = 77100, classification = ItemClassification.filler, type = "Item"),
    "Logbook 3": Ys8ItemData("Consumable", code = 77200, classification = ItemClassification.filler, type = "Item"),
    "Logbook 4": Ys8ItemData("Consumable", code = 77300, classification = ItemClassification.filler, type = "Item"),
    "Logbook 5": Ys8ItemData("Consumable", code = 77400, classification = ItemClassification.filler, type = "Item"),
    "Monolith Fragment": Ys8ItemData("Consumable", code = 77700, classification = ItemClassification.filler, type = "Item"),
    "Flame Stone": Ys8ItemData("Consumable", code = 77800, classification = ItemClassification.progression, type = "Item"),
    "Ship Blueprint": Ys8ItemData("Consumable", code = 77900, classification = ItemClassification.progression, type = "Item"),
    "Sweet Pepper Seeds": Ys8ItemData("Consumable", code = 78000, classification = ItemClassification.filler, type = "Item"),
    "Shiny Corn Seeds": Ys8ItemData("Consumable", code = 78300, classification = ItemClassification.filler, type = "Item"),
    "Queen Tomato Seeds": Ys8ItemData("Consumable", code = 78400, classification = ItemClassification.filler, type = "Item"),
    "King Pumpkin seeds": Ys8ItemData("Consumable", code = 78500, classification = ItemClassification.filler, type = "Item"),
    "Seiren Nautical Chart": Ys8ItemData("Consumable", code = 79500, classification = ItemClassification.filler, type = "Item"),
    "Treasure Chest Key": Ys8ItemData("Consumable", code = 79600, classification = ItemClassification.progression, type = "Item"),
    "Romun Badge": Ys8ItemData("Consumable", code = 80100, classification = ItemClassification.filler, type = "Item"),
    "Rainbow Pigment": Ys8ItemData("Consumable", code = 80300, classification = ItemClassification.filler, type = "Item"),
    "Ship Nameplate": Ys8ItemData("Consumable", code = 80400, classification = ItemClassification.filler, type = "Item"),
    "Violet Bookmark": Ys8ItemData("Consumable", code = 80800, classification = ItemClassification.filler, type = "Item"),
    "Engraved Pen": Ys8ItemData("Consumable", code = 81300, classification = ItemClassification.filler, type = "Item"),
    "Gold Essence Crystal": Ys8ItemData("Consumable", code = 81500, classification = ItemClassification.filler, type = "Item"),
    "Ancient Coin": Ys8ItemData("Consumable", code = 81600, classification = ItemClassification.filler, type = "Item"),
    "Iron Knuckle": Ys8ItemData("Consumable", code = 81800, classification = ItemClassification.filler, type = "Item"),
    "Snowflake Soap": Ys8ItemData("Consumable", code = 81900, classification = ItemClassification.filler, type = "Item"),
    "Big Seed": Ys8ItemData("Consumable", code = 82700, classification = ItemClassification.filler, type = "Item"),
    "Old Stethoscope": Ys8ItemData("Consumable", code = 82900, classification = ItemClassification.filler, type = "Item"),
}

#Make item categories
item_name_groups: Dict[str, Set[str]] = {}
for item in item_table.keys():
    category = item_table[item].category
    if category not in item_name_groups.keys():
        item_name_groups[category] = set()
    item_name_groups[category].add(item)