from typing import Dict, NamedTuple, Optional, Set
import typing

from BaseClasses import Location

class Ys8Location(Location):
    game: str = "Ys 8"

class Ys8LocationData(NamedTuple):
    category: str
    code: Optional[int] = None
    type: Optional[str] = None
    
def get_locations_by_type(type: str) -> Dict[str, Ys8LocationData]:
    return {name: data for name, data in location_table.items() if data.type == type}

location_table: Dict[str, Ys8LocationData] = {
    # Adol Starting Skill
    "Adol Starting Skill Skill 1 Sonic Slide": Ys8LocationData("Adol Starting Skill", 520, "event"),
    "Adol Starting Skill Skill 2 Arc Shot": Ys8LocationData("Adol Starting Skill", 521, "event"),
    # Archeozoic Chasm
    "Archeozoic Chasm Entrance Chest": Ys8LocationData("Archeozoic Chasm", 248, "chest"),
    "Archeozoic Chasm Cliffs Overlooking Crater Chest 1": Ys8LocationData("Archeozoic Chasm", 249, "chest"),
    "Archeozoic Chasm Cliffs Overlooking Crater Chest 2": Ys8LocationData("Archeozoic Chasm", 250, "chest"),
    "Archeozoic Chasm Whirlpools Chest 1": Ys8LocationData("Archeozoic Chasm", 251, "chest"),
    "Archeozoic Chasm Whirlpools Chest 2": Ys8LocationData("Archeozoic Chasm", 252, "chest"),
    "Archeozoic Chasm Submerged Cave Chest 1": Ys8LocationData("Archeozoic Chasm", 253, "chest"),
    "Archeozoic Chasm Submerged Cave Chest 2": Ys8LocationData("Archeozoic Chasm", 254, "chest"),
    "Archeozoic Chasm Submerged Cave Chest 3": Ys8LocationData("Archeozoic Chasm", 255, "chest"),
    "Archeozoic Chasm Water Vents Chest 1": Ys8LocationData("Archeozoic Chasm", 256, "chest"),
    "Archeozoic Chasm Water Vents Chest 2": Ys8LocationData("Archeozoic Chasm", 257, "chest"),
    "Archeozoic Chasm Sunken Eternia Ruins West Chest": Ys8LocationData("Archeozoic Chasm", 258, "chest"),
    "Archeozoic Chasm Sunken Eternia Ruins East Chest 1": Ys8LocationData("Archeozoic Chasm", 259, "chest"),
    "Archeozoic Chasm Sunken Eternia Ruins East Chest 2": Ys8LocationData("Archeozoic Chasm", 260, "chest"),
    "Archeozoic Chasm Sunken Eternia Ruins East Chest 3": Ys8LocationData("Archeozoic Chasm", 261, "chest"),
    "Archeozoic Chasm Boss Arena Kill Boss": Ys8LocationData("Archeozoic Chasm", 437, "event"),
    "Archeozoic Chasm Boss Arena Driftage": Ys8LocationData("Archeozoic Chasm", 516, "event"),
    "Archeozoic Chasm Boss Arena Oceanus Skill 1": Ys8LocationData("Archeozoic Chasm", 548, "event"),
    "Archeozoic Chasm Boss Arena Oceanus Skill 2": Ys8LocationData("Archeozoic Chasm", 549, "event"),
    "Archeozoic Chasm Mid-Boss Arena Coelacantos Skill 1": Ys8LocationData("Archeozoic Chasm", 550, "event"),
    "Archeozoic Chasm Mid-Boss Arena Coelacantos Skill 2": Ys8LocationData("Archeozoic Chasm", 551, "event"),
    "Archeozoic Chasm Boss Arena Oceanus": Ys8LocationData("Archeozoic Chasm", 594, "event"),
    "Archeozoic Chasm Mid-Boss Arena Coelacantos": Ys8LocationData("Archeozoic Chasm", 595, "event"),
    "Archeozoic Chasm Boss Arena Psyches": Ys8LocationData("Archeozoic Chasm", 623, "event"),
    # Baja Tower
    "Baja Tower Second Floor Chest 1": Ys8LocationData("Baja Tower", 216, "chest"),
    "Baja Tower Second Floor Chest 2": Ys8LocationData("Baja Tower", 217, "chest"),
    "Baja Tower Second Floor Chest 3": Ys8LocationData("Baja Tower", 218, "chest"),
    "Baja Tower Third Floor Chest 1": Ys8LocationData("Baja Tower", 219, "chest"),
    "Baja Tower Third Floor Chest 2": Ys8LocationData("Baja Tower", 220, "chest"),
    "Baja Tower Third Floor Chest 3": Ys8LocationData("Baja Tower", 221, "chest"),
    "Baja Tower Third Floor Chest 4": Ys8LocationData("Baja Tower", 222, "chest"),
    "Baja Tower Mid-Boss Arena Chest": Ys8LocationData("Baja Tower", 223, "chest"),
    "Baja Tower Fifth Floor Chest 1": Ys8LocationData("Baja Tower", 224, "chest"),
    "Baja Tower Fifth Floor Chest 2": Ys8LocationData("Baja Tower", 225, "chest"),
    "Baja Tower Sixth Floor Chest 1": Ys8LocationData("Baja Tower", 226, "chest"),
    "Baja Tower Sixth Floor Chest 2": Ys8LocationData("Baja Tower", 227, "chest"),
    "Baja Tower Sixth Floor Chest 3": Ys8LocationData("Baja Tower", 228, "chest"),
    "Baja Tower Sixth Floor Chest 4": Ys8LocationData("Baja Tower", 229, "chest"),
    "Baja Tower Sixth Floor Chest 5": Ys8LocationData("Baja Tower", 230, "chest"),
    "Baja Tower Top Floor Monolith Scene": Ys8LocationData("Baja Tower", 440, "event"),
    "Baja Tower Boss Arena Carveros Skill 1": Ys8LocationData("Baja Tower", 554, "event"),
    "Baja Tower Boss Arena Carveros Skill 2": Ys8LocationData("Baja Tower", 555, "event"),
    "Baja Tower Mid-Boss Arena Exmetal Skill 1": Ys8LocationData("Baja Tower", 556, "event"),
    "Baja Tower Mid-Boss Arena Exmetal Skill 2": Ys8LocationData("Baja Tower", 557, "event"),
    "Baja Tower Boss Arena Carveros": Ys8LocationData("Baja Tower", 597, "event"),
    "Baja Tower Mid-Boss Arena Exmetal": Ys8LocationData("Baja Tower", 598, "event"),
    "Baja Tower Boss Arena Psyches": Ys8LocationData("Baja Tower", 625, "event"),
    # Base of Western Foot of Gendarme
    "Great River Valley Cliffs Chest 1": Ys8LocationData("Base of Western Foot of Gendarme", 27, "chest"),
    "Great River Valley Falls Chest 1": Ys8LocationData("Base of Western Foot of Gendarme", 93, "chest"),
    "Great River Valley Falls Chest 2": Ys8LocationData("Base of Western Foot of Gendarme", 94, "chest"),
    # Bolado Monastery
    "Bolado Monastery Entrance Chest 1": Ys8LocationData("Bolado Monastery", 269, "chest"),
    "Bolado Monastery Entrance Chest 2": Ys8LocationData("Bolado Monastery", 270, "chest"),
    "Bolado Monastery Entrance Chest 3": Ys8LocationData("Bolado Monastery", 271, "chest"),
    "Bolado Monastery Entrance Chest 4": Ys8LocationData("Bolado Monastery", 272, "chest"),
    "Bolado Monastery Entrance Chest 5": Ys8LocationData("Bolado Monastery", 273, "chest"),
    "Bolado Monastery Basement Chest 1": Ys8LocationData("Bolado Monastery", 274, "chest"),
    "Bolado Monastery Basement Chest 2": Ys8LocationData("Bolado Monastery", 275, "chest"),
    "Bolado Monastery Basement Chest 3": Ys8LocationData("Bolado Monastery", 276, "chest"),
    "Bolado Monastery Basement Chest 4": Ys8LocationData("Bolado Monastery", 277, "chest"),
    "Bolado Monastery Basement Chest 5": Ys8LocationData("Bolado Monastery", 278, "chest"),
    # Calm Inlet: Intercept List 1
    "Calm Inlet Intercept Stage 2": Ys8LocationData("Calm Inlet: Intercept List 1", 446, "event"),
    "Calm Inlet Intercept Stage 3": Ys8LocationData("Calm Inlet: Intercept List 1", 447, "event"),
    "Calm Inlet Intercept Stage 5": Ys8LocationData("Calm Inlet: Intercept List 1", 448, "event"),
    # Calm Inlet: Intercept List 3
    "Calm Inlet Intercept Stage 7": Ys8LocationData("Calm Inlet: Intercept List 3", 449, "event"),
    "Calm Inlet Intercept Stage 9": Ys8LocationData("Calm Inlet: Intercept List 3", 450, "event"),
    # Calm Inlet Map Completion
    "Calm Inlet Map Completion Percent 10": Ys8LocationData("Calm Inlet: Map Completion", 451, "event"),
    "Calm Inlet Map Completion Percent 20": Ys8LocationData("Calm Inlet: Map Completion", 452, "event"),
    "Calm Inlet Map Completion Percent 30": Ys8LocationData("Calm Inlet: Map Completion", 453, "event"),
    "Calm Inlet Map Completion Percent 40": Ys8LocationData("Calm Inlet: Map Completion", 454, "event"),
    "Calm Inlet Map Completion Percent 50": Ys8LocationData("Calm Inlet: Map Completion", 455, "event"),
    "Calm Inlet Map Completion Percent 60": Ys8LocationData("Calm Inlet: Map Completion", 456, "event"),
    "Calm Inlet Map Completion Percent 70": Ys8LocationData("Calm Inlet: Map Completion", 457, "event"),
    "Calm Inlet Map Completion Percent 80": Ys8LocationData("Calm Inlet: Map Completion", 458, "event"),
    "Calm Inlet Map Completion Percent 90": Ys8LocationData("Calm Inlet: Map Completion", 459, "event"),
    "Calm Inlet Map Completion Percent 100": Ys8LocationData("Calm Inlet: Map Completion", 460, "event"),
    # Calm Inlet Jewel Trade
    "Calm Inlet Jewel Trade Item 1": Ys8LocationData("Calm Inlet: Jewel Trade", 461, "event"),
    "Calm Inlet Jewel Trade Item 2": Ys8LocationData("Calm Inlet: Jewel Trade", 462, "event"),
    "Calm Inlet Jewel Trade Item 3": Ys8LocationData("Calm Inlet: Jewel Trade", 463, "event"),
    "Calm Inlet Jewel Trade Item 4": Ys8LocationData("Calm Inlet: Jewel Trade", 464, "event"),
    "Calm Inlet Jewel Trade Item 5": Ys8LocationData("Calm Inlet: Jewel Trade", 465, "event"),
    "Calm Inlet Jewel Trade Past Item 1": Ys8LocationData("Calm Inlet: Jewel Trade", 466, "event"),
    "Calm Inlet Jewel Trade Past Item 2": Ys8LocationData("Calm Inlet: Jewel Trade", 467, "event"),
    "Calm Inlet Jewel Trade Past Item 3": Ys8LocationData("Calm Inlet: Jewel Trade", 468, "event"),
    "Calm Inlet Jewel Trade Past Item 4": Ys8LocationData("Calm Inlet: Jewel Trade", 469, "event"),
    "Calm Inlet Jewel Trade Past Item 5": Ys8LocationData("Calm Inlet: Jewel Trade", 470, "event"),
    # Calm Inlet Fish Trade
    "Calm Inlet Fish Trade Fish 4": Ys8LocationData("Calm Inlet: Fish Trade", 472, "event"),
    "Calm Inlet Fish Trade Fish 8": Ys8LocationData("Calm Inlet: Fish Trade", 473, "event"),
    "Calm Inlet Fish Trade Fish 12": Ys8LocationData("Calm Inlet: Fish Trade", 474, "event"),
    "Calm Inlet Fish Trade Fish 16": Ys8LocationData("Calm Inlet: Fish Trade", 475, "event"),
    "Calm Inlet Fish Trade Fish 20": Ys8LocationData("Calm Inlet: Fish Trade", 476, "event"),
    "Calm Inlet Fish Trade Fish 24": Ys8LocationData("Calm Inlet: Fish Trade", 477, "event"),
    # Calm Inlet Area
    "Nameless Coast Cliffs South - Treebridge Chest 1": Ys8LocationData("Calm Inlet Area", 23, "chest"),
    "Nameless Coast Cliffs South - Treebridge Chest 2": Ys8LocationData("Calm Inlet Area", 24, "chest"),
    "Nameless Coast Shoreline South of Boulder Chest": Ys8LocationData("Calm Inlet Area", 33, "chest"),
    "White Sand Cape North of Starting Shore Chest": Ys8LocationData("Calm Inlet Area", 36, "chest"),
    "Nameless Coast Northwest of Laxia Chest": Ys8LocationData("Calm Inlet Area", 51, "chest"),
    "White Sand Cape Cobalt Crag Chest 1": Ys8LocationData("Calm Inlet Area", 52, "chest"),
    "White Sand Cape Cobalt Crag Chest 2": Ys8LocationData("Calm Inlet Area", 53, "chest"),
    "White Sand Cape Cobalt Crag Chest 3": Ys8LocationData("Calm Inlet Area", 54, "chest"),
    "White Sand Cape Alison's Shore Chest": Ys8LocationData("Calm Inlet Area", 55, "chest"),
    "White Sand Cape Coral Shore Chest 1": Ys8LocationData("Calm Inlet Area", 56, "chest"),
    "White Sand Cape Coral Shore Chest 2": Ys8LocationData("Calm Inlet Area", 57, "chest"),
    "Nameless Coast North of Castaway Village (Where Adol Meets Laxia) Laxia Join": Ys8LocationData("Calm Inlet Area", 401, "event"),
    "Calm Inlet Calm Inlet (Castaway Village Area) Little Paro Join": Ys8LocationData("Calm Inlet Area", 403, "event"),
    "Nameless Coast First Avalodragil Arena Sahad Join": Ys8LocationData("Calm Inlet Area", 404, "event"),
    "Calm Inlet Calm Inlet (Castaway Village Area) Dogi Join": Ys8LocationData("Calm Inlet Area", 405, "event"),
    "White Sand Cape Alison's Shore Alison Join": Ys8LocationData("Calm Inlet Area", 406, "event"),
    "Calm Inlet Ricotta and Shoebill Reunite Shoebill Join": Ys8LocationData("Calm Inlet Area", 426, "event"),
    "Calm Inlet Calm Inlet (Castaway Village Area) Fishing Tutorial": Ys8LocationData("Calm Inlet Area", 471, "event"),
    "Calm Inlet Calm Inlet (Castaway Village Area) Silvia Skill 1": Ys8LocationData("Calm Inlet Area", 542, "event"),
    "Calm Inlet Calm Inlet (Castaway Village Area) Silvia Skill 2": Ys8LocationData("Calm Inlet Area", 543, "event"),
    "Nameless Coast First Avalodragil Arena Avalodragil Skill": Ys8LocationData("Calm Inlet Area", 578, "event"),
    "Calm Inlet Calm Inlet (Castaway Village Area) Silvia": Ys8LocationData("Calm Inlet Area", 591, "event"),
    "Nameless Coast First Avalodragil Arena Avalodragil": Ys8LocationData("Calm Inlet Area", 609, "event"),
    "Calm Inlet Discovery Rewards Half": Ys8LocationData("Calm Inlet Area", 478, "event"),
    "Calm Inlet Discovery Rewards All": Ys8LocationData("Calm Inlet Area", 479, "event"),
    "White Sand Cape Cobalt Crag Landmark": Ys8LocationData("Calm Inlet Area", 638, "event"),
    # Dana Starting Skill
    "Dana Starting Skill Skill 1 Twin Edge": Ys8LocationData("Dana Starting Skill", 530, "event"),
    "Dana Starting Skill Skill 2 Sonic Rise": Ys8LocationData("Dana Starting Skill", 531, "event"),
    # East Coast Cave
    "East Coast Cave East Coast Cave Chest 1": Ys8LocationData("East Coast Cave After Gilkyra", 381, "chest"),
    "East Coast Cave East Coast Cave Chest 2": Ys8LocationData("East Coast Cave Before Gilkyra", 382, "chest"),
    "East Coast Cave East Coast Cave Chest 3": Ys8LocationData("East Coast Cave After Gilkyra", 383, "chest"),
    "East Coast Cave East Coast Cave Landmark": Ys8LocationData("East Coast Cave Before Gilkyra", 651, "event"),
    "East Coast Cave East Coast Cave Gilkyra Encounter": Ys8LocationData("East Coast Cave Before Gilkyra", 661, "event"),
    # Eroded Valley
    "Eroded Valley Entrance Chest 1": Ys8LocationData("Eroded Valley Front", 128, "chest"),
    "Eroded Valley Entrance Chest 2": Ys8LocationData("Eroded Valley Front", 129, "chest"),
    "Eroded Valley Entrance Chest 3": Ys8LocationData("Eroded Valley Webbed Walkway", 130, "chest"),
    "Eroded Valley Entrance Chest 4": Ys8LocationData("Eroded Valley Front", 131, "chest"),
    "Eroded Valley Entrance Chest 5": Ys8LocationData("Eroded Valley Webbed Walkway", 132, "chest"),
    "Eroded Valley Cave Chest 1": Ys8LocationData("Eroded Valley Front", 133, "chest"),
    "Eroded Valley Cave Chest 2": Ys8LocationData("Eroded Valley Front", 134, "chest"),
    "Eroded Valley Cave Chest 3": Ys8LocationData("Eroded Valley Front", 135, "chest"),
    "Eroded Valley Dark Passage Chest": Ys8LocationData("Eroded Valley Dark Area", 136, "chest"),
    "Eroded Valley Midpoint Chest 1": Ys8LocationData("Eroded Valley Front", 137, "chest"),
    "Eroded Valley Midpoint Chest 2": Ys8LocationData("Eroded Valley Front", 138, "chest"),
    "Eroded Valley Midpoint Chest 3": Ys8LocationData("Eroded Valley Front", 139, "chest"),
    "Eroded Valley Mid-Boss Arena Chest": Ys8LocationData("Eroded Valley Mid-Boss Arena", 140, "chest"),
    "Eroded Valley Webbed Walkways Chest 1": Ys8LocationData("Eroded Valley Webbed Walkway", 141, "chest"),
    "Eroded Valley Webbed Walkways Chest 2": Ys8LocationData("Eroded Valley Webbed Walkway", 142, "chest"),
    "Eroded Valley Webbed Walkways Chest 3": Ys8LocationData("Eroded Valley Before Boss", 143, "chest"),
    "Eroded Valley End Chest": Ys8LocationData("Eroded Valley Before Boss", 144, "chest"),
    "Eroded Valley Boss Arena Kill Boss": Ys8LocationData("Eroded Valley Boss Arena", 435, "event"),
    "Eroded Valley End Corpse": Ys8LocationData("Eroded Valley Before Boss", 494, "event"),
    "Eroded Valley Midpoint Corpse": Ys8LocationData("Eroded Valley Front", 495, "event"),
    "Eroded Valley Entrance Corpse": Ys8LocationData("Eroded Valley Front", 496, "event"),
    "Eroded Valley Boss Arena Gargantula Skill 1": Ys8LocationData("Eroded Valley Boss Arena", 570, "event"),
    "Eroded Valley Boss Arena Gargantula Skill 2": Ys8LocationData("Eroded Valley Boss Arena", 571, "event"),
    "Eroded Valley Mid-Boss Arena Lonbrigius Skill 1": Ys8LocationData("Eroded Valley Mid-Boss Arena", 572, "event"),
    "Eroded Valley Mid-Boss Arena Lonbrigius Skill 2": Ys8LocationData("Eroded Valley Mid-Boss Arena", 573, "event"),
    #"Eroded Valley Boss Arena Psyches": Ys8LocationData("Eroded Valley", 629, "event"),
    "Eroded Valley Dark Passage Landmark": Ys8LocationData("Eroded Valley Indigo Mineral Vein", 643, "event"),
    # Eternal Hill
    "Eternal Hill Eternal Hill Chest": Ys8LocationData("Eternal Hill", 180, "chest"),
    "Eternal Hill Eternal Hill Griselda Join": Ys8LocationData("Eternal Hill", 427, "event"),
    "Eternal Hill Eternal Hill Landmark": Ys8LocationData("Eternal Hill", 659, "event"),
    # Former Sanctuary Crypt - B1
    "Former Sanctuary Crypt - B1 Entrance Chest 1": Ys8LocationData("Former Sanctuary Crypt - B1", 279, "chest"),
    "Former Sanctuary Crypt - B1 Entrance Chest 2": Ys8LocationData("Former Sanctuary Crypt - B1", 280, "chest"),
    "Former Sanctuary Crypt - B1 Entrance Chest 3": Ys8LocationData("Former Sanctuary Crypt - B1", 281, "chest"),
    "Former Sanctuary Crypt - B1 First Brazier Chest 1": Ys8LocationData("Former Sanctuary Crypt - B1", 283, "chest"),
    "Former Sanctuary Crypt - B1 First Brazier Chest 2": Ys8LocationData("Former Sanctuary Crypt - B1", 284, "chest"),
    "Former Sanctuary Crypt - B1 North Brazier Room Chest 1": Ys8LocationData("Former Sanctuary Crypt - B1", 287, "chest"),
    "Former Sanctuary Crypt - B1 North Brazier Room Chest 2": Ys8LocationData("Former Sanctuary Crypt - B1", 288, "chest"),
    "Former Sanctuary Crypt - B1 Boss Arena Chest": Ys8LocationData("Former Sanctuary Crypt - B1", 291, "chest"),
    # Former Sanctuary Crypt - B2
    "Former Sanctuary Crypt - B2 Entrance Chest 1": Ys8LocationData("Former Sanctuary Crypt - B2", 293, "chest"),
    "Former Sanctuary Crypt - B2 Entrance Chest 2": Ys8LocationData("Former Sanctuary Crypt - B2", 294, "chest"),
    "Former Sanctuary Crypt - B2 Entrance Chest 3": Ys8LocationData("Former Sanctuary Crypt - B2", 295, "chest"),
    "Former Sanctuary Crypt - B2 Stone and Rock Block Puzzle Chest 1": Ys8LocationData("Former Sanctuary Crypt - B2", 296, "chest"),
    "Former Sanctuary Crypt - B2 Stone and Rock Block Puzzle Chest 2": Ys8LocationData("Former Sanctuary Crypt - B2", 297, "chest"),
    "Former Sanctuary Crypt - B2 Boss Arena Chest": Ys8LocationData("Former Sanctuary Crypt - B2", 301, "chest"),
    # Former Sanctuary Crypt - B3
    "Former Sanctuary Crypt - B3 Entrance Chest 1": Ys8LocationData("Former Sanctuary Crypt - B3", 303, "chest"),
    "Former Sanctuary Crypt - B3 Entrance Chest 2": Ys8LocationData("Former Sanctuary Crypt - B3", 304, "chest"),
    "Former Sanctuary Crypt - B3 Entrance Chest 3": Ys8LocationData("Former Sanctuary Crypt - B3", 305, "chest"),
    "Former Sanctuary Crypt - B3 Entrance Chest 4": Ys8LocationData("Former Sanctuary Crypt - B3", 306, "chest"),
    "Former Sanctuary Crypt - B3 Entrance Chest 5": Ys8LocationData("Former Sanctuary Crypt - B3", 307, "chest"),
    "Former Sanctuary Crypt - B3 Entrance Chest 6": Ys8LocationData("Former Sanctuary Crypt - B3", 308, "chest"),
    "Former Sanctuary Crypt - B3 Entrance Chest 7": Ys8LocationData("Former Sanctuary Crypt - B3", 309, "chest"),
    "Former Sanctuary Crypt - B3 Floating Block Puzzle Chest 1": Ys8LocationData("Former Sanctuary Crypt - B3", 320, "chest"),
    "Former Sanctuary Crypt - B3 Floating Block Puzzle Chest 2": Ys8LocationData("Former Sanctuary Crypt - B3", 321, "chest"),
    "Former Sanctuary Crypt - B3 Floating Block Puzzle Chest 3": Ys8LocationData("Former Sanctuary Crypt - B3", 322, "chest"),
    "Former Sanctuary Crypt - B3 Boss Arena Chest": Ys8LocationData("Former Sanctuary Crypt - B3", 329, "chest"),
    # Former Sanctuary Crypt - B4
    "Former Sanctuary Crypt - B4 Entrance Chest 1": Ys8LocationData("Former Sanctuary Crypt - B4", 331, "chest"),
    "Former Sanctuary Crypt - B4 Entrance Chest 2": Ys8LocationData("Former Sanctuary Crypt - B4", 332, "chest"),
    "Former Sanctuary Crypt - B4 Entrance Chest 3": Ys8LocationData("Former Sanctuary Crypt - B4", 333, "chest"),
    "Former Sanctuary Crypt - B4 Entrance Chest 4": Ys8LocationData("Former Sanctuary Crypt - B4", 334, "chest"),
    "Former Sanctuary Crypt - B4 Frozen Statue Room Chest 1": Ys8LocationData("Former Sanctuary Crypt - B4", 337, "chest"),
    "Former Sanctuary Crypt - B4 Frozen Statue Room Chest 2": Ys8LocationData("Former Sanctuary Crypt - B4", 338, "chest"),
    "Former Sanctuary Crypt - B4 Frozen Statue Room Chest 3": Ys8LocationData("Former Sanctuary Crypt - B4", 339, "chest"),
    "Former Sanctuary Crypt - B4 Frozen Statue Room Chest 4": Ys8LocationData("Former Sanctuary Crypt - B4", 340, "chest"),
    "Former Sanctuary Crypt - B4 Boss Arena Chest": Ys8LocationData("Former Sanctuary Crypt - B4", 344, "chest"),
    # Former Sanctuary Crypt - B5
    "Former Sanctuary Crypt - B5 Entrance Chest 1": Ys8LocationData("Former Sanctuary Crypt - B5", 346, "chest"),
    "Former Sanctuary Crypt - B5 Entrance Chest 2": Ys8LocationData("Former Sanctuary Crypt - B5", 347, "chest"),
    "Former Sanctuary Crypt - B5 Entrance Chest 3": Ys8LocationData("Former Sanctuary Crypt - B5", 348, "chest"),
    "Former Sanctuary Crypt - B5 Eastern Hall Chest": Ys8LocationData("Former Sanctuary Crypt - B5", 351, "chest"),
    "Former Sanctuary Crypt - B5 Western Hall Chest 1": Ys8LocationData("Former Sanctuary Crypt - B5", 357, "chest"),
    "Former Sanctuary Crypt - B5 Western Hall Chest 2": Ys8LocationData("Former Sanctuary Crypt - B5", 358, "chest"),
    "Former Sanctuary Crypt - B5 Western Hall Chest 3": Ys8LocationData("Former Sanctuary Crypt - B5", 359, "chest"),
    "Former Sanctuary Crypt - B5 Western Hall Chest 4": Ys8LocationData("Former Sanctuary Crypt - B5", 360, "chest"),
    "Former Sanctuary Crypt - B5 Large Stairwell Chest 1": Ys8LocationData("Former Sanctuary Crypt - B5", 364, "chest"),
    "Former Sanctuary Crypt - B5 Large Stairwell Chest 2": Ys8LocationData("Former Sanctuary Crypt - B5", 365, "chest"),
    "Former Sanctuary Crypt - B5 Boss Arena Chest": Ys8LocationData("Former Sanctuary Crypt - B5", 366, "chest"),
    # Former Sanctuary Crypt - B6
    "Former Sanctuary Crypt - B6 Big Staircase Chest 1": Ys8LocationData("Former Sanctuary Crypt - B6", 369, "chest"),
    "Former Sanctuary Crypt - B6 Big Staircase Chest 2": Ys8LocationData("Former Sanctuary Crypt - B6", 370, "chest"),
    "Former Sanctuary Crypt - B6 Big Staircase Chest 3": Ys8LocationData("Former Sanctuary Crypt - B6", 371, "chest"),
    "Former Sanctuary Crypt - B6 Big Staircase Chest 4": Ys8LocationData("Former Sanctuary Crypt - B6", 372, "chest"),
    # Former Sanctuary Crypt - Final Floor
    "Former Sanctuary Crypt - Final Floor Boss Arena Melaiduma Skill": Ys8LocationData("Former Sanctuary Crypt - Final Floor", 533, "event"),
    "Former Sanctuary Crypt - Final Floor Boss Arena Melaiduma Medals": Ys8LocationData("Former Sanctuary Crypt - Final Floor", 634, "event"),
    "Former Sanctuary Crypt - Final Floor Boss Arena Melaiduma": Ys8LocationData("Former Sanctuary Crypt - Final Floor", 663, "event"),
    "Former Sanctuary Crypt - Final Floor Boss Arena Psyches": Ys8LocationData("Former Sanctuary Crypt - Final Floor", 664, "event"),
    # Great River Valley
    "Nameless Coast Cliffs North Chest": Ys8LocationData("Great River Valley Area", 26, "chest"),
    "Great River Valley Cliffs Chest 2": Ys8LocationData("Great River Valley Area", 28, "chest"),
    "Beast Hills Valley (Where Hummel Joins) Chest": Ys8LocationData("Great River Valley Area", 29, "chest"),
    "Great River Valley Large Shoreline Chest 1": Ys8LocationData("Great River Valley Area", 44, "chest"),
    "Great River Valley Large Shoreline Chest 2": Ys8LocationData("Great River Valley Area", 45, "chest"),
    "Great River Valley Large Shoreline Chest 3": Ys8LocationData("Great River Valley Area", 46, "chest"),
    "Great River Valley Falls Chest 3": Ys8LocationData("Great River Valley Area", 95, "chest"),
    "Great River Valley Falls Chest 4": Ys8LocationData("Great River Valley Area", 96, "chest"),
    "Great River Valley Falls Chest 5": Ys8LocationData("Great River Valley Area", 97, "chest"),
    "Great River Valley Lookout Tower Chest": Ys8LocationData("Great River Valley Area", 114, "chest"),
    "Great River Valley Chimney Rock Chest": Ys8LocationData("Great River Valley Area", 115, "chest"),
    "Waterfall Grotto Waterfall Grotto Sister Nia Join": Ys8LocationData("Great River Valley Area", 410, "event"),
    "Beast Hills Valley (Where Hummel Joins) Hummel Join": Ys8LocationData("Great River Valley Area", 411, "event"),
    "Great River Valley Chimney Rock Landmark": Ys8LocationData("Great River Valley Area", 642, "event"),
    # Waterfall Grotto
    "Waterfall Grotto Waterfall Grotto Chest 1": Ys8LocationData("Waterfall Grotto Dark Area", 392, "chest"),
    "Waterfall Grotto Waterfall Grotto Chest 2": Ys8LocationData("Waterfall Grotto Dark Area", 393, "chest"),
    "Waterfall Grotto Waterfall Grotto Landmark": Ys8LocationData("Milky White Vein", 660, "event"),
    # Hummel Starting Skill
    "Hummel Starting Skill Skill 1 Burst Shot": Ys8LocationData("Hummel Starting Skill", 526, "event"),
    "Hummel Starting Skill Skill 2 Venomous Bullet": Ys8LocationData("Hummel Starting Skill", 527, "event"),
    # Laxia Starting Skill
    "Laxia Starting Skill Skill 1 Dagger Fling": Ys8LocationData("Laxia Starting Skill", 522, "event"),
    "Laxia Starting Skill Skill 2 Wake Up!": Ys8LocationData("Laxia Starting Skill", 523, "event"),
    # Lodinia Marshland
    "Lodinia Marshland Entrance from Vista Ridge Chest 1": Ys8LocationData("Lodinia Marshland", 173, "chest"),
    "Lodinia Marshland Entrance from Vista Ridge Chest 2": Ys8LocationData("Lodinia Marshland", 174, "chest"),
    "Lodinia Marshland Entrance from Vista Ridge Chest 3": Ys8LocationData("Lodinia Marshland", 175, "chest"),
    "Lodinia Marshland Near Submerged Cemetery Chest 1": Ys8LocationData("Lodinia Marshland", 176, "chest"),
    "Lodinia Marshland Near Submerged Cemetery Chest 2": Ys8LocationData("Lodinia Marshland", 177, "chest"),
    "Lodinia Marshland Valley of Kings - Camp Chest": Ys8LocationData("Lodinia Marshland", 178, "chest"),
    "Lodinia Marshland Valley of Kings - Camp (Dawn) Chest": Ys8LocationData("Lodinia Marshland", 179, "chest"),
    "Lodinia Marshland Muddy Lake Chest 1": Ys8LocationData("Lodinia Marshland", 185, "chest"),
    "Lodinia Marshland Muddy Lake Chest 2": Ys8LocationData("Lodinia Marshland", 186, "chest"),
    "Lodinia Marshland Muddy Lake Chest 3": Ys8LocationData("Lodinia Marshland", 187, "chest"),
    "Lodinia Marshland Exit to Valley of Kings Chest 1": Ys8LocationData("Lodinia Marshland", 188, "chest"),
    "Lodinia Marshland Exit to Valley of Kings Chest 2": Ys8LocationData("Lodinia Marshland", 189, "chest"),
    "Lodinia Marshland Exit to Valley of Kings Chest 3": Ys8LocationData("Lodinia Marshland", 190, "chest"),
    "Lodinia Marshland Exit to Valley of Kings Fermented Sap": Ys8LocationData("Lodinia Marshland", 445, "event"),
    "Lodinia Marshland Exit to Valley of Kings Landmark": Ys8LocationData("Lodinia Marshland", 657, "event"),
    # Lombardia
    "Lombardia Opening Cutscene Adol Join": Ys8LocationData("Calm Inlet Area", 429, "event"),
    # Longhorn Coast Area
    "Beast Hills Collapsed Cliff Chest 1": Ys8LocationData("Longhorn Coast Area", 30, "chest"),
    "Beast Hills Collapsed Cliff Chest 2": Ys8LocationData("Longhorn Coast Area", 31, "chest"),
    "Beast Hills Collapsed Cliff Chest 3": Ys8LocationData("Longhorn Coast Area", 32, "chest"),
    "Longhorn Coast Eastern Shore Chest 1": Ys8LocationData("Longhorn Coast Area", 39, "chest"),
    "Longhorn Coast Eastern Shore Chest 2": Ys8LocationData("Longhorn Coast Area", 40, "chest"),
    "Water and Wood Hills Foggy Forest Chest": Ys8LocationData("Longhorn Coast Area", 100, "chest"),
    "Longhorn Coast Reja Shore Reja Join": Ys8LocationData("Longhorn Coast Area", 413, "event"),
    "Water and Wood Hills Water and Wood Hills - Camp Miralda Join": Ys8LocationData("Longhorn Coast Area", 419, "event"),
    "Longhorn Coast Eastern Shore Corpse": Ys8LocationData("Longhorn Coast Area", 498, "event"),
    "Longhorn Coast Eastern Shore Reja's Pikkard": Ys8LocationData("Longhorn Coast Area", 510, "event"),
    # Beehive
    "Longhorn Coast Reja Shore Chest 1": Ys8LocationData("Beehive", 37, "chest"),
    "Longhorn Coast Reja Shore Chest 3": Ys8LocationData("Beehive", 38, "chest"),
    "Longhorn Coast Reja Shore Pirate Treasure": Ys8LocationData("Beehive", 444, "event"),
    "Longhorn Coast Reja Shore Landmark": Ys8LocationData("Beehive", 649, "event"),
    # Metavolicalis Area
    "Roaring Seashore Metavolicalis Chest 1": Ys8LocationData("Metavolicalis Area", 42, "chest"),
    "Roaring Seashore Metavolicalis Chest 2": Ys8LocationData("Metavolicalis Area", 43, "chest"),
    "Roaring Seashore Metavolicalis Kathleen Join": Ys8LocationData("Metavolicalis Area", 409, "event"),
    "Roaring Seashore Metavolicalis Landmark": Ys8LocationData("Metavolicalis Area", 640, "event"),
    # Mont Gendarme
    "Mont Gendarme Entrance Chest": Ys8LocationData("Mont Gendarme Front", 145, "chest"),
    "Mont Gendarme Southern Lower Cliffside Trail Chest 1": Ys8LocationData("Mont Gendarme Front", 147, "chest"),
    "Mont Gendarme Southern Lower Cliffside Trail Chest 2": Ys8LocationData("Mont Gendarme Front", 148, "chest"),
    "Mont Gendarme Northern Lower Cliffside Trail Chest 1": Ys8LocationData("Mont Gendarme Front", 152, "chest"),
    "Mont Gendarme Northern Lower Cliffside Trail Chest 2": Ys8LocationData("Mont Gendarme Front", 153, "chest"),
    "Mont Gendarme Northern Lower Cliffside Trail Chest 3": Ys8LocationData("Mont Gendarme Middle", 154, "chest"),
    "Mont Gendarme Outside Cabin Chest": Ys8LocationData("Mont Gendarme Middle", 157, "chest"),
    "Mont Gendarme Cliffside Midpoint Chest 1": Ys8LocationData("Mont Gendarme Middle", 158, "chest"),
    "Mont Gendarme Cliffside Midpoint Chest 2": Ys8LocationData("Mont Gendarme Middle", 159, "chest"),
    "Mont Gendarme Upper Cliffs 1 Chest 1": Ys8LocationData("Mont Gendarme Middle", 162, "chest"),
    "Mont Gendarme Upper Cliffs 1 Chest 2": Ys8LocationData("Mont Gendarme Middle", 163, "chest"),
    "Mont Gendarme Upper Cliffs 2 Chest": Ys8LocationData("Mont Gendarme Middle", 165, "chest"),
    "Mont Gendarme Mid-Boss Arena Ricotta Join": Ys8LocationData("Mont Gendarme Mid-Boss Arena", 417, "event"),
    "Mont Gendarme Cliffside Midpoint Wish Tree": Ys8LocationData("Mont Gendarme Middle", 443, "event"),
    "Mont Gendarme Mishy Rewards Food 2": Ys8LocationData("Mont Gendarme Upper", 480, "event"),
    "Mont Gendarme Mishy Rewards Food 4": Ys8LocationData("Mont Gendarme Upper", 481, "event"),
    "Mont Gendarme Mishy Rewards Food 6": Ys8LocationData("Mont Gendarme Upper", 482, "event"),
    "Mont Gendarme Mishy Rewards Food 8": Ys8LocationData("Mont Gendarme Upper", 483, "event"),
    "Mont Gendarme Mishy Rewards Food 10": Ys8LocationData("Mont Gendarme Upper", 484, "event"),
    "Mont Gendarme Mishy Rewards Food 12": Ys8LocationData("Mont Gendarme Upper", 485, "event"),
    "Mont Gendarme Boss Arena Giasburn Skill 1": Ys8LocationData("Mont Gendarme Boss Arena", 560, "event"),
    "Mont Gendarme Boss Arena Giasburn Skill 2": Ys8LocationData("Mont Gendarme Boss Arena", 561, "event"),
    "Mont Gendarme Mid-Boss Arena Avalodragil 2 Skill 1": Ys8LocationData("Mont Gendarme Mid-Boss Arena", 562, "event"),
    "Mont Gendarme Mid-Boss Arena Avalodragil 2 Skill 2": Ys8LocationData("Mont Gendarme Mid-Boss Arena", 563, "event"),
    "Mont Gendarme Boss Arena Master Kong Skill Laxia": Ys8LocationData("Mont Gendarme Boss Arena", 583, "event"),
    #"Mont Gendarme Boss Arena Psyches": Ys8LocationData("Mont Gendarme", 627, "event"),
    # Mont Gendarme (Night)
    "Mont Gendarme (Night) Entrance Chest": Ys8LocationData("Mont Gendarme (Night)", 146, "chest"),
    "Mont Gendarme (Night) Southern Lower Cliffside Trail Chest 1": Ys8LocationData("Mont Gendarme (Night)", 149, "chest"),
    "Mont Gendarme (Night) Southern Lower Cliffside Trail Chest 2": Ys8LocationData("Mont Gendarme (Night)", 150, "chest"),
    "Mont Gendarme (Night) Southern Lower Cliffside Trail Chest 3": Ys8LocationData("Mont Gendarme (Night)", 151, "chest"),
    "Mont Gendarme (Night) Northern Lower Cliffside Trail Chest 1": Ys8LocationData("Mont Gendarme (Night)", 155, "chest"),
    "Mont Gendarme (Night) Northern Lower Cliffside Trail Chest 2": Ys8LocationData("Mont Gendarme (Night)", 156, "chest"),
    "Mont Gendarme (Night) Cliffside Midpoint Chest": Ys8LocationData("Mont Gendarme (Night)", 160, "chest"),
    "Mont Gendarme (Night) Mid-Boss Arena Chest": Ys8LocationData("Mont Gendarme (Night)", 161, "chest"),
    "Mont Gendarme (Night) Upper Cliffs 1 Chest": Ys8LocationData("Mont Gendarme (Night)", 164, "chest"),
    "Mont Gendarme (Night) Upper Cliffs 2 Chest": Ys8LocationData("Mont Gendarme (Night)", 166, "chest"),
    # Seiren North
    "Seiren North Top Chest": Ys8LocationData("Seiren North Access", 120, "chest"),
    "Seiren North Outside First Cave Exit Chest 1": Ys8LocationData("Seiren North Access", 121, "chest"),
    "Seiren North Outside First Cave Exit Chest 2": Ys8LocationData("Seiren North Access", 122, "chest"),
    "Seiren North Lower Mountain Trail Chest": Ys8LocationData("Seiren North Access", 123, "chest"),
    "Seiren North Outside Second Cave Entrance Chest 1": Ys8LocationData("Seiren North Access", 124, "chest"),
    "Seiren North Outside Second Cave Entrance Chest 2": Ys8LocationData("Seiren North Access", 125, "chest"),
    "Titis Primeval Forest Exit to Pangaia Plains Chest": Ys8LocationData("Seiren North Access", 167, "chest"),
    "Titis Primeval Forest Near Primordial Den Chest 1": Ys8LocationData("Seiren North Access", 168, "chest"),
    "Titis Primeval Forest Near Primordial Den Chest 2": Ys8LocationData("Seiren North Access", 169, "chest"),
    "Titis Primeval Forest Near Primordial Den Chest 3": Ys8LocationData("Seiren North Access", 170, "chest"),
    "Titis Primeval Forest Entrance from Temple Approach Chest": Ys8LocationData("Seiren North Access", 171, "chest"),
    "Pangaia Plains Pond Chest": Ys8LocationData("Seiren North Access", 181, "chest"),
    "Pangaia Plains Ancient Tree Chest": Ys8LocationData("Seiren North Access", 183, "chest"),
    "Pangaia Plains Northern Plains Chest 1": Ys8LocationData("Seiren North Access", 192, "chest"),
    "Pangaia Plains Northern Plains Chest 2": Ys8LocationData("Seiren North Access", 193, "chest"),
    "Mountain Pinnacle Trail First Cave Chest": Ys8LocationData("Seiren North Access", 377, "chest"),
    "Pangaia Plains Northern Plains Silvia Join": Ys8LocationData("Seiren North Access", 421, "event"),
    "Pangaia Plains Ancient Tree Master Kong Skill Hummel": Ys8LocationData("Seiren North Access", 584, "event"),
    "Mountain Pinnacle Trail Second Cave Landmark": Ys8LocationData("Seiren North Access", 653, "event"),
    "Titis Primeval Forest Near Primordial Den Landmark": Ys8LocationData("Seiren North Access", 654, "event"),
    "Pangaia Plains Northern Plains Landmark": Ys8LocationData("Seiren North Access", 655, "event"),
    "Pangaia Plains Ancient Tree Landmark": Ys8LocationData("Seiren North Access", 656, "event"),
    # Nameless Coast North of Boulder
    "Nameless Coast Cliffs South - Treebridge Chest 3": Ys8LocationData("Nameless Coast North of Boulder", 25, "chest"),
    "Nameless Coast Shoreline North of Boulder Chest 1": Ys8LocationData("Nameless Coast North of Boulder", 34, "chest"),
    "Nameless Coast Shoreline North of Boulder Chest 2": Ys8LocationData("Nameless Coast North of Boulder", 35, "chest"),
    "Nameless Coast Forested Area (Gravel Spot) Chest 1": Ys8LocationData("Nameless Coast North of Boulder", 91, "chest"),
    "Nameless Coast Forested Area (Gravel Spot) Chest 2": Ys8LocationData("Nameless Coast North of Boulder", 92, "chest"),
    "Nameless Coast Shoreline North of Boulder Landmark": Ys8LocationData("Nameless Coast North of Boulder", 637, "event"),
    # Nostalgia Cape
    "Nostalgia Cape Nostalgia Cape Chest": Ys8LocationData("Nostalgia Cape Area", 41, "chest"),
    "Nostalgia Cape Nostalgia Cape Ed Join": Ys8LocationData("Nostalgia Cape Area", 424, "event"),
    "Nostalgia Cape Nostalgia Cape Driftage": Ys8LocationData("Nostalgia Cape Area", 513, "event"),
    "Nostalgia Cape Nostalgia Cape Landmark": Ys8LocationData("Nostalgia Cape Area", 650, "event"),
    # Octus Overlook
    "Octus Overlook Path of the Ocean Era Chest 1": Ys8LocationData("Octus Overlook", 202, "chest"),
    "Octus Overlook Path of the Ocean Era Chest 2": Ys8LocationData("Octus Overlook", 203, "chest"),
    "Octus Overlook Path of the Frozen Era Chest 1": Ys8LocationData("Octus Overlook", 204, "chest"),
    "Octus Overlook Path of the Frozen Era Chest 2": Ys8LocationData("Octus Overlook", 205, "chest"),
    "Octus Overlook Path of the Frozen Era Chest 3": Ys8LocationData("Octus Overlook", 206, "chest"),
    "Octus Overlook Path of the Insectoid Era Chest 1": Ys8LocationData("Octus Overlook", 207, "chest"),
    "Octus Overlook Path of the Insectoid Era Chest 2": Ys8LocationData("Octus Overlook", 208, "chest"),
    "Octus Overlook Path of the Insectoid Era Chest 3": Ys8LocationData("Octus Overlook", 209, "chest"),
    "Octus Overlook Path of the Sky Era Chest 1": Ys8LocationData("Octus Overlook", 210, "chest"),
    "Octus Overlook Path of the Sky Era Chest 2": Ys8LocationData("Octus Overlook", 211, "chest"),
    "Octus Overlook Path of the Sky Era Chest 3": Ys8LocationData("Octus Overlook", 212, "chest"),
    "Octus Overlook Selection Sphere Chest 1": Ys8LocationData("Octus Overlook", 213, "chest"),
    "Octus Overlook Selection Sphere Chest 2": Ys8LocationData("Octus Overlook", 214, "chest"),
    "Octus Overlook Selection Sphere Chest 3": Ys8LocationData("Octus Overlook", 215, "chest"),
    "Octus Overlook Selection Sphere Goal": Ys8LocationData("Octus Overlook", 438, "event"),
    "Octus Overlook Path of the Sky Era Psyche-Ura Skill 1": Ys8LocationData("Octus Overlook", 534, "event"),
    "Octus Overlook Path of the Sky Era Psyche-Ura Skill 2": Ys8LocationData("Octus Overlook", 535, "event"),
    "Octus Overlook Path of the Insectoid Era Psyche-Nestor Skill 1": Ys8LocationData("Octus Overlook", 536, "event"),
    "Octus Overlook Path of the Insectoid Era Psyche-Nestor Skill 2": Ys8LocationData("Octus Overlook", 537, "event"),
    "Octus Overlook Path of the Frozen Era Psyche-Minos Skill 1": Ys8LocationData("Octus Overlook", 538, "event"),
    "Octus Overlook Path of the Frozen Era Psyche-Minos Skill 2": Ys8LocationData("Octus Overlook", 539, "event"),
    "Octus Overlook Path of the Ocean Era Psyche-Hydra Skill 1": Ys8LocationData("Octus Overlook", 540, "event"),
    "Octus Overlook Path of the Ocean Era Psyche-Hydra Skill 2": Ys8LocationData("Octus Overlook", 541, "event"),
    "Octus Overlook Path of the Sky Era Psyche-Ura": Ys8LocationData("Octus Overlook", 587, "event"),
    "Octus Overlook Path of the Insectoid Era Psyche-Nestor": Ys8LocationData("Octus Overlook", 588, "event"),
    "Octus Overlook Path of the Frozen Era Psyche-Minos": Ys8LocationData("Octus Overlook", 589, "event"),
    "Octus Overlook Path of the Ocean Era Psyche-Hydra": Ys8LocationData("Octus Overlook", 590, "event"),
    "Octus Overlook Path of the Sky Era Psyches": Ys8LocationData("Octus Overlook", 618, "event"),
    "Octus Overlook Path of the Insectoid Era Psyches": Ys8LocationData("Octus Overlook", 619, "event"),
    "Octus Overlook Path of the Frozen Era Psyches": Ys8LocationData("Octus Overlook", 620, "event"),
    "Octus Overlook Path of the Ocean Era Psyches": Ys8LocationData("Octus Overlook", 621, "event"),
    # Odd Rock Coast
    "Odd Rock Coast Odd Rock Coast Licht Join": Ys8LocationData("Odd Rock Coast", 415, "event"),
    "Odd Rock Coast Odd Rock Coast Quina Join": Ys8LocationData("Odd Rock Coast", 416, "event"),
    "Odd Rock Coast Odd Rock Coast Kiergaard Weissman Skill 1": Ys8LocationData("Odd Rock Coast", 564, "event"),
    "Odd Rock Coast Odd Rock Coast Kiergaard Weissman Skill 2": Ys8LocationData("Odd Rock Coast", 565, "event"),
    "Odd Rock Coast Odd Rock Coast Master Kong Skill Dana": Ys8LocationData("Odd Rock Coast", 582, "event"),
    # Pangaia Plains (Night)
    "Pangaia Plains (Night) Pond Chest": Ys8LocationData("Pangaia Plains (Night)", 182, "chest"),
    "Pangaia Plains (Night) Ancient Tree Chest": Ys8LocationData("Pangaia Plains (Night)", 184, "chest"),
    "Pangaia Plains (Night) Northern Plains Chest": Ys8LocationData("Pangaia Plains (Night)", 194, "chest"),
    # Parasequoia Area
    "Roaring Seashore Parasequoia Chest 1": Ys8LocationData("Parasequoia Area", 58, "chest"),
    "Roaring Seashore Parasequoia Chest 2": Ys8LocationData("Parasequoia Area", 59, "chest"),
    "Roaring Seashore Parasequoia Master Kong Skill Ricotta": Ys8LocationData("Parasequoia Area", 580, "event"),
    "Roaring Seashore Parasequoia Master Kong Ricotta": Ys8LocationData("Parasequoia Area", 611, "event"),
    "Roaring Seashore Parasequoia Landmark": Ys8LocationData("Parasequoia Area", 641, "event"),
    # Pirate Ship Eleftheria
    "Pirate Ship Eleftheria Submerged Hold Chest 1": Ys8LocationData("Pirate Ship Eleftheria Submerged Hold", 1, "chest"),
    "Pirate Ship Eleftheria Submerged Hold Chest 2": Ys8LocationData("Pirate Ship Eleftheria Submerged Hold", 2, "chest"),
    "Pirate Ship Eleftheria Submerged Hold Chest 3": Ys8LocationData("Pirate Ship Eleftheria Submerged Hold", 3, "chest"),
    "Pirate Ship Eleftheria Submerged Hold Chest 4": Ys8LocationData("Pirate Ship Eleftheria Submerged Hold", 4, "chest"),
    "Pirate Ship Eleftheria Hold Chest 1": Ys8LocationData("Pirate Ship Eleftheria Submerged Hold", 5, "chest"),
    "Pirate Ship Eleftheria Hold Chest 2": Ys8LocationData("Pirate Ship Eleftheria", 6, "chest"),
    "Pirate Ship Eleftheria Hold Chest 3": Ys8LocationData("Pirate Ship Eleftheria", 7, "chest"),
    "Pirate Ship Eleftheria Hold Chest 4": Ys8LocationData("Pirate Ship Eleftheria", 8, "chest"),
    "Pirate Ship Eleftheria Accessway Chest 1": Ys8LocationData("Pirate Ship Eleftheria", 9, "chest"),
    "Pirate Ship Eleftheria Accessway Chest 2": Ys8LocationData("Pirate Ship Eleftheria", 10, "chest"),
    "Pirate Ship Eleftheria Accessway Chest 3": Ys8LocationData("Pirate Ship Eleftheria", 11, "chest"),
    "Pirate Ship Eleftheria Accessway Chest 4": Ys8LocationData("Pirate Ship Eleftheria", 12, "chest"),
    "Pirate Ship Eleftheria Crew Quarters Chest 1": Ys8LocationData("Pirate Ship Eleftheria", 13, "chest"),
    "Pirate Ship Eleftheria Crew Quarters Chest 2": Ys8LocationData("Pirate Ship Eleftheria", 14, "chest"),
    "Pirate Ship Eleftheria Crew Quarters Chest 3": Ys8LocationData("Pirate Ship Eleftheria", 15, "chest"),
    "Pirate Ship Eleftheria Crew Quarters Chest 4": Ys8LocationData("Pirate Ship Eleftheria", 16, "chest"),
    "Pirate Ship Eleftheria Crew Quarters Chest 5": Ys8LocationData("Pirate Ship Eleftheria", 17, "chest"),
    "Pirate Ship Eleftheria Deck Chest": Ys8LocationData("Pirate Ship Eleftheria", 18, "chest"),
    "Pirate Ship Eleftheria Stairwell Chest 1": Ys8LocationData("Pirate Ship Eleftheria", 19, "chest"),
    "Pirate Ship Eleftheria Stairwell Chest 2": Ys8LocationData("Pirate Ship Eleftheria", 20, "chest"),
    "Pirate Ship Eleftheria Stairwell Chest 3": Ys8LocationData("Pirate Ship Eleftheria", 21, "chest"),
    "Pirate Ship Eleftheria Stairwell Chest 4": Ys8LocationData("Pirate Ship Eleftheria", 22, "chest"),
    "Pirate Ship Eleftheria Deck Kill Boss": Ys8LocationData("Pirate Ship Eleftheria", 434, "event"),
    "Pirate Ship Eleftheria Stairwell Corpse": Ys8LocationData("Pirate Ship Eleftheria", 499, "event"),
    "Pirate Ship Eleftheria Deck Seiren Chart": Ys8LocationData("Pirate Ship Eleftheria", 512, "event"),
    "Pirate Ship Eleftheria Hold Corpse": Ys8LocationData("Pirate Ship Eleftheria", 515, "event"),
    "Pirate Ship Eleftheria Deck Pirate Revenant Skill 1": Ys8LocationData("Pirate Ship Eleftheria", 552, "event"),
    "Pirate Ship Eleftheria Deck Pirate Revenant Skill 2": Ys8LocationData("Pirate Ship Eleftheria", 553, "event"),
    #"Pirate Ship Eleftheria Deck Psyches": Ys8LocationData("Pirate Ship Eleftheria", 624, "event"),
    # Ricotta Starting Skill
    "Ricotta Starting Skill Skill 1 Wild Spin": Ys8LocationData("Ricotta Starting Skill", 528, "event"),
    "Ricotta Starting Skill Skill 2 Handmade Trap": Ys8LocationData("Ricotta Starting Skill", 529, "event"),
    # Sahad Starting Skill
    "Sahad Starting Skill Skill 1 High Wave": Ys8LocationData("Sahad Starting Skill", 524, "event"),
    "Sahad Starting Skill Skill 2 Grand Anchor": Ys8LocationData("Sahad Starting Skill", 525, "event"),
    # Schlamm Jungle
    "Schlamm Jungle Entrance Chest 1": Ys8LocationData("Schlamm Jungle Front", 101, "chest"),
    "Schlamm Jungle Entrance Chest 2": Ys8LocationData("Schlamm Jungle Front", 102, "chest"),
    "Schlamm Jungle Entrance Chest 3": Ys8LocationData("Schlamm Jungle Front", 103, "chest"),
    "Schlamm Jungle North of Entrance Chest": Ys8LocationData("Schlamm Jungle Front", 104, "chest"),
    "Schlamm Jungle Mid-Boss Arena Chest": Ys8LocationData("Schlamm Jungle Mid-Boss Arena", 105, "chest"),
    "Schlamm Jungle Small Passage Chest 1": Ys8LocationData("Schlamm Jungle Muddy Path", 106, "chest"),
    "Schlamm Jungle Small Passage Chest 2": Ys8LocationData("Schlamm Jungle Muddy Path", 107, "chest"),
    "Schlamm Jungle Muddy Passage Chest 1": Ys8LocationData("Schlamm Jungle Field of Medicinal Herbs", 108, "chest"),
    "Schlamm Jungle Muddy Passage Chest 2": Ys8LocationData("Schlamm Jungle Muddy Path", 109, "chest"),
    "Schlamm Jungle End Chest": Ys8LocationData("Schlamm Jungle Before Boss", 110, "chest"),
    "Schlamm Jungle Entrance Euron Join": Ys8LocationData("Schlamm Jungle Front", 414, "event"),
    "Schlamm Jungle Midpoint Corpse": Ys8LocationData("Schlamm Jungle Muddy Path", 497, "event"),
    "Schlamm Jungle Boss Arena Laspisus Skill 1": Ys8LocationData("Schlamm Jungle Boss Arena", 566, "event"),
    "Schlamm Jungle Boss Arena Laspisus Skill 2": Ys8LocationData("Schlamm Jungle Boss Arena", 567, "event"),
    "Schlamm Jungle Mid-Boss Arena Magamandra Skill 1": Ys8LocationData("Schlamm Jungle Mid-Boss Arena", 568, "event"),
    "Schlamm Jungle Mid-Boss Arena Magamandra Skill 2": Ys8LocationData("Schlamm Jungle Mid-Boss Arena", 569, "event"),
    #"Schlamm Jungle Boss Arena Psyches": Ys8LocationData("Schlamm Jungle Boss Arena", 628, "event"),
    "Schlamm Jungle Muddy Passage Landmark": Ys8LocationData("Schlamm Jungle Field of Medicinal Herbs", 645, "event"),
    # Silent Tower
    "Silent Tower First Basement Chest 1": Ys8LocationData("Silent Tower", 262, "chest"),
    "Silent Tower First Basement Chest 2": Ys8LocationData("Silent Tower", 263, "chest"),
    "Silent Tower First Basement Chest 3": Ys8LocationData("Silent Tower", 264, "chest"),
    "Silent Tower Second Basement Chest 1": Ys8LocationData("Silent Tower", 265, "chest"),
    "Silent Tower Second Basement Chest 2": Ys8LocationData("Silent Tower", 266, "chest"),
    "Silent Tower Second Basement Chest 3": Ys8LocationData("Silent Tower", 267, "chest"),
    "Silent Tower Second Basement Chest 4": Ys8LocationData("Silent Tower", 268, "chest"),
    "Silent Tower Second Basement Mephorash Skill": Ys8LocationData("Silent Tower", 532, "event"),
    "Silent Tower Second Basement Mephorash": Ys8LocationData("Silent Tower", 586, "event"),
    "Silent Tower Second Basement Psyches": Ys8LocationData("Silent Tower", 617, "event"),
    # Solitude Island
    "Solitude Island Cave Chest": Ys8LocationData("Solitude Island", 50, "chest"),
    "Solitude Island Magna Carpa Second Carlan Join": Ys8LocationData("Solitude Island", 441, "event"),
    "Solitude Island Magna Carpa Driftage": Ys8LocationData("Solitude Island", 514, "event"),
    "Solitude Island Magna Carpa Landmark": Ys8LocationData("Solitude Island", 652, "event"),
    # Stone Pillar Wind Cave
    "Stone Pillar Wind Cave Stone Pillar Wind Cave Chest 1": Ys8LocationData("Stone Pillar Wind Cave", 396, "chest"),
    "Stone Pillar Wind Cave Stone Pillar Wind Cave Chest 2": Ys8LocationData("Stone Pillar Wind Cave", 397, "chest"),
    "Stone Pillar Wind Cave Stone Pillar Wind Cave Chest 3": Ys8LocationData("Stone Pillar Wind Cave", 398, "chest"),
    "Stone Pillar Wind Cave Stone Pillar Wind Cave Chest 4": Ys8LocationData("Stone Pillar Wind Cave", 399, "chest"),
    "Stone Pillar Wind Cave Stone Pillar Wind Cave Chest 5": Ys8LocationData("Stone Pillar Wind Cave", 400, "chest"),
    # Sunrise Beach
    "Sunrise Beach Sunrise Beach Dina Join": Ys8LocationData("Sunrise Beach", 412, "event"),
    "Sunrise Beach Sunrise Beach Master Kong Skill Sahad": Ys8LocationData("Sunrise Beach", 581, "event"),
    "Sunrise Beach Sunrise Beach Master Kong Sahad": Ys8LocationData("Sunrise Beach", 612, "event"),
    "Sunrise Beach Sunrise Beach Landmark": Ys8LocationData("Sunrise Beach", 644, "event"),
    # Temple of the Great Tree
    "Temple of the Great Tree Great Tree Garden Thanatos Join": Ys8LocationData("Temple of the Great Tree", 420, "event"),
    "Temple of the Great Tree Great Tree Garden Dana Join": Ys8LocationData("Temple of the Great Tree", 422, "event"),
    "Temple of the Great Tree Great Tree Garden Dana Join Event Flame Stone": Ys8LocationData("Temple of the Great Tree", 433, "event"),
    "Temple of the Great Tree Dana's Room Blue Score Location": Ys8LocationData("Temple of the Great Tree", 439, "event"),
    "Temple of the Great Tree Temple Boss Arena Brachion Skill 1": Ys8LocationData("Temple of the Great Tree", 558, "event"),
    "Temple of the Great Tree Temple Boss Arena Brachion Skill 2": Ys8LocationData("Temple of the Great Tree", 559, "event"),
    "Temple of the Great Tree Temple Boss Arena Brachion": Ys8LocationData("Temple of the Great Tree", 599, "event"),
    "Temple of the Great Tree Temple Boss Arena Psyches": Ys8LocationData("Temple of the Great Tree", 626, "event"),
    # The Primordial Passage
    "The Primordial Passage Dana's Tree Chest 1": Ys8LocationData("The Primordial Passage", 118, "chest"),
    "The Primordial Passage Dana's Tree Chest 2": Ys8LocationData("The Primordial Passage", 119, "chest"),
    # The Ruins of Eternia
    "The Ruins of Eternia Central District Chest 2": Ys8LocationData("The Ruins of Eternia", 195, "chest"),
    "The Ruins of Eternia Central District Chest 1": Ys8LocationData("The Ruins of Eternia", 196, "chest"),
    "The Ruins of Eternia Eastern Entrance Chest 1": Ys8LocationData("The Ruins of Eternia", 197, "chest"),
    "The Ruins of Eternia Eastern Entrance Chest 2": Ys8LocationData("The Ruins of Eternia", 198, "chest"),
    "The Ruins of Eternia Eastern Entrance Chest 3": Ys8LocationData("The Ruins of Eternia", 199, "chest"),
    "The Ruins of Eternia Residence Chest 1": Ys8LocationData("The Ruins of Eternia", 200, "chest"),
    "The Ruins of Eternia Residence Chest 2": Ys8LocationData("The Ruins of Eternia", 201, "chest"),
    "The Ruins of Eternia Palace Ruins Ship Blueprints": Ys8LocationData("The Ruins of Eternia", 511, "event"),
    "The Ruins of Eternia Central Stupa Jade Pendant": Ys8LocationData("The Ruins of Eternia", 635, "event"),
    # The Submerged Cemetery
    "The Submerged Cemetery The Submerged Cemetery Chest 1": Ys8LocationData("The Submerged Cemetery", 394, "chest"),
    "The Submerged Cemetery The Submerged Cemetery Chest 2": Ys8LocationData("The Submerged Cemetery", 395, "chest"),
    "The Submerged Cemetery The Submerged Cemetery Landmark": Ys8LocationData("The Submerged Cemetery", 658, "event"),
    # Towal Highway
    "Towal Highway Baja Tower Approach Chest": Ys8LocationData("Towal Highway", 172, "chest"),
    "Towal Highway Cliff Overlooking Chasm Chest": Ys8LocationData("Towal Highway", 191, "chest"),
    "Towal Highway Baja Tower Approach Katthew Join": Ys8LocationData("Towal Highway", 423, "event"),
    # Towering Coral Forest
    "Towering Coral Forest Entrance Chest 1": Ys8LocationData("Towering Coral Forest Front", 60, "chest"),
    "Towering Coral Forest Entrance Chest 2": Ys8LocationData("Towering Coral Forest Front", 61, "chest"),
    "Towering Coral Forest Walkways Chest 3": Ys8LocationData("Towering Coral Forest Front", 65, "chest"),
    "Towering Coral Forest Walkways Chest 4": Ys8LocationData("Towering Coral Forest Front", 66, "chest"),
    "Towering Coral Forest Walkways Chest 5": Ys8LocationData("Towering Coral Forest Front", 67, "chest"),
    "Towering Coral Forest Walkways Chest 6": Ys8LocationData("Towering Coral Forest Front", 68, "chest"),
    "Towering Coral Forest After Mid-Boss Chest 1": Ys8LocationData("Towering Coral Forest Rainbow Falls", 73, "chest"),
    "Towering Coral Forest After Mid-Boss Chest 2": Ys8LocationData("Towering Coral Forest Rainbow Falls", 74, "chest"),
    "Towering Coral Forest After Mid-Boss Chest 3": Ys8LocationData("Towering Coral Forest Rainbow Falls", 75, "chest"),
    "Towering Coral Forest After Mid-Boss Chest 4": Ys8LocationData("Towering Coral Forest Rainbow Falls", 76, "chest"),
    "Towering Coral Forest Rainbow Falls Chest 1": Ys8LocationData("Towering Coral Forest Rainbow Falls", 79, "chest"),
    "Towering Coral Forest Rainbow Falls Chest 2": Ys8LocationData("Towering Coral Forest Boss Area", 80, "chest"),
    "Towering Coral Forest Rainbow Falls Chest 3": Ys8LocationData("Towering Coral Forest Boss Area", 81, "chest"),
    "Towering Coral Forest Rainbow Falls Chest 4": Ys8LocationData("Towering Coral Forest Boss Area", 82, "chest"),
    "Towering Coral Forest Rainbow Falls Chest 5": Ys8LocationData("Towering Coral Forest Boss Area", 83, "chest"),
    "Towering Coral Forest Midpoint Chest": Ys8LocationData("Towering Coral Forest Front", 87, "chest"),
    "Towering Coral Forest End Chest": Ys8LocationData("Towering Coral Forest Boss Area", 89, "chest"),
    "Towering Coral Forest Midpoint Sir Carlan Join": Ys8LocationData("Towering Coral Forest Front", 407, "event"),
    "Towering Coral Forest Midpoint Kiergaard Join": Ys8LocationData("Towering Coral Forest Front", 408, "event"),
    "Towering Coral Forest After Mid-Boss Corpse": Ys8LocationData("Towering Coral Forest Corpse", 430, "event"),
    "Towering Coral Forest Boss Arena Clareon Skill 1": Ys8LocationData("Towering Coral Forest Boss Arena", 574, "event"),
    "Towering Coral Forest Boss Arena Clareon Skill 2": Ys8LocationData("Towering Coral Forest Boss Arena", 575, "event"),
    "Towering Coral Forest Mid-Boss Arena Serpentus Skill 1": Ys8LocationData("Towering Coral Forest Mid-Boss Arena", 576, "event"),
    "Towering Coral Forest Mid-Boss Arena Serpentus Skill 2": Ys8LocationData("Towering Coral Forest Mid-Boss Arena", 577, "event"),
    #"Towering Coral Forest Boss Arena Psyches": Ys8LocationData("Towering Coral Forest", 630, "event"),
    "Towering Coral Forest Rainbow Falls Landmark": Ys8LocationData("Towering Coral Forest Rainbow Falls", 639, "event"),
    # Towering Coral Forest (Night)
    "Towering Coral Forest (Night) Entrance Chest 1": Ys8LocationData("Towering Coral Forest (Night)", 62, "chest"),
    "Towering Coral Forest (Night) Entrance Chest 2": Ys8LocationData("Towering Coral Forest (Night)", 63, "chest"),
    "Towering Coral Forest (Night) Entrance Chest 3": Ys8LocationData("Towering Coral Forest (Night)", 64, "chest"),
    "Towering Coral Forest (Night) Walkways Chest 1": Ys8LocationData("Towering Coral Forest (Night)", 69, "chest"),
    "Towering Coral Forest (Night) Walkways Chest 2": Ys8LocationData("Towering Coral Forest (Night)", 70, "chest"),
    "Towering Coral Forest (Night) Walkways Chest 3": Ys8LocationData("Towering Coral Forest (Night)", 71, "chest"),
    "Towering Coral Forest (Night) Walkways Chest 4": Ys8LocationData("Towering Coral Forest (Night)", 72, "chest"),
    "Towering Coral Forest (Night) After Mid-Boss Chest 1": Ys8LocationData("Towering Coral Forest (Night)", 77, "chest"),
    "Towering Coral Forest (Night) After Mid-Boss Chest 2": Ys8LocationData("Towering Coral Forest (Night)", 78, "chest"),
    "Towering Coral Forest (Night) Rainbow Falls Chest 1": Ys8LocationData("Towering Coral Forest (Night)", 84, "chest"),
    "Towering Coral Forest (Night) Rainbow Falls Chest 2": Ys8LocationData("Towering Coral Forest (Night)", 85, "chest"),
    "Towering Coral Forest (Night) Rainbow Falls Chest 3": Ys8LocationData("Towering Coral Forest (Night)", 86, "chest"),
    "Towering Coral Forest (Night) Mid-Boss Arena Chest": Ys8LocationData("Towering Coral Forest (Night)", 88, "chest"),
    "Towering Coral Forest (Night) End Chest": Ys8LocationData("Towering Coral Forest (Night)", 90, "chest"),
    # Underground Water Vein
    "Underground Water Vein Submerged Area Chest 1": Ys8LocationData("Underground Water Vein", 389, "chest"),
    "Underground Water Vein Submerged Area Chest 2": Ys8LocationData("Lapis Mineral Vein Area", 390, "chest"),
    "Underground Water Vein Submerged Area Chest 3": Ys8LocationData("Underground Water Vein", 391, "chest"),
    "Underground Water Vein Submerged Area Pikkard": Ys8LocationData("Lapis Mineral Vein Area", 442, "event"),
    "Underground Water Vein Submerged Area Driftage": Ys8LocationData("Underground Water Vein", 517, "event"),
    "Underground Water Vein Lapis Mineral Vein Landmark": Ys8LocationData("Lapis Mineral Vein Area", 648, "event"),
    # Valley of Kings
    "Valley of Kings Entrance Chest 1": Ys8LocationData("Valley of Kings", 231, "chest"),
    "Valley of Kings Entrance Chest 2": Ys8LocationData("Valley of Kings", 232, "chest"),
    "Valley of Kings Entrance Chest 3": Ys8LocationData("Valley of Kings", 233, "chest"),
    "Valley of Kings Entrance Chest 4": Ys8LocationData("Valley of Kings", 234, "chest"),
    "Valley of Kings Entrance Chest 5": Ys8LocationData("Valley of Kings", 235, "chest"),
    "Valley of Kings Entrance Chest 6": Ys8LocationData("Valley of Kings", 236, "chest"),
    "Valley of Kings Northern Lower Level Chest 1": Ys8LocationData("Valley of Kings", 237, "chest"),
    "Valley of Kings Northern Lower Level Chest 2": Ys8LocationData("Valley of Kings", 238, "chest"),
    "Valley of Kings Mid-Boss Arena Chest": Ys8LocationData("Valley of Kings", 239, "chest"),
    "Valley of Kings Stairway (Statue Doors) Chest 1": Ys8LocationData("Valley of Kings", 240, "chest"),
    "Valley of Kings Stairway (Statue Doors) Chest 2": Ys8LocationData("Valley of Kings", 241, "chest"),
    "Valley of Kings Stairway (Statue Doors) Chest 3": Ys8LocationData("Valley of Kings", 242, "chest"),
    "Valley of Kings Stairway (Statue Doors) Chest 4": Ys8LocationData("Valley of Kings", 243, "chest"),
    "Valley of Kings End Chest 1": Ys8LocationData("Valley of Kings", 244, "chest"),
    "Valley of Kings End Chest 2": Ys8LocationData("Valley of Kings", 245, "chest"),
    "Valley of Kings End Chest 3": Ys8LocationData("Valley of Kings", 246, "chest"),
    "Valley of Kings End Chest 4": Ys8LocationData("Valley of Kings", 247, "chest"),
    "Valley of Kings Seren Garden Mistilteinn Event": Ys8LocationData("Valley of Kings", 432, "event"),
    "Valley of Kings Boss Arena Kill Boss": Ys8LocationData("Valley of Kings", 436, "event"),
    "Valley of Kings Boss Arena Basileus Skill 1": Ys8LocationData("Valley of Kings", 544, "event"),
    "Valley of Kings Boss Arena Basileus Skill 2": Ys8LocationData("Valley of Kings", 545, "event"),
    "Valley of Kings Mid-Boss Arena Doxa Griel Skill 1": Ys8LocationData("Valley of Kings", 546, "event"),
    "Valley of Kings Mid-Boss Arena Doxa Griel Skill 2": Ys8LocationData("Valley of Kings", 547, "event"),
    "Valley of Kings Boss Arena Basileus": Ys8LocationData("Valley of Kings", 592, "event"),
    "Valley of Kings Mid-Boss Arena Doxa Griel": Ys8LocationData("Valley of Kings", 593, "event"),
    "Valley of Kings Boss Arena Psyches": Ys8LocationData("Valley of Kings", 622, "event"),
    # Vista Ridge
    "Vista Ridge Vista Ridge Upper Chest 1": Ys8LocationData("Vista Ridge", 126, "chest"),
    "Vista Ridge Vista Ridge Upper Chest 2": Ys8LocationData("Vista Ridge", 127, "chest"),
    "Vista Ridge Vista Ridge Upper Franz Join": Ys8LocationData("Vista Ridge", 425, "event"),
    "Vista Ridge Vista Ridge Lower Master Kong Join": Ys8LocationData("Vista Ridge", 428, "event"),
    "Vista Ridge Vista Ridge Lower Master Kong Skill Adol": Ys8LocationData("Vista Ridge", 585, "event"),
    "Vista Ridge Vista Ridge Lower Master Kong Adol": Ys8LocationData("Vista Ridge", 616, "event"),
    # Outside Silent Tower
    "Water and Wood Hills Near Silent Tower Chest 1": Ys8LocationData("Outside Silent Tower", 98, "chest"),
    "Water and Wood Hills Near Silent Tower Chest 2": Ys8LocationData("Outside Silent Tower", 99, "chest"),
    # Waterdrop Cave
    "Waterdrop Cave Dilapidated Living Space Chest 2": Ys8LocationData("Waterdrop Cave", 378, "chest"),
    "Waterdrop Cave Dilapidated Living Space Chest 3": Ys8LocationData("Waterdrop Cave", 379, "chest"),
    "Waterdrop Cave Before Boss Arena Chest": Ys8LocationData("Waterdrop Cave", 380, "chest"),
    "Waterdrop Cave Coastal Outlook Captain Barbaros Join": Ys8LocationData("Waterdrop Cave", 402, "event"),
    "Waterdrop Cave Before Boss Arena Corpse": Ys8LocationData("Waterdrop Cave", 493, "event"),
    "Waterdrop Cave Boss Arena Byfteriza Skill": Ys8LocationData("Waterdrop Cave", 579, "event"),
    "Waterdrop Cave Boss Arena Byfteriza": Ys8LocationData("Waterdrop Cave", 610, "event"),
    # Weathervane Hills
    "Weathervane Hills South of Nameless Coast Rockslide Chest 1": Ys8LocationData("Weathervane Hills", 111, "chest"),
    "Weathervane Hills South of Nameless Coast Rockslide Chest 2": Ys8LocationData("Weathervane Hills", 112, "chest"),
    "Weathervane Hills Zephyr Hill Chest": Ys8LocationData("Weathervane Hills", 113, "chest"),
    "Weathervane Hills Zephyr Hill Landmark": Ys8LocationData("Weathervane Hills", 647, "event"),
    "Headwater Falls Headwater Falls Chest 1": Ys8LocationData("Weathervane Hills", 384, "chest"),
    "Headwater Falls Headwater Falls Chest 2": Ys8LocationData("Weathervane Hills Past Insect Nest", 385, "chest"),
    "Headwater Falls Headwater Falls Chest 3": Ys8LocationData("Weathervane Hills Past Insect Nest", 386, "chest"),
    "Headwater Falls Headwater Falls Chest 4": Ys8LocationData("Weathervane Hills Past Insect Nest", 387, "chest"),
    "Headwater Falls Headwater Falls Chest 5": Ys8LocationData("Weathervane Hills Past Insect Nest", 388, "chest"),
    # Western Foot of Gendarme
    "Western Foot of Gendarme Moutain Base Chest": Ys8LocationData("Western Foot of Gendarme", 116, "chest"),
    "Western Foot of Gendarme Near Cavern of the Ancient King Chest": Ys8LocationData("Western Foot of Gendarme", 117, "chest"),
    "Western Foot of Gendarme Near Cavern of the Ancient King Austin Join": Ys8LocationData("Western Foot of Gendarme", 418, "event"),
    "Cavern of the Ancient King Cavern of the Ancient King Cave Wall": Ys8LocationData("Western Foot of Gendarme", 431, "event"),
    "Western Foot of Gendarme Near Cavern of the Ancient King Landmark": Ys8LocationData("Western Foot of Gendarme", 646, "event")
}

event_location_table: Dict[str, Ys8LocationData] = {
    "Octus Overlook Selection Sphere Goal": Ys8LocationData("Final Boss", 10000, "None"),
    "Silent Tower Second Basement Mephorash": Ys8LocationData("Silent Tower", 10001, None),
    "Octus Overlook Path of the Sky Era Psyche-Ura": Ys8LocationData("Octus Overlook", 10002, None),
    "Octus Overlook Path of the Insectoid Era Psyche-Nestor": Ys8LocationData("Octus Overlook", 10003, None),
    "Octus Overlook Path of the Frozen Era Psyche-Minos": Ys8LocationData("Octus Overlook", 10004, None),
    "Octus Overlook Path of the Ocean Era Psyche-Hydra": Ys8LocationData("Octus Overlook", 10005, None),
    "Calm Inlet Calm Inlet (Castaway Village Area) Silvia": Ys8LocationData("Calm Inlet", 10006, None),
    "Valley of Kings Boss Arena Basileus": Ys8LocationData("Valley of Kings", 10007, None),
    "Valley of Kings Mid-Boss Arena Doxa Griel": Ys8LocationData("Valley of Kings", 10008, None),
    "Archeozoic Chasm Boss Arena Oceanus": Ys8LocationData("Archeozoic Chasm", 10009, None),
    "Archeozoic Chasm Mid-Boss Arena Coelacantos": Ys8LocationData("Archeozoic Chasm", 10010, None),
    "Pirate Ship Eleftheria Deck Pirate Revenant": Ys8LocationData("Pirate Ship Eleftheria", 10011, None),
    "Baja Tower Boss Arena Carveros": Ys8LocationData("Baja Tower", 10012, None),
    "Baja Tower Mid-Boss Arena Exmetal": Ys8LocationData("Baja Tower", 10013, None),
    "Temple of the Great Tree Temple Boss Arena Brachion": Ys8LocationData("Temple of the Great Tree", 10014, None),
    "Mont Gendarme Boss Arena Giasburn": Ys8LocationData("Mont Gendarme", 10015, None),
    "Mont Gendarme Mid-Boss Arena Avalodragil 2": Ys8LocationData("Mont Gendarme", 10016, None),
    "Odd Rock Coast Odd Rock Coast Kiergaard Weissman": Ys8LocationData("Odd Rock Coast", 10017, None),
    "Schlamm Jungle Boss Arena Laspisus": Ys8LocationData("Schlamm Jungle", 10018, None),
    "Schlamm Jungle Mid-Boss Arena Magamandra": Ys8LocationData("Schlamm Jungle", 10019, None),
    "Eroded Valley Boss Arena Gargantula": Ys8LocationData("Eroded Valley", 10020, None),
    "Eroded Valley Mid-Boss Arena Lonbrigius": Ys8LocationData("Eroded Valley", 10021, None),
    "Towering Coral Forest Boss Arena Clareon": Ys8LocationData("Towering Coral Forest", 10022, None),
    "Towering Coral Forest Mid-Boss Arena Serpentus": Ys8LocationData("Towering Coral Forest", 10023, None),
    "Nameless Coast First Avalodragil Arena Avalodragil": Ys8LocationData("Nameless Coast", 10024, None),
    "Waterdrop Cave Boss Arena Byfteriza": Ys8LocationData("Waterdrop Cave", 10025, None),
    "Roaring Seashore Parasequoia Master Kong Ricotta": Ys8LocationData("Roaring Seashore", 10026, None),
    "Sunrise Beach Sunrise Beach Master Kong Sahad": Ys8LocationData("Sunrise Beach", 10027, None),
    "Odd Rock Coast Odd Rock Coast Master Kong Dana": Ys8LocationData("Odd Rock Coast", 10028, None),
    "Mont Gendarme Boss Arena Master Kong Laxia": Ys8LocationData("Mont Gendarme", 10029, None),
    "Pangaia Plains Ancient Tree Master Kong Hummel": Ys8LocationData("Pangaia Plains", 10030, None),
    "Vista Ridge Vista Ridge Lower Master Kong Adol": Ys8LocationData("Vista Ridge", 10031, None)
}

# === PAST LOCATIONS (PRESERVED FOR REFERENCE) ===
# These locations are commented out to separate them from active randomization
# but are preserved here for potential future use or reference.
# past_location_table: Dict[str, Ys8LocationData] = {
#    "Sanctuary Crypt - Chamber of Braziers (Past) Entrance Chest": Ys8LocationData("Sanctuary Crypt - Chamber of Braziers (Past)", 282, "chest"),
#    "Sanctuary Crypt - Chamber of Braziers (Past) First Brazier Chest 1": Ys8LocationData("Sanctuary Crypt - Chamber of Braziers (Past)", 285, "chest"),
#    "Sanctuary Crypt - Chamber of Braziers (Past) First Brazier Chest 2": Ys8LocationData("Sanctuary Crypt - Chamber of Braziers (Past)", 286, "chest"),
#    "Sanctuary Crypt - Chamber of Braziers (Past) Wind Tunnel Chest 1": Ys8LocationData("Sanctuary Crypt - Chamber of Braziers (Past)", 289, "chest"),
#    "Sanctuary Crypt - Chamber of Braziers (Past) Wind Tunnel Chest 2": Ys8LocationData("Sanctuary Crypt - Chamber of Braziers (Past)", 290, "chest"),
#    "Sanctuary Crypt - Chamber of Braziers (Past) Boss Arena Chest": Ys8LocationData("Sanctuary Crypt - Chamber of Braziers (Past)", 292, "chest"),
#    "Sanctuary Crypt - Chamber of Stone (Past) Stone and Rock Block Puzzle Chest": Ys8LocationData("Sanctuary Crypt - Chamber of Stone (Past)", 298, "chest"),
#    "Sanctuary Crypt - Chamber of Stone (Past) Stone and Rock Floating Block Puzzle with Gaps Chest": Ys8LocationData("Sanctuary Crypt - Chamber of Stone (Past)", 299, "chest"),
#    "Sanctuary Crypt - Chamber of Stone (Past) Stone and Rock Floating Block Puzzle Chest": Ys8LocationData("Sanctuary Crypt - Chamber of Stone (Past)", 300, "chest"),
#    "Sanctuary Crypt - Chamber of Stone (Past) Boss Arena Chest": Ys8LocationData("Sanctuary Crypt - Chamber of Stone (Past)", 302, "chest"),
#    "Sanctuary Crypt - Chamber of Clairvoyance (Past) Entrance Chest 1": Ys8LocationData("Sanctuary Crypt - Chamber of Clairvoyance (Past)", 310, "chest"),
#    "Sanctuary Crypt - Chamber of Clairvoyance (Past) Entrance Chest 2": Ys8LocationData("Sanctuary Crypt - Chamber of Clairvoyance (Past)", 311, "chest"),
#    "Sanctuary Crypt - Chamber of Clairvoyance (Past) Entrance Chest 3": Ys8LocationData("Sanctuary Crypt - Chamber of Clairvoyance (Past)", 312, "chest"),
#    "Sanctuary Crypt - Chamber of Clairvoyance (Past) Entrance Chest 4": Ys8LocationData("Sanctuary Crypt - Chamber of Clairvoyance (Past)", 313, "chest"),
#    "Sanctuary Crypt - Chamber of Clairvoyance (Past) Entrance Chest 5": Ys8LocationData("Sanctuary Crypt - Chamber of Clairvoyance (Past)", 314, "chest"),
#    "Sanctuary Crypt - Chamber of Clairvoyance (Past) Entrance Chest 6": Ys8LocationData("Sanctuary Crypt - Chamber of Clairvoyance (Past)", 315, "chest"),
#    "Sanctuary Crypt - Chamber of Clairvoyance (Past) Entrance Chest 7": Ys8LocationData("Sanctuary Crypt - Chamber of Clairvoyance (Past)", 316, "chest"),
#    "Sanctuary Crypt - Chamber of Clairvoyance (Past) Entrance Chest 8": Ys8LocationData("Sanctuary Crypt - Chamber of Clairvoyance (Past)", 317, "chest"),
#    "Sanctuary Crypt - Chamber of Clairvoyance (Past) Entrance Chest 9": Ys8LocationData("Sanctuary Crypt - Chamber of Clairvoyance (Past)", 318, "chest"),
#    "Sanctuary Crypt - Chamber of Clairvoyance (Past) Entrance Chest 10": Ys8LocationData("Sanctuary Crypt - Chamber of Clairvoyance (Past)", 319, "chest"),
#    "Sanctuary Crypt - Chamber of Clairvoyance (Past) Floating Block Puzzle Chest 1": Ys8LocationData("Sanctuary Crypt - Chamber of Clairvoyance (Past)", 323, "chest"),
#    "Sanctuary Crypt - Chamber of Clairvoyance (Past) Floating Block Puzzle Chest 2": Ys8LocationData("Sanctuary Crypt - Chamber of Clairvoyance (Past)", 324, "chest"),
#    "Sanctuary Crypt - Chamber of Clairvoyance (Past) Floating Block Puzzle Chest 3": Ys8LocationData("Sanctuary Crypt - Chamber of Clairvoyance (Past)", 325, "chest"),
#    "Sanctuary Crypt - Chamber of Clairvoyance (Past) Floating Block Puzzle Chest 4": Ys8LocationData("Sanctuary Crypt - Chamber of Clairvoyance (Past)", 326, "chest"),
#    "Sanctuary Crypt - Chamber of Clairvoyance (Past) Floating Block Puzzle Chest 5": Ys8LocationData("Sanctuary Crypt - Chamber of Clairvoyance (Past)", 327, "chest"),
#    "Sanctuary Crypt - Chamber of Clairvoyance (Past) Floating Block Puzzle Chest 6": Ys8LocationData("Sanctuary Crypt - Chamber of Clairvoyance (Past)", 328, "chest"),
#    "Sanctuary Crypt - Chamber of Clairvoyance (Past) Boss Arena Chest": Ys8LocationData("Sanctuary Crypt - Chamber of Clairvoyance (Past)", 330, "chest"),
#    "Sanctuary Crypt - Chamber of Frost (Past) Entrance Chest 1": Ys8LocationData("Sanctuary Crypt - Chamber of Frost (Past)", 335, "chest"),
#    "Sanctuary Crypt - Chamber of Frost (Past) Entrance Chest 2": Ys8LocationData("Sanctuary Crypt - Chamber of Frost (Past)", 336, "chest"),
#    "Sanctuary Crypt - Chamber of Frost (Past) Frozen Statue Room Chest 1": Ys8LocationData("Sanctuary Crypt - Chamber of Frost (Past)", 341, "chest"),
#    "Sanctuary Crypt - Chamber of Frost (Past) Frozen Statue Room Chest 2": Ys8LocationData("Sanctuary Crypt - Chamber of Frost (Past)", 342, "chest"),
#    "Sanctuary Crypt - Chamber of Frost (Past) Frozen Statue Room Chest 3": Ys8LocationData("Sanctuary Crypt - Chamber of Frost (Past)", 343, "chest"),
#    "Sanctuary Crypt - Chamber of Frost (Past) Boss Arena Chest": Ys8LocationData("Sanctuary Crypt - Chamber of Frost (Past)", 345, "chest"),
#    "Sanctuary Crypt - Chamber of Magma (Past) Entrance Chest 1": Ys8LocationData("Sanctuary Crypt - Chamber of Magma (Past)", 349, "chest"),
#    "Sanctuary Crypt - Chamber of Magma (Past) Entrance Chest 2": Ys8LocationData("Sanctuary Crypt - Chamber of Magma (Past)", 350, "chest"),
#    "Sanctuary Crypt - Chamber of Magma (Past) Eastern Hall Chest 1": Ys8LocationData("Sanctuary Crypt - Chamber of Magma (Past)", 352, "chest"),
#    "Sanctuary Crypt - Chamber of Magma (Past) Eastern Hall Chest 2": Ys8LocationData("Sanctuary Crypt - Chamber of Magma (Past)", 353, "chest"),
#    "Sanctuary Crypt - Chamber of Magma (Past) Eastern Hall Chest 3": Ys8LocationData("Sanctuary Crypt - Chamber of Magma (Past)", 354, "chest"),
#    "Sanctuary Crypt - Chamber of Magma (Past) Central Chamber North of Entrance Chest 1": Ys8LocationData("Sanctuary Crypt - Chamber of Magma (Past)", 355, "chest"),
#    "Sanctuary Crypt - Chamber of Magma (Past) Central Chamber North of Entrance Chest 2": Ys8LocationData("Sanctuary Crypt - Chamber of Magma (Past)", 356, "chest"),
#    "Sanctuary Crypt - Chamber of Magma (Past) Western Hall Chest 1": Ys8LocationData("Sanctuary Crypt - Chamber of Magma (Past)", 361, "chest"),
#    "Sanctuary Crypt - Chamber of Magma (Past) Western Hall Chest 2": Ys8LocationData("Sanctuary Crypt - Chamber of Magma (Past)", 362, "chest"),
#    "Sanctuary Crypt - Chamber of Magma (Past) Western Hall Chest 3": Ys8LocationData("Sanctuary Crypt - Chamber of Magma (Past)", 363, "chest"),
#    "Sanctuary Crypt - Chamber of Magma (Past) Boss Arena Chest 1": Ys8LocationData("Sanctuary Crypt - Chamber of Magma (Past)", 367, "chest"),
#    "Sanctuary Crypt - Chamber of Magma (Past) Boss Arena Chest 4": Ys8LocationData("Sanctuary Crypt - Chamber of Magma (Past)", 368, "chest"),
#    "Sanctuary Crypt - Chamber of the Final Trial (Past) Big Staircase Chest 1": Ys8LocationData("Sanctuary Crypt - Chamber of the Final Trial (Past)", 373, "chest"),
#    "Sanctuary Crypt - Chamber of the Final Trial (Past) Big Staircase Chest 2": Ys8LocationData("Sanctuary Crypt - Chamber of the Final Trial (Past)", 374, "chest"),
#    "Sanctuary Crypt - Chamber of the Final Trial (Past) Big Staircase Chest 3": Ys8LocationData("Sanctuary Crypt - Chamber of the Final Trial (Past)", 375, "chest"),
#    "Sanctuary Crypt - Chamber of the Final Trial (Past) Big Staircase Chest 4": Ys8LocationData("Sanctuary Crypt - Chamber of the Final Trial (Past)", 376, "chest"),
# }

# === PAST LOCATIONS (PRESERVED FOR REFERENCE) ===
# These locations are commented out to separate them from active randomization
# but are preserved here for potential future use or reference.
# these are duplicate chests that share flags with the non-dawn versions, they shouldn't be accessible in the randomizer but are preserved here for reference
# duplicate_location_table: Dict[str, Ys8LocationData] = {
#     "Great River Valley Large Shoreline - Dawn Chest 1": Ys8LocationData("Great River Valley Area", 47, "chest"),
#     "Great River Valley Large Shoreline - Dawn Chest 2": Ys8LocationData("Great River Valley Area", 48, "chest"),
#     "Great River Valley Large Shoreline - Dawn Chest 3": Ys8LocationData("Great River Valley Area", 49, "chest"),

lookup_id_to_name: typing.Dict[int, str] = {data.code: item_name for item_name, data in location_table.items() if data.code}

#Make location categories
location_name_groups: Dict[str, Set[str]] = {}
for location in location_table.keys():
    category = location_table[location].category
    if category not in location_name_groups.keys():
        location_name_groups[category] = set()
    location_name_groups[category].add(location)
